const peripheralCounts = {
    "F29H859TU8-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29H859TM8-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29H859DU6-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29H850TU9": {
        "EMIF1"   : 1,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 1,
    },
    "F29H850DU7": {
        "EMIF1"   : 1,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 1,
    },
    "F29H850DM3": {
        "EMIF1"   : 1,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 1,
    },
    "F29H850DM4": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29H850DM6": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29H850DM7": {
        "EMIF1"   : 1,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 1,
        "MCANF"   : 1,
        "LINB"    : 1,
        "ECAT"    : 1,
    },
    "F29P589DU5-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 0,
        "MCANF"   : 0,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29P589DM5-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 0,
        "MCANF"   : 0,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29P580DM5": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 1,
        "MCANE"   : 0,
        "MCANF"   : 0,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29P329SJ1-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 0,
        "MCANE"   : 0,
        "MCANF"   : 0,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29P329SM1-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 0,
        "MCANE"   : 0,
        "MCANF"   : 0,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
    "F29P329SM2-Q": {
        "EMIF1"   : 0,
        "MCANC"   : 1,
        "MCAND"   : 0,
        "MCANE"   : 0,
        "MCANF"   : 0,
        "LINB"    : 1,
        "ECAT"    : 0,
    },
}

exports = {
    peripheralCounts
}
