let XBAR_MUXES = [
	{ name: "XBAR_MUX00", displayName:"MUX 00" },
	{ name: "XBAR_MUX01", displayName:"MUX 01" },
	{ name: "XBAR_MUX02", displayName:"MUX 02" },
	{ name: "XBAR_MUX03", displayName:"MUX 03" },
	{ name: "XBAR_MUX04", displayName:"MUX 04" },
	{ name: "XBAR_MUX05", displayName:"MUX 05" },
	{ name: "XBAR_MUX06", displayName:"MUX 06" },
	{ name: "XBAR_MUX07", displayName:"MUX 07" },
	{ name: "XBAR_MUX08", displayName:"MUX 08" },
	{ name: "XBAR_MUX09", displayName:"MUX 09" },
	{ name: "XBAR_MUX10", displayName:"MUX 10" },
	{ name: "XBAR_MUX11", displayName:"MUX 11" },
	{ name: "XBAR_MUX12", displayName:"MUX 12" },
	{ name: "XBAR_MUX13", displayName:"MUX 13" },
	{ name: "XBAR_MUX14", displayName:"MUX 14" },
	{ name: "XBAR_MUX15", displayName:"MUX 15" },
	{ name: "XBAR_MUX16", displayName:"MUX 16" },
	{ name: "XBAR_MUX17", displayName:"MUX 17" },
	{ name: "XBAR_MUX18", displayName:"MUX 18" },
	{ name: "XBAR_MUX19", displayName:"MUX 19" },
	{ name: "XBAR_MUX20", displayName:"MUX 20" },
	{ name: "XBAR_MUX21", displayName:"MUX 21" },
	{ name: "XBAR_MUX22", displayName:"MUX 22" },
	{ name: "XBAR_MUX23", displayName:"MUX 23" },
	{ name: "XBAR_MUX24", displayName:"MUX 24" },
	{ name: "XBAR_MUX25", displayName:"MUX 25" },
	{ name: "XBAR_MUX26", displayName:"MUX 26" },
	{ name: "XBAR_MUX27", displayName:"MUX 27" },
	{ name: "XBAR_MUX28", displayName:"MUX 28" },
	{ name: "XBAR_MUX29", displayName:"MUX 29" },
	{ name: "XBAR_MUX30", displayName:"MUX 30" },
	{ name: "XBAR_MUX31", displayName:"MUX 31" },
]
let XBAR_OutputNum = [
	{ name: "XBAR_OUTPUT1", displayName: "OUTPUT1 of the X-BAR" },
	{ name: "XBAR_OUTPUT2", displayName: "OUTPUT2 of the X-BAR" },
	{ name: "XBAR_OUTPUT3", displayName: "OUTPUT3 of the X-BAR" },
	{ name: "XBAR_OUTPUT4", displayName: "OUTPUT4 of the X-BAR" },
	{ name: "XBAR_OUTPUT5", displayName: "OUTPUT5 of the X-BAR" },
	{ name: "XBAR_OUTPUT6", displayName: "OUTPUT6 of the X-BAR" },
	{ name: "XBAR_OUTPUT7", displayName: "OUTPUT7 of the X-BAR" },
	{ name: "XBAR_OUTPUT8", displayName: "OUTPUT8 of the X-BAR" },
	{ name: "XBAR_OUTPUT9", displayName: "OUTPUT9 of the X-BAR" },
	{ name: "XBAR_OUTPUT10", displayName: "OUTPUT10 of the X-BAR" },
	{ name: "XBAR_OUTPUT11", displayName: "OUTPUT11 of the X-BAR" },
	{ name: "XBAR_OUTPUT12", displayName: "OUTPUT12 of the X-BAR" },
	{ name: "XBAR_OUTPUT13", displayName: "OUTPUT13 of the X-BAR" },
	{ name: "XBAR_OUTPUT14", displayName: "OUTPUT14 of the X-BAR" },
	{ name: "XBAR_OUTPUT15", displayName: "OUTPUT15 of the X-BAR" },
	{ name: "XBAR_OUTPUT16", displayName: "OUTPUT16 of the X-BAR" },
]
let XBAR_TripNum = [
	{ name: "XBAR_TRIP1", displayName: "TRIP1 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP2", displayName: "TRIP2 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP3", displayName: "TRIP3 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP4", displayName: "TRIP4 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP5", displayName: "TRIP5 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP6", displayName: "TRIP6 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP7", displayName: "TRIP7 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP8", displayName: "TRIP8 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP9", displayName: "TRIP9 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP10", displayName: "TRIP10 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP11", displayName: "TRIP11 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP12", displayName: "TRIP12 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP13", displayName: "TRIP13 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP14", displayName: "TRIP14 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP15", displayName: "TRIP15 of the ePWM X-BAR" },
	{ name: "XBAR_TRIP16", displayName: "TRIP16 of the ePWM X-BAR" },
]
let XBAR_AuxSigNum = [
	{ name: "XBAR_AUXSIG0", displayName: "AUXSIG0 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG1", displayName: "AUXSIG1 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG2", displayName: "AUXSIG2 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG3", displayName: "AUXSIG3 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG4", displayName: "AUXSIG4 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG5", displayName: "AUXSIG5 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG6", displayName: "AUXSIG6 of the CLB X-BAR" },
	{ name: "XBAR_AUXSIG7", displayName: "AUXSIG7 of the CLB X-BAR" },
]
let XBAR_InputNum = [
	{ name: "XBAR_INPUT1", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWM TRIP[TZ1,TRIP1], EPWMDEL, ECAP, ERAD, ECAT" },
	{ name: "XBAR_INPUT2", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWM TRIP[TZ2,TRIP2], EPWMDEL, ECAP, ERAD, ECAT" },
	{ name: "XBAR_INPUT3", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWM TRIP[TZ3,TRIP3], EPWMDEL, ECAP, ERAD, ECAT" },
	{ name: "XBAR_INPUT4", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, XINT[XINT1], EPWMDEL, ECAP, ERAD, ECAT" },
	{ name: "XBAR_INPUT5", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, XINT[XINT2], EPWMDEL, ECAP, ADCSOC[ADCEXTSOC], SYNCIN[EXTSYNCIN1], ERAD, ECAT" },
	{ name: "XBAR_INPUT6", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, XINT[XINT3], EPWM TRIP[TRIP6], EPWMDEL, ECAP, SYNCIN[EXTSYNCIN2], ERAD, ECAT" },
	{ name: "XBAR_INPUT7", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, ERAD, CMPSS[CMPSS1_EXT_FILTIN_H,CMPSS3_EXT_FILTIN_H], ECAT" },
	{ name: "XBAR_INPUT8", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, ERAD, CMPSS[CMPSS1_EXT_FILTIN_L ,CMPSS3_EXT_FILTIN_L], ECAT" },
	{ name: "XBAR_INPUT9", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, ERAD, CMPSS[CMPSS2_EXT_FILTIN_H,CMPSS4_EXT_FILTIN_H], ECAT" },
	{ name: "XBAR_INPUT10", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, ERAD, CMPSS[CMPSS2_EXT_FILTIN_L ,CMPSS4_EXT_FILTIN_L], ECAT" },
	{ name: "XBAR_INPUT11", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, DCCx[CLK1], ERAD, ECAT" },
	{ name: "XBAR_INPUT12", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, DCCx[CLK1], ERAD, ECAT" },
	{ name: "XBAR_INPUT13", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, XINT[XINT4], EPWMDEL, ECAP, EPG[EPG1IN1], ERAD, ECAT" },
	{ name: "XBAR_INPUT14", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, XINT[XINT5], EPWMDEL, ECAP, EPG[EPG1IN2], ERAD, ECAT" },
	{ name: "XBAR_INPUT15", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, DCCx[CLK1], EPG[EPG1IN3], ERAD, ECAT" },
	{ name: "XBAR_INPUT16", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, ECAP, DCCx[CLK0], EPG[EPG1IN4], ERAD, ECAT" },
	{ name: "XBAR_INPUT17", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT18", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT19", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT20", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT21", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT22", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT23", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT24", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT25", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT26", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT27", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT28", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT29", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT30", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT31", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT32", displayName: "X-BARs, CLBXBAR, OUTPUTXBAR, EPWMDEL, CLB" },
	{ name: "XBAR_INPUT33", displayName: "EQEP[EQEP1A], WADI1[WADI1]" },
	{ name: "XBAR_INPUT34", displayName: "EQEP[EQEP1B], WADI1[WADI1]" },
	{ name: "XBAR_INPUT35", displayName: "EQEP[EQEP1I], WADI1[WADI1]" },
	{ name: "XBAR_INPUT36", displayName: "EQEP[EQEP1S], WADI1[WADI1]" },
	{ name: "XBAR_INPUT37", displayName: "EQEP[EQEP2A], WADI1[WADI1]" },
	{ name: "XBAR_INPUT38", displayName: "EQEP[EQEP2B], WADI1[WADI1]" },
	{ name: "XBAR_INPUT39", displayName: "EQEP[EQEP2I], WADI1[WADI1]" },
	{ name: "XBAR_INPUT40", displayName: "EQEP[EQEP2S], WADI1[WADI1]" },
	{ name: "XBAR_INPUT41", displayName: "EQEP[EQEP3A], WADI1[WADI1]" },
	{ name: "XBAR_INPUT42", displayName: "EQEP[EQEP3B], WADI1[WADI1]" },
	{ name: "XBAR_INPUT43", displayName: "EQEP[EQEP3I], WADI1[WADI1]" },
	{ name: "XBAR_INPUT44", displayName: "EQEP[EQEP3S], WADI1[WADI1]" },
	{ name: "XBAR_INPUT45", displayName: "EQEP[EQEP4A], WADI1[WADI1]" },
	{ name: "XBAR_INPUT46", displayName: "EQEP[EQEP4B], WADI1[WADI1]" },
	{ name: "XBAR_INPUT47", displayName: "EQEP[EQEP4I], WADI1[WADI1]" },
	{ name: "XBAR_INPUT48", displayName: "EQEP[EQEP4S], WADI1[WADI1]" },
	{ name: "XBAR_INPUT49", displayName: "EQEP[EQEP5A], WADI2[WADI2]" },
	{ name: "XBAR_INPUT50", displayName: "EQEP[EQEP5B], WADI2[WADI2]" },
	{ name: "XBAR_INPUT51", displayName: "EQEP[EQEP5I], WADI2[WADI2]" },
	{ name: "XBAR_INPUT52", displayName: "EQEP[EQEP5S], WADI2[WADI2]" },
	{ name: "XBAR_INPUT53", displayName: "EQEP[EQEP6A], WADI2[WADI2]" },
	{ name: "XBAR_INPUT54", displayName: "EQEP[EQEP6B], WADI2[WADI2]" },
	{ name: "XBAR_INPUT55", displayName: "EQEP[EQEP6I], WADI2[WADI2]" },
	{ name: "XBAR_INPUT56", displayName: "EQEP[EQEP6S], WADI2[WADI2]" },
	{ name: "XBAR_INPUT57", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT58", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT59", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT60", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT61", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT62", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT63", displayName: "WADI2[WADI2]" },
	{ name: "XBAR_INPUT64", displayName: "WADI2[WADI2]" },
]
let XBAR_OutputXbarInputSource = [
	{ name: "XBAR_OUT_CMPSS1_CTRIPOUTH", displayName: "CMPSS1 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS1_CTRIPOUTL", displayName: "CMPSS1 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS2_CTRIPOUTH", displayName: "CMPSS2 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS2_CTRIPOUTL", displayName: "CMPSS2 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS3_CTRIPOUTH", displayName: "CMPSS3 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS3_CTRIPOUTL", displayName: "CMPSS3 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS4_CTRIPOUTH", displayName: "CMPSS4 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS4_CTRIPOUTL", displayName: "CMPSS4 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS5_CTRIPOUTH", displayName: "CMPSS5 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS5_CTRIPOUTL", displayName: "CMPSS5 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS6_CTRIPOUTH", displayName: "CMPSS6 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS6_CTRIPOUTL", displayName: "CMPSS6 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS7_CTRIPOUTH", displayName: "CMPSS7 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS7_CTRIPOUTL", displayName: "CMPSS7 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS8_CTRIPOUTH", displayName: "CMPSS8 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS8_CTRIPOUTL", displayName: "CMPSS8 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS9_CTRIPOUTH", displayName: "CMPSS9 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS9_CTRIPOUTL", displayName: "CMPSS9 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS10_CTRIPOUTH", displayName: "CMPSS10 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS10_CTRIPOUTL", displayName: "CMPSS10 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS11_CTRIPOUTH", displayName: "CMPSS11 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS11_CTRIPOUTL", displayName: "CMPSS11 CTRIPOUTL" },
	{ name: "XBAR_OUT_CMPSS12_CTRIPOUTH", displayName: "CMPSS12 CTRIPOUTH" },
	{ name: "XBAR_OUT_CMPSS12_CTRIPOUTL", displayName: "CMPSS12 CTRIPOUTL" },
	{ name: "XBAR_OUT_SD1FLT1_COMPH", displayName: "SD1FLT1 COMPH" },
	{ name: "XBAR_OUT_SD1FLT1_COMPL", displayName: "SD1FLT1 COMPL" },
	{ name: "XBAR_OUT_SD1FLT2_COMPH", displayName: "SD1FLT2 COMPH" },
	{ name: "XBAR_OUT_SD1FLT2_COMPL", displayName: "SD1FLT2 COMPL" },
	{ name: "XBAR_OUT_SD1FLT3_COMPH", displayName: "SD1FLT3 COMPH" },
	{ name: "XBAR_OUT_SD1FLT3_COMPL", displayName: "SD1FLT3 COMPL" },
	{ name: "XBAR_OUT_SD1FLT4_COMPH", displayName: "SD1FLT4 COMPH" },
	{ name: "XBAR_OUT_SD1FLT4_COMPL", displayName: "SD1FLT4 COMPL" },
	{ name: "XBAR_OUT_SD2FLT1_COMPH", displayName: "SD2FLT1 COMPH" },
	{ name: "XBAR_OUT_SD2FLT1_COMPL", displayName: "SD2FLT1 COMPL" },
	{ name: "XBAR_OUT_SD2FLT2_COMPH", displayName: "SD2FLT2 COMPH" },
	{ name: "XBAR_OUT_SD2FLT2_COMPL", displayName: "SD2FLT2 COMPL" },
	{ name: "XBAR_OUT_SD2FLT3_COMPH", displayName: "SD2FLT3 COMPH" },
	{ name: "XBAR_OUT_SD2FLT3_COMPL", displayName: "SD2FLT3 COMPL" },
	{ name: "XBAR_OUT_SD2FLT4_COMPH", displayName: "SD2FLT4 COMPH" },
	{ name: "XBAR_OUT_SD2FLT4_COMPL", displayName: "SD2FLT4 COMPL" },
	{ name: "XBAR_OUT_SD3FLT1_COMPH", displayName: "SD3FLT1 COMPH" },
	{ name: "XBAR_OUT_SD3FLT1_COMPL", displayName: "SD3FLT1 COMPL" },
	{ name: "XBAR_OUT_SD3FLT2_COMPH", displayName: "SD3FLT2 COMPH" },
	{ name: "XBAR_OUT_SD3FLT2_COMPL", displayName: "SD3FLT2 COMPL" },
	{ name: "XBAR_OUT_SD3FLT3_COMPH", displayName: "SD3FLT3 COMPH" },
	{ name: "XBAR_OUT_SD3FLT3_COMPL", displayName: "SD3FLT3 COMPL" },
	{ name: "XBAR_OUT_SD3FLT4_COMPH", displayName: "SD3FLT4 COMPH" },
	{ name: "XBAR_OUT_SD3FLT4_COMPL", displayName: "SD3FLT4 COMPL" },
	{ name: "XBAR_OUT_SD4FLT1_COMPH", displayName: "SD4FLT1 COMPH" },
	{ name: "XBAR_OUT_SD4FLT1_COMPL", displayName: "SD4FLT1 COMPL" },
	{ name: "XBAR_OUT_SD4FLT2_COMPH", displayName: "SD4FLT2 COMPH" },
	{ name: "XBAR_OUT_SD4FLT2_COMPL", displayName: "SD4FLT2 COMPL" },
	{ name: "XBAR_OUT_SD4FLT3_COMPH", displayName: "SD4FLT3 COMPH" },
	{ name: "XBAR_OUT_SD4FLT3_COMPL", displayName: "SD4FLT3 COMPL" },
	{ name: "XBAR_OUT_SD4FLT4_COMPH", displayName: "SD4FLT4 COMPH" },
	{ name: "XBAR_OUT_SD4FLT4_COMPL", displayName: "SD4FLT4 COMPL" },
	{ name: "XBAR_OUT_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_OUT_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_OUT_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_OUT_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_OUT_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_OUT_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_OUT_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_OUT_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_OUT_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_OUT_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_OUT_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_OUT_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_OUT_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_OUT_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_OUT_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_OUT_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_OUT_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_OUT_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_OUT_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_OUT_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_OUT_CPU1_ADCCHECK_EVT1", displayName: "CPU1 ADCCHECKEVT1" },
	{ name: "XBAR_OUT_CPU1_ADCCHECK_EVT2", displayName: "CPU1 ADCCHECKEVT2" },
	{ name: "XBAR_OUT_CPU1_ADCCHECK_EVT3", displayName: "CPU1 ADCCHECKEVT3" },
	{ name: "XBAR_OUT_CPU1_ADCCHECK_EVT4", displayName: "CPU1 ADCCHECKEVT4" },
	{ name: "XBAR_OUT_CPU2_ADCCHECK_EVT1", displayName: "CPU2 ADCCHECKEVT1" },
	{ name: "XBAR_OUT_CPU2_ADCCHECK_EVT2", displayName: "CPU2 ADCCHECKEVT2" },
	{ name: "XBAR_OUT_CPU2_ADCCHECK_EVT3", displayName: "CPU2 ADCCHECKEVT3" },
	{ name: "XBAR_OUT_CPU2_ADCCHECK_EVT4", displayName: "CPU2 ADCCHECKEVT4" },
	{ name: "XBAR_OUT_CPU3_ADCCHECK_EVT1", displayName: "CPU3 ADCCHECKEVT1" },
	{ name: "XBAR_OUT_CPU3_ADCCHECK_EVT2", displayName: "CPU3 ADCCHECKEVT2" },
	{ name: "XBAR_OUT_CPU3_ADCCHECK_EVT3", displayName: "CPU3 ADCCHECKEVT3" },
	{ name: "XBAR_OUT_CPU3_ADCCHECK_EVT4", displayName: "CPU3 ADCCHECKEVT4" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_OUT_INPUTXBAR_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_OUT_EQEP1_INDEX_SYNCOUT", displayName: "OUT EQEP1 INDEX SYNCOUT" },
	{ name: "XBAR_OUT_EQEP1_STROBE_SYNCOUT", displayName: "OUT EQEP1 STROBE SYNCOUT" },
	{ name: "XBAR_OUT_EQEP2_INDEX_SYNCOUT", displayName: "OUT EQEP2 INDEX SYNCOUT" },
	{ name: "XBAR_OUT_EQEP2_STROBE_SYNCOUT", displayName: "OUT EQEP2 STROBE SYNCOUT" },
	{ name: "XBAR_OUT_EQEP3_INDEX_SYNCOUT", displayName: "OUT EQEP3 INDEX SYNCOUT" },
	{ name: "XBAR_OUT_EQEP3_STROBE_SYNCOUT", displayName: "OUT EQEP3 STROBE SYNCOUT" },
	{ name: "XBAR_OUT_EQEP4_INDEX_SYNCOUT", displayName: "OUT EQEP4 INDEX SYNCOUT" },
	{ name: "XBAR_OUT_EQEP4_STROBE_SYNCOUT", displayName: "OUT EQEP4 STROBE SYNCOUT" },
	{ name: "XBAR_OUT_EQEP5_INDEX_SYNCOUT", displayName: "OUT EQEP5 INDEX SYNCOUT" },
	{ name: "XBAR_OUT_EQEP5_STROBE_SYNCOUT", displayName: "OUT EQEP5 STROBE SYNCOUT" },
	{ name: "XBAR_OUT_EQEP6_INDEX_SYNCOUT", displayName: "OUT EQEP6 INDEX SYNCOUT" },
	{ name: "XBAR_OUT_EQEP6_STROBE_SYNCOUT", displayName: "OUT EQEP6 STROBE SYNCOUT" },
	{ name: "XBAR_OUT_FSIA_RX_TRIG1", displayName: "FSIA RX TRIG1" },
	{ name: "XBAR_OUT_FSIB_RX_TRIG1", displayName: "FSIB RX TRIG1" },
	{ name: "XBAR_OUT_FSIC_RX_TRIG1", displayName: "FSIC RX TRIG1" },
	{ name: "XBAR_OUT_FSID_RX_TRIG1", displayName: "FSID RX TRIG1" },
	{ name: "XBAR_OUT_FSIA_RX_TRIG2", displayName: "FSIA RX TRIG2" },
	{ name: "XBAR_OUT_FSIB_RX_TRIG2", displayName: "FSIB RX TRIG2" },
	{ name: "XBAR_OUT_FSIC_RX_TRIG2", displayName: "FSIC RX TRIG2" },
	{ name: "XBAR_OUT_FSID_RX_TRIG2", displayName: "FSID RX TRIG2" },
	{ name: "XBAR_OUT_FSIA_RX_TRIG3", displayName: "FSIA RX TRIG3" },
	{ name: "XBAR_OUT_FSIB_RX_TRIG3", displayName: "FSIB RX TRIG3" },
	{ name: "XBAR_OUT_FSIC_RX_TRIG3", displayName: "FSIC RX TRIG3" },
	{ name: "XBAR_OUT_FSID_RX_TRIG3", displayName: "FSID RX TRIG3" },
	{ name: "XBAR_OUT_XCLKOUT", displayName: "XCLKOUT" },
	{ name: "XBAR_OUT_ECATSYNC0", displayName: "ECAT SYNC0" },
	{ name: "XBAR_OUT_ECATSYNC1", displayName: "ECAT SYNC1" },
	{ name: "XBAR_OUT_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_OUT_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_OUT_ECAP3_OUT", displayName: "ECAP3 OUT" },
	{ name: "XBAR_OUT_ECAP4_OUT", displayName: "ECAP4 OUT" },
	{ name: "XBAR_OUT_ECAP5_OUT", displayName: "ECAP5 OUT" },
	{ name: "XBAR_OUT_ECAP6_OUT", displayName: "ECAP6 OUT" },
	{ name: "XBAR_OUT_ECAP1_TRIPOUT", displayName: "ECAP1 TRIPOUT" },
	{ name: "XBAR_OUT_ECAP2_TRIPOUT", displayName: "ECAP2 TRIPOUT" },
	{ name: "XBAR_OUT_ECAP3_TRIPOUT", displayName: "ECAP3 TRIPOUT" },
	{ name: "XBAR_OUT_ECAP4_TRIPOUT", displayName: "ECAP4 TRIPOUT" },
	{ name: "XBAR_OUT_ECAP5_TRIPOUT", displayName: "ECAP5 TRIPOUT" },
	{ name: "XBAR_OUT_ECAP6_TRIPOUT", displayName: "ECAP6 TRIPOUT" },
	{ name: "XBAR_OUT_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_OUT_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_OUT_ESM_GEN_EVENT", displayName: "ESM GEN EVENT" },
	{ name: "XBAR_OUT_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_OUT_EPG1_OUT0", displayName: "EPG1OUT0" },
	{ name: "XBAR_OUT_EPG1_OUT1", displayName: "EPG1 OUT1" },
	{ name: "XBAR_OUT_EPG1_OUT2", displayName: "EPG1 OUT2" },
	{ name: "XBAR_OUT_EPG1_OUT3", displayName: "EPG1 OUT3" },
	{ name: "XBAR_OUT_WADI1OUT0", displayName: "WADI1OUT0" },
	{ name: "XBAR_OUT_WADI1OUT1", displayName: "WADI1OUT1" },
	{ name: "XBAR_OUT_WADI1OUT2", displayName: "WADI1OUT2" },
	{ name: "XBAR_OUT_WADI1OUT3", displayName: "WADI1OUT3" },
	{ name: "XBAR_OUT_WADI1OUT4", displayName: "WADI1OUT4" },
	{ name: "XBAR_OUT_WADI1OUT5", displayName: "WADI1OUT5" },
	{ name: "XBAR_OUT_WADI1OUT6", displayName: "WADI1OUT6" },
	{ name: "XBAR_OUT_WADI1OUT7", displayName: "WADI1OUT7" },
	{ name: "XBAR_OUT_MCANA_FEVT0", displayName: "MCANA FEVT0" },
	{ name: "XBAR_OUT_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_OUT_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_OUT_MCANB_FEVT0", displayName: "MCANB FEVT0" },
	{ name: "XBAR_OUT_MCANB_FEVT1", displayName: "MCANB FEVT1" },
	{ name: "XBAR_OUT_MCANB_FEVT2", displayName: "MCANB FEVT2" },
	{ name: "XBAR_OUT_MCANC_FEVT0", displayName: "MCANC FEVT0" },
	{ name: "XBAR_OUT_MCANC_FEVT1", displayName: "MCANC FEVT1" },
	{ name: "XBAR_OUT_MCANC_FEVT2", displayName: "MCANC FEVT2" },
	{ name: "XBAR_OUT_MCAND_FEVT0", displayName: "MCAND FEVT0" },
	{ name: "XBAR_OUT_MCAND_FEVT1", displayName: "MCAND FEVT1" },
	{ name: "XBAR_OUT_MCAND_FEVT2", displayName: "MCAND FEVT2" },
	{ name: "XBAR_OUT_MCANE_FEVT0", displayName: "MCANE FEVT0" },
	{ name: "XBAR_OUT_MCANE_FEVT1", displayName: "MCANE FEVT1" },
	{ name: "XBAR_OUT_MCANE_FEVT2", displayName: "MCANE FEVT2" },
	{ name: "XBAR_OUT_MCANF_FEVT0", displayName: "MCANF FEVT0" },
	{ name: "XBAR_OUT_MCANF_FEVT1", displayName: "MCANF FEVT1" },
	{ name: "XBAR_OUT_MCANF_FEVT2", displayName: "MCANF FEVT2" },
	{ name: "XBAR_OUT_WADI2OUT0", displayName: "WADI2OUT0" },
	{ name: "XBAR_OUT_WADI2OUT1", displayName: "WADI2OUT1" },
	{ name: "XBAR_OUT_WADI2OUT2", displayName: "WADI2OUT2" },
	{ name: "XBAR_OUT_WADI2OUT3", displayName: "WADI2OUT3" },
	{ name: "XBAR_OUT_WADI2OUT4", displayName: "WADI2OUT4" },
	{ name: "XBAR_OUT_WADI2OUT5", displayName: "WADI2OUT5" },
	{ name: "XBAR_OUT_WADI2OUT6", displayName: "WADI2OUT6" },
	{ name: "XBAR_OUT_WADI2OUT7", displayName: "WADI2OUT7" },
	{ name: "XBAR_OUT_CLB1_OUT0", displayName: "CLB1 OUT0" },
	{ name: "XBAR_OUT_CLB1_OUT1", displayName: "CLB1 OUT1" },
	{ name: "XBAR_OUT_CLB1_OUT2", displayName: "CLB1 OUT2" },
	{ name: "XBAR_OUT_CLB1_OUT3", displayName: "CLB1 OUT3" },
	{ name: "XBAR_OUT_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_OUT_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_OUT_CLB1_OUT6", displayName: "CLB1 OUT6" },
	{ name: "XBAR_OUT_CLB1_OUT7", displayName: "CLB1 OUT7" },
	{ name: "XBAR_OUT_CLB2_OUT0", displayName: "CLB2 OUT0" },
	{ name: "XBAR_OUT_CLB2_OUT1", displayName: "CLB2 OUT1" },
	{ name: "XBAR_OUT_CLB2_OUT2", displayName: "CLB2 OUT2" },
	{ name: "XBAR_OUT_CLB2_OUT3", displayName: "CLB2 OUT3" },
	{ name: "XBAR_OUT_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_OUT_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_OUT_CLB2_OUT6", displayName: "CLB2 OUT6" },
	{ name: "XBAR_OUT_CLB2_OUT7", displayName: "CLB2 OUT7" },
	{ name: "XBAR_OUT_CLB3_OUT0", displayName: "CLB3 OUT0" },
	{ name: "XBAR_OUT_CLB3_OUT1", displayName: "CLB3 OUT1" },
	{ name: "XBAR_OUT_CLB3_OUT2", displayName: "CLB3 OUT2" },
	{ name: "XBAR_OUT_CLB3_OUT3", displayName: "CLB3 OUT3" },
	{ name: "XBAR_OUT_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_OUT_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_OUT_CLB3_OUT6", displayName: "CLB3 OUT6" },
	{ name: "XBAR_OUT_CLB3_OUT7", displayName: "CLB3 OUT7" },
	{ name: "XBAR_OUT_CLB4_OUT0", displayName: "CLB4 OUT0" },
	{ name: "XBAR_OUT_CLB4_OUT1", displayName: "CLB4 OUT1" },
	{ name: "XBAR_OUT_CLB4_OUT2", displayName: "CLB4 OUT2" },
	{ name: "XBAR_OUT_CLB4_OUT3", displayName: "CLB4 OUT3" },
	{ name: "XBAR_OUT_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_OUT_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_OUT_CLB4_OUT6", displayName: "CLB4 OUT6" },
	{ name: "XBAR_OUT_CLB4_OUT7", displayName: "CLB4 OUT7" },
	{ name: "XBAR_OUT_CLB5_OUT0", displayName: "CLB5 OUT0" },
	{ name: "XBAR_OUT_CLB5_OUT1", displayName: "CLB5 OUT1" },
	{ name: "XBAR_OUT_CLB5_OUT2", displayName: "CLB5 OUT2" },
	{ name: "XBAR_OUT_CLB5_OUT3", displayName: "CLB5 OUT3" },
	{ name: "XBAR_OUT_CLB5_OUT4", displayName: "CLB5 OUT4" },
	{ name: "XBAR_OUT_CLB5_OUT5", displayName: "CLB5 OUT5" },
	{ name: "XBAR_OUT_CLB5_OUT6", displayName: "CLB5 OUT6" },
	{ name: "XBAR_OUT_CLB5_OUT7", displayName: "CLB5 OUT7" },
	{ name: "XBAR_OUT_CLB6_OUT0", displayName: "CLB6 OUT0" },
	{ name: "XBAR_OUT_CLB6_OUT1", displayName: "CLB6 OUT1" },
	{ name: "XBAR_OUT_CLB6_OUT2", displayName: "CLB6 OUT2" },
	{ name: "XBAR_OUT_CLB6_OUT3", displayName: "CLB6 OUT3" },
	{ name: "XBAR_OUT_CLB6_OUT4", displayName: "CLB6 OUT4" },
	{ name: "XBAR_OUT_CLB6_OUT5", displayName: "CLB6 OUT5" },
	{ name: "XBAR_OUT_CLB6_OUT6", displayName: "CLB6 OUT6" },
	{ name: "XBAR_OUT_CLB6_OUT7", displayName: "CLB6 OUT7" },
	{ name: "XBAR_OUT_CLBXBAR1", displayName: "CLBXBAR1" },
	{ name: "XBAR_OUT_CLBXBAR2", displayName: "CLBXBAR2" },
	{ name: "XBAR_OUT_CLBXBAR3", displayName: "CLBXBAR3" },
	{ name: "XBAR_OUT_CLBXBAR4", displayName: "CLBXBAR4" },
	{ name: "XBAR_OUT_CLBXBAR5", displayName: "CLBXBAR5" },
	{ name: "XBAR_OUT_CLBXBAR6", displayName: "CLBXBAR6" },
	{ name: "XBAR_OUT_CLBXBAR7", displayName: "CLBXBAR7" },
	{ name: "XBAR_OUT_CLBXBAR8", displayName: "CLBXBAR8" },
	{ name: "XBAR_OUT_ADCA_EXTMUXSEL0", displayName: "ADCA EXTMUXSEL0" },
	{ name: "XBAR_OUT_ADCA_EXTMUXSEL1", displayName: "ADCA EXTMUXSEL1" },
	{ name: "XBAR_OUT_ADCA_EXTMUXSEL2", displayName: "ADCA EXTMUXSEL2" },
	{ name: "XBAR_OUT_ADCA_EXTMUXSEL3", displayName: "ADCA EXTMUXSEL3" },
	{ name: "XBAR_OUT_ADCB_EXTMUXSEL0", displayName: "ADCB EXTMUXSEL0" },
	{ name: "XBAR_OUT_ADCB_EXTMUXSEL1", displayName: "ADCB EXTMUXSEL1" },
	{ name: "XBAR_OUT_ADCB_EXTMUXSEL2", displayName: "ADCB EXTMUXSEL2" },
	{ name: "XBAR_OUT_ADCB_EXTMUXSEL3", displayName: "ADCB EXTMUXSEL3" },
	{ name: "XBAR_OUT_ADCC_EXTMUXSEL0", displayName: "ADCC EXTMUXSEL0" },
	{ name: "XBAR_OUT_ADCC_EXTMUXSEL1", displayName: "ADCC EXTMUXSEL1" },
	{ name: "XBAR_OUT_ADCC_EXTMUXSEL2", displayName: "ADCC EXTMUXSEL2" },
	{ name: "XBAR_OUT_ADCC_EXTMUXSEL3", displayName: "ADCC EXTMUXSEL3" },
	{ name: "XBAR_OUT_ADCD_EXTMUXSEL0", displayName: "ADCD EXTMUXSEL0" },
	{ name: "XBAR_OUT_ADCD_EXTMUXSEL1", displayName: "ADCD EXTMUXSEL1" },
	{ name: "XBAR_OUT_ADCD_EXTMUXSEL2", displayName: "ADCD EXTMUXSEL2" },
	{ name: "XBAR_OUT_ADCD_EXTMUXSEL3", displayName: "ADCD EXTMUXSEL3" },
	{ name: "XBAR_OUT_ADCE_EXTMUXSEL0", displayName: "ADCE EXTMUXSEL0" },
	{ name: "XBAR_OUT_ADCE_EXTMUXSEL1", displayName: "ADCE EXTMUXSEL1" },
	{ name: "XBAR_OUT_ADCE_EXTMUXSEL2", displayName: "ADCE EXTMUXSEL2" },
	{ name: "XBAR_OUT_ADCE_EXTMUXSEL3", displayName: "ADCE EXTMUXSEL3" },
]
let XBAR_EpwmXbarInputSource = [
	{ name: "XBAR_EPWM_CMPSS1_CTRIPH", displayName: "CMPSS1 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS1_CTRIPL", displayName: "CMPSS1 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS2_CTRIPH", displayName: "CMPSS2 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS2_CTRIPL", displayName: "CMPSS2 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS3_CTRIPH", displayName: "CMPSS3 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS3_CTRIPL", displayName: "CMPSS3 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS4_CTRIPH", displayName: "CMPSS4 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS4_CTRIPL", displayName: "CMPSS4 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS5_CTRIPH", displayName: "CMPSS5 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS5_CTRIPL", displayName: "CMPSS5 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS6_CTRIPH", displayName: "CMPSS6 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS6_CTRIPL", displayName: "CMPSS6 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS7_CTRIPH", displayName: "CMPSS7 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS7_CTRIPL", displayName: "CMPSS7 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS8_CTRIPH", displayName: "CMPSS8 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS8_CTRIPL", displayName: "CMPSS8 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS9_CTRIPH", displayName: "CMPSS9 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS9_CTRIPL", displayName: "CMPSS9 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS10_CTRIPH", displayName: "CMPSS10 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS10_CTRIPL", displayName: "CMPSS10 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS11_CTRIPH", displayName: "CMPSS11 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS11_CTRIPL", displayName: "CMPSS11 CTRIPL" },
	{ name: "XBAR_EPWM_CMPSS12_CTRIPH", displayName: "CMPSS12 CTRIPH" },
	{ name: "XBAR_EPWM_CMPSS12_CTRIPL", displayName: "CMPSS12 CTRIPL" },
	{ name: "XBAR_EPWM_SD1FLT1_COMPH", displayName: "SD1FLT1 COMPH" },
	{ name: "XBAR_EPWM_SD1FLT1_COMPL", displayName: "SD1FLT1 COMPL" },
	{ name: "XBAR_EPWM_SD1FLT2_COMPH", displayName: "SD1FLT2 COMPH" },
	{ name: "XBAR_EPWM_SD1FLT2_COMPL", displayName: "SD1FLT2 COMPL" },
	{ name: "XBAR_EPWM_SD1FLT3_COMPH", displayName: "SD1FLT3 COMPH" },
	{ name: "XBAR_EPWM_SD1FLT3_COMPL", displayName: "SD1FLT3 COMPL" },
	{ name: "XBAR_EPWM_SD1FLT4_COMPH", displayName: "SD1FLT4 COMPH" },
	{ name: "XBAR_EPWM_SD1FLT4_COMPL", displayName: "SD1FLT4 COMPL" },
	{ name: "XBAR_EPWM_SD2FLT1_COMPH", displayName: "SD2FLT1 COMPH" },
	{ name: "XBAR_EPWM_SD2FLT1_COMPL", displayName: "SD2FLT1 COMPL" },
	{ name: "XBAR_EPWM_SD2FLT2_COMPH", displayName: "SD2FLT2 COMPH" },
	{ name: "XBAR_EPWM_SD2FLT2_COMPL", displayName: "SD2FLT2 COMPL" },
	{ name: "XBAR_EPWM_SD2FLT3_COMPH", displayName: "SD2FLT3 COMPH" },
	{ name: "XBAR_EPWM_SD2FLT3_COMPL", displayName: "SD2FLT3 COMPL" },
	{ name: "XBAR_EPWM_SD2FLT4_COMPH", displayName: "SD2FLT4 COMPH" },
	{ name: "XBAR_EPWM_SD2FLT4_COMPL", displayName: "SD2FLT4 COMPL" },
	{ name: "XBAR_EPWM_SD3FLT1_COMPH", displayName: "SD3FLT1 COMPH" },
	{ name: "XBAR_EPWM_SD3FLT1_COMPL", displayName: "SD3FLT1 COMPL" },
	{ name: "XBAR_EPWM_SD3FLT2_COMPH", displayName: "SD3FLT2 COMPH" },
	{ name: "XBAR_EPWM_SD3FLT2_COMPL", displayName: "SD3FLT2 COMPL" },
	{ name: "XBAR_EPWM_SD3FLT3_COMPH", displayName: "SD3FLT3 COMPH" },
	{ name: "XBAR_EPWM_SD3FLT3_COMPL", displayName: "SD3FLT3 COMPL" },
	{ name: "XBAR_EPWM_SD3FLT4_COMPH", displayName: "SD3FLT4 COMPH" },
	{ name: "XBAR_EPWM_SD3FLT4_COMPL", displayName: "SD3FLT4 COMPL" },
	{ name: "XBAR_EPWM_SD4FLT1_COMPH", displayName: "SD4FLT1 COMPH" },
	{ name: "XBAR_EPWM_SD4FLT1_COMPL", displayName: "SD4FLT1 COMPL" },
	{ name: "XBAR_EPWM_SD4FLT2_COMPH", displayName: "SD4FLT2 COMPH" },
	{ name: "XBAR_EPWM_SD4FLT2_COMPL", displayName: "SD4FLT2 COMPL" },
	{ name: "XBAR_EPWM_SD4FLT3_COMPH", displayName: "SD4FLT3 COMPH" },
	{ name: "XBAR_EPWM_SD4FLT3_COMPL", displayName: "SD4FLT3 COMPL" },
	{ name: "XBAR_EPWM_SD4FLT4_COMPH", displayName: "SD4FLT4 COMPH" },
	{ name: "XBAR_EPWM_SD4FLT4_COMPL", displayName: "SD4FLT4 COMPL" },
	{ name: "XBAR_EPWM_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_EPWM_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_EPWM_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_EPWM_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_EPWM_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_EPWM_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_EPWM_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_EPWM_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_EPWM_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_EPWM_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_EPWM_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_EPWM_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_EPWM_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_EPWM_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_EPWM_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_EPWM_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_EPWM_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_EPWM_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_EPWM_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_EPWM_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_EPWM_CPU1_ADCCHECK_EVT1", displayName: "CPU1 ADCCHECKEVT1" },
	{ name: "XBAR_EPWM_CPU1_ADCCHECK_EVT2", displayName: "CPU1 ADCCHECKEVT2" },
	{ name: "XBAR_EPWM_CPU1_ADCCHECK_EVT3", displayName: "CPU1 ADCCHECKEVT3" },
	{ name: "XBAR_EPWM_CPU1_ADCCHECK_EVT4", displayName: "CPU1 ADCCHECKEVT4" },
	{ name: "XBAR_EPWM_CPU2_ADCCHECK_EVT1", displayName: "CPU2 ADCCHECKEVT1" },
	{ name: "XBAR_EPWM_CPU2_ADCCHECK_EVT2", displayName: "CPU2 ADCCHECKEVT2" },
	{ name: "XBAR_EPWM_CPU2_ADCCHECK_EVT3", displayName: "CPU2 ADCCHECKEVT3" },
	{ name: "XBAR_EPWM_CPU2_ADCCHECK_EVT4", displayName: "CPU2 ADCCHECKEVT4" },
	{ name: "XBAR_EPWM_CPU3_ADCCHECK_EVT1", displayName: "CPU3 ADCCHECKEVT1" },
	{ name: "XBAR_EPWM_CPU3_ADCCHECK_EVT2", displayName: "CPU3 ADCCHECKEVT2" },
	{ name: "XBAR_EPWM_CPU3_ADCCHECK_EVT3", displayName: "CPU3 ADCCHECKEVT3" },
	{ name: "XBAR_EPWM_CPU3_ADCCHECK_EVT4", displayName: "CPU3 ADCCHECKEVT4" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT9", displayName: "INPUTXBAR INPUT9" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT10", displayName: "INPUTXBAR INPUT10" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT11", displayName: "INPUTXBAR INPUT11" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT12", displayName: "INPUTXBAR INPUT12" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT13", displayName: "INPUTXBAR INPUT13" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT14", displayName: "INPUTXBAR INPUT14" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT15", displayName: "INPUTXBAR INPUT15" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT16", displayName: "INPUTXBAR INPUT16" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT17", displayName: "INPUTXBAR INPUT17" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT18", displayName: "INPUTXBAR INPUT18" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT19", displayName: "INPUTXBAR INPUT19" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT20", displayName: "INPUTXBAR INPUT20" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT21", displayName: "INPUTXBAR INPUT21" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT22", displayName: "INPUTXBAR INPUT22" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT23", displayName: "INPUTXBAR INPUT23" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT24", displayName: "INPUTXBAR INPUT24" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT25", displayName: "INPUTXBAR INPUT25" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT26", displayName: "INPUTXBAR INPUT26" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT27", displayName: "INPUTXBAR INPUT27" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT28", displayName: "INPUTXBAR INPUT28" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT29", displayName: "INPUTXBAR INPUT29" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT30", displayName: "INPUTXBAR INPUT30" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT31", displayName: "INPUTXBAR INPUT31" },
	{ name: "XBAR_EPWM_INPUTXBAR_INPUT32", displayName: "INPUTXBAR INPUT32" },
	{ name: "XBAR_EPWM_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_EPWM_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_EPWM_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_EPWM_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_EPWM_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_EPWM_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_EPWM_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_EPWM_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_EPWM_CLB5_OUT4", displayName: "CLB5 OUT4" },
	{ name: "XBAR_EPWM_CLB5_OUT5", displayName: "CLB5 OUT5" },
	{ name: "XBAR_EPWM_CLB6_OUT4", displayName: "CLB6 OUT4" },
	{ name: "XBAR_EPWM_CLB6_OUT5", displayName: "CLB6 OUT5" },
	{ name: "XBAR_EPWM_FSIA_RX_TRIG1", displayName: "FSIA RX TRIG1" },
	{ name: "XBAR_EPWM_FSIB_RX_TRIG1", displayName: "FSIB RX TRIG1" },
	{ name: "XBAR_EPWM_FSIC_RX_TRIG1", displayName: "FSIC RX TRIG1" },
	{ name: "XBAR_EPWM_FSID_RX_TRIG1", displayName: "FSID RX TRIG1" },
	{ name: "XBAR_EPWM_ECAT_SYNC0", displayName: "ECAT SYNC0" },
	{ name: "XBAR_EPWM_ECAT_SYNC1", displayName: "ECAT SYNC1" },
	{ name: "XBAR_EPWM_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_EPWM_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_EPWM_ECAP3_OUT", displayName: "ECAP3 OUT" },
	{ name: "XBAR_EPWM_ECAP4_OUT", displayName: "ECAP4 OUT" },
	{ name: "XBAR_EPWM_ECAP5_OUT", displayName: "ECAP5 OUT" },
	{ name: "XBAR_EPWM_ECAP6_OUT", displayName: "ECAP6 OUT" },
	{ name: "XBAR_EPWM_ECAP1_TRIPOUT", displayName: "ECAP1 TRIPOUT" },
	{ name: "XBAR_EPWM_ECAP2_TRIPOUT", displayName: "ECAP2 TRIPOUT" },
	{ name: "XBAR_EPWM_ECAP3_TRIPOUT", displayName: "ECAP3 TRIPOUT" },
	{ name: "XBAR_EPWM_ECAP4_TRIPOUT", displayName: "ECAP4 TRIPOUT" },
	{ name: "XBAR_EPWM_ECAP5_TRIPOUT", displayName: "ECAP5 TRIPOUT" },
	{ name: "XBAR_EPWM_ECAP6_TRIPOUT", displayName: "ECAP6 TRIPOUT" },
	{ name: "XBAR_EPWM_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_EPWM_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_EPWM_ESM_GEN_EVENT", displayName: "ESM GEN EVENT" },
	{ name: "XBAR_EPWM_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_0", displayName: "WADI1 ERROR BUS O 0" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_1", displayName: "WADI1 ERROR BUS O 1" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_2", displayName: "WADI1 ERROR BUS O 2" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_3", displayName: "WADI1 ERROR BUS O 3" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_4", displayName: "WADI1 ERROR BUS O 4" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_5", displayName: "WADI1 ERROR BUS O 5" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_6", displayName: "WADI1 ERROR BUS O 6" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_7", displayName: "WADI1 ERROR BUS O 7" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_8", displayName: "WADI1 ERROR BUS O 8" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_9", displayName: "WADI1 ERROR BUS O 9" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_10", displayName: "WADI1 ERROR BUS O 10" },
	{ name: "XBAR_EPWM_WADI1_ERROR_BUS_O_11", displayName: "WADI1 ERROR BUS O 11" },
	{ name: "XBAR_EPWM_MCANA_FEVT0", displayName: "MCANA FEVT0" },
	{ name: "XBAR_EPWM_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_EPWM_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_EPWM_MCANB_FEVT0", displayName: "MCANB FEVT0" },
	{ name: "XBAR_EPWM_MCANB_FEVT1", displayName: "MCANB FEVT1" },
	{ name: "XBAR_EPWM_MCANB_FEVT2", displayName: "MCANB FEVT2" },
	{ name: "XBAR_EPWM_MCANC_FEVT0", displayName: "MCANC FEVT0" },
	{ name: "XBAR_EPWM_MCANC_FEVT1", displayName: "MCANC FEVT1" },
	{ name: "XBAR_EPWM_MCANC_FEVT2", displayName: "MCANC FEVT2" },
	{ name: "XBAR_EPWM_MCAND_FEVT0", displayName: "MCAND FEVT0" },
	{ name: "XBAR_EPWM_MCAND_FEVT1", displayName: "MCAND FEVT1" },
	{ name: "XBAR_EPWM_MCAND_FEVT2", displayName: "MCAND FEVT2" },
	{ name: "XBAR_EPWM_MCANE_FEVT0", displayName: "MCANE FEVT0" },
	{ name: "XBAR_EPWM_MCANE_FEVT1", displayName: "MCANE FEVT1" },
	{ name: "XBAR_EPWM_MCANE_FEVT2", displayName: "MCANE FEVT2" },
	{ name: "XBAR_EPWM_MCANF_FEVT0", displayName: "MCANF FEVT0" },
	{ name: "XBAR_EPWM_MCANF_FEVT1", displayName: "MCANF FEVT1" },
	{ name: "XBAR_EPWM_MCANF_FEVT2", displayName: "MCANF FEVT2" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_0", displayName: "WADI2 ERROR BUS O 0" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_1", displayName: "WADI2 ERROR BUS O 1" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_2", displayName: "WADI2 ERROR BUS O 2" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_3", displayName: "WADI2 ERROR BUS O 3" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_4", displayName: "WADI2 ERROR BUS O 4" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_5", displayName: "WADI2 ERROR BUS O 5" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_6", displayName: "WADI2 ERROR BUS O 6" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_7", displayName: "WADI2 ERROR BUS O 7" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_8", displayName: "WADI2 ERROR BUS O 8" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_9", displayName: "WADI2 ERROR BUS O 9" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_10", displayName: "WADI2 ERROR BUS O 10" },
	{ name: "XBAR_EPWM_WADI2_ERROR_BUS_O_11", displayName: "WADI2 ERROR BUS O 11" },
	{ name: "XBAR_EPWM_EPWM1_TRIPOUT", displayName: "EPWM1 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM2_TRIPOUT", displayName: "EPWM2 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM3_TRIPOUT", displayName: "EPWM3 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM4_TRIPOUT", displayName: "EPWM4 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM5_TRIPOUT", displayName: "EPWM5 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM6_TRIPOUT", displayName: "EPWM6 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM7_TRIPOUT", displayName: "EPWM7 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM8_TRIPOUT", displayName: "EPWM8 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM9_TRIPOUT", displayName: "EPWM9 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM10_TRIPOUT", displayName: "EPWM10 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM11_TRIPOUT", displayName: "EPWM11 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM12_TRIPOUT", displayName: "EPWM12 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM13_TRIPOUT", displayName: "EPWM13 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM14_TRIPOUT", displayName: "EPWM14 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM15_TRIPOUT", displayName: "EPWM15 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM16_TRIPOUT", displayName: "EPWM16 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM17_TRIPOUT", displayName: "EPWM17 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM18_TRIPOUT", displayName: "EPWM18 TRIPOUT" },
	{ name: "XBAR_EPWM_EPWM1_DE_DEMONTRIP", displayName: "EPWM1 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM2_DE_DEMONTRIP", displayName: "EPWM2 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM3_DE_DEMONTRIP", displayName: "EPWM3 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM4_DE_DEMONTRIP", displayName: "EPWM4 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM5_DE_DEMONTRIP", displayName: "EPWM5 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM6_DE_DEMONTRIP", displayName: "EPWM6 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM7_DE_DEMONTRIP", displayName: "EPWM7 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM8_DE_DEMONTRIP", displayName: "EPWM8 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM9_DE_DEMONTRIP", displayName: "EPWM9 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM10_DE_DEMONTRIP", displayName: "EPWM10 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM11_DE_DEMONTRIP", displayName: "EPWM11 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM12_DE_DEMONTRIP", displayName: "EPWM12 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM13_DE_DEMONTRIP", displayName: "EPWM13 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM14_DE_DEMONTRIP", displayName: "EPWM14 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM15_DE_DEMONTRIP", displayName: "EPWM15 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM16_DE_DEMONTRIP", displayName: "EPWM16 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM17_DE_DEMONTRIP", displayName: "EPWM17 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM18_DE_DEMONTRIP", displayName: "EPWM18 DE DEMONTRIP" },
	{ name: "XBAR_EPWM_EPWM1_DE_ACTIVE", displayName: "EPWM1 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM2_DE_ACTIVE", displayName: "EPWM2 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM3_DE_ACTIVE", displayName: "EPWM3 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM4_DE_ACTIVE", displayName: "EPWM4 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM5_DE_ACTIVE", displayName: "EPWM5 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM6_DE_ACTIVE", displayName: "EPWM6 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM7_DE_ACTIVE", displayName: "EPWM7 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM8_DE_ACTIVE", displayName: "EPWM8 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM9_DE_ACTIVE", displayName: "EPWM9 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM10_DE_ACTIVE", displayName: "EPWM10 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM11_DE_ACTIVE", displayName: "EPWM11 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM12_DE_ACTIVE", displayName: "EPWM12 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM13_DE_ACTIVE", displayName: "EPWM13 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM14_DE_ACTIVE", displayName: "EPWM14 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM15_DE_ACTIVE", displayName: "EPWM15 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM16_DE_ACTIVE", displayName: "EPWM16 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM17_DE_ACTIVE", displayName: "EPWM17 DE ACTIVE" },
	{ name: "XBAR_EPWM_EPWM18_DE_ACTIVE", displayName: "EPWM18 DE ACTIVE" },
]
let XBAR_ClbXbarInputSource = [
	{ name: "XBAR_CLB_CMPSS1_CTRIPH", displayName: "CMPSS1 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS1_CTRIPL", displayName: "CMPSS1 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS2_CTRIPH", displayName: "CMPSS2 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS2_CTRIPL", displayName: "CMPSS2 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS3_CTRIPH", displayName: "CMPSS3 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS3_CTRIPL", displayName: "CMPSS3 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS4_CTRIPH", displayName: "CMPSS4 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS4_CTRIPL", displayName: "CMPSS4 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS5_CTRIPH", displayName: "CMPSS5 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS5_CTRIPL", displayName: "CMPSS5 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS6_CTRIPH", displayName: "CMPSS6 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS6_CTRIPL", displayName: "CMPSS6 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS7_CTRIPH", displayName: "CMPSS7 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS7_CTRIPL", displayName: "CMPSS7 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS8_CTRIPH", displayName: "CMPSS8 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS8_CTRIPL", displayName: "CMPSS8 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS9_CTRIPH", displayName: "CMPSS9 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS9_CTRIPL", displayName: "CMPSS9 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS10_CTRIPH", displayName: "CMPSS10 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS10_CTRIPL", displayName: "CMPSS10 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS11_CTRIPH", displayName: "CMPSS11 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS11_CTRIPL", displayName: "CMPSS11 CTRIPL" },
	{ name: "XBAR_CLB_CMPSS12_CTRIPH", displayName: "CMPSS12 CTRIPH" },
	{ name: "XBAR_CLB_CMPSS12_CTRIPL", displayName: "CMPSS12 CTRIPL" },
	{ name: "XBAR_CLB_SD1FLT1_COMPH", displayName: "SD1FLT1 COMPH" },
	{ name: "XBAR_CLB_SD1FLT1_COMPL", displayName: "SD1FLT1 COMPL" },
	{ name: "XBAR_CLB_SD1FLT2_COMPH", displayName: "SD1FLT2 COMPH" },
	{ name: "XBAR_CLB_SD1FLT2_COMPL", displayName: "SD1FLT2 COMPL" },
	{ name: "XBAR_CLB_SD1FLT3_COMPH", displayName: "SD1FLT3 COMPH" },
	{ name: "XBAR_CLB_SD1FLT3_COMPL", displayName: "SD1FLT3 COMPL" },
	{ name: "XBAR_CLB_SD1FLT4_COMPH", displayName: "SD1FLT4 COMPH" },
	{ name: "XBAR_CLB_SD1FLT4_COMPL", displayName: "SD1FLT4 COMPL" },
	{ name: "XBAR_CLB_SD2FLT1_COMPH", displayName: "SD2FLT1 COMPH" },
	{ name: "XBAR_CLB_SD2FLT1_COMPL", displayName: "SD2FLT1 COMPL" },
	{ name: "XBAR_CLB_SD2FLT2_COMPH", displayName: "SD2FLT2 COMPH" },
	{ name: "XBAR_CLB_SD2FLT2_COMPL", displayName: "SD2FLT2 COMPL" },
	{ name: "XBAR_CLB_SD2FLT3_COMPH", displayName: "SD2FLT3 COMPH" },
	{ name: "XBAR_CLB_SD2FLT3_COMPL", displayName: "SD2FLT3 COMPL" },
	{ name: "XBAR_CLB_SD2FLT4_COMPH", displayName: "SD2FLT4 COMPH" },
	{ name: "XBAR_CLB_SD2FLT4_COMPL", displayName: "SD2FLT4 COMPL" },
	{ name: "XBAR_CLB_SD3FLT1_COMPH", displayName: "SD3FLT1 COMPH" },
	{ name: "XBAR_CLB_SD3FLT1_COMPL", displayName: "SD3FLT1 COMPL" },
	{ name: "XBAR_CLB_SD3FLT2_COMPH", displayName: "SD3FLT2 COMPH" },
	{ name: "XBAR_CLB_SD3FLT2_COMPL", displayName: "SD3FLT2 COMPL" },
	{ name: "XBAR_CLB_SD3FLT3_COMPH", displayName: "SD3FLT3 COMPH" },
	{ name: "XBAR_CLB_SD3FLT3_COMPL", displayName: "SD3FLT3 COMPL" },
	{ name: "XBAR_CLB_SD3FLT4_COMPH", displayName: "SD3FLT4 COMPH" },
	{ name: "XBAR_CLB_SD3FLT4_COMPL", displayName: "SD3FLT4 COMPL" },
	{ name: "XBAR_CLB_SD4FLT1_COMPH", displayName: "SD4FLT1 COMPH" },
	{ name: "XBAR_CLB_SD4FLT1_COMPL", displayName: "SD4FLT1 COMPL" },
	{ name: "XBAR_CLB_SD4FLT2_COMPH", displayName: "SD4FLT2 COMPH" },
	{ name: "XBAR_CLB_SD4FLT2_COMPL", displayName: "SD4FLT2 COMPL" },
	{ name: "XBAR_CLB_SD4FLT3_COMPH", displayName: "SD4FLT3 COMPH" },
	{ name: "XBAR_CLB_SD4FLT3_COMPL", displayName: "SD4FLT3 COMPL" },
	{ name: "XBAR_CLB_SD4FLT4_COMPH", displayName: "SD4FLT4 COMPH" },
	{ name: "XBAR_CLB_SD4FLT4_COMPL", displayName: "SD4FLT4 COMPL" },
	{ name: "XBAR_CLB_ADCAEVT1", displayName: "ADCAEVT1" },
	{ name: "XBAR_CLB_ADCAEVT2", displayName: "ADCAEVT2" },
	{ name: "XBAR_CLB_ADCAEVT3", displayName: "ADCAEVT3" },
	{ name: "XBAR_CLB_ADCAEVT4", displayName: "ADCAEVT4" },
	{ name: "XBAR_CLB_ADCBEVT1", displayName: "ADCBEVT1" },
	{ name: "XBAR_CLB_ADCBEVT2", displayName: "ADCBEVT2" },
	{ name: "XBAR_CLB_ADCBEVT3", displayName: "ADCBEVT3" },
	{ name: "XBAR_CLB_ADCBEVT4", displayName: "ADCBEVT4" },
	{ name: "XBAR_CLB_ADCCEVT1", displayName: "ADCCEVT1" },
	{ name: "XBAR_CLB_ADCCEVT2", displayName: "ADCCEVT2" },
	{ name: "XBAR_CLB_ADCCEVT3", displayName: "ADCCEVT3" },
	{ name: "XBAR_CLB_ADCCEVT4", displayName: "ADCCEVT4" },
	{ name: "XBAR_CLB_ADCDEVT1", displayName: "ADCDEVT1" },
	{ name: "XBAR_CLB_ADCDEVT2", displayName: "ADCDEVT2" },
	{ name: "XBAR_CLB_ADCDEVT3", displayName: "ADCDEVT3" },
	{ name: "XBAR_CLB_ADCDEVT4", displayName: "ADCDEVT4" },
	{ name: "XBAR_CLB_ADCEEVT1", displayName: "ADCEEVT1" },
	{ name: "XBAR_CLB_ADCEEVT2", displayName: "ADCEEVT2" },
	{ name: "XBAR_CLB_ADCEEVT3", displayName: "ADCEEVT3" },
	{ name: "XBAR_CLB_ADCEEVT4", displayName: "ADCEEVT4" },
	{ name: "XBAR_CLB_CPU1_ADCCHECK_EVT1", displayName: "CPU1 ADCCHECKEVT1" },
	{ name: "XBAR_CLB_CPU1_ADCCHECK_EVT2", displayName: "CPU1 ADCCHECKEVT2" },
	{ name: "XBAR_CLB_CPU1_ADCCHECK_EVT3", displayName: "CPU1 ADCCHECKEVT3" },
	{ name: "XBAR_CLB_CPU1_ADCCHECK_EVT4", displayName: "CPU1 ADCCHECKEVT4" },
	{ name: "XBAR_CLB_CPU2_ADCCHECK_EVT1", displayName: "CPU2 ADCCHECKEVT1" },
	{ name: "XBAR_CLB_CPU2_ADCCHECK_EVT2", displayName: "CPU2 ADCCHECKEVT2" },
	{ name: "XBAR_CLB_CPU2_ADCCHECK_EVT3", displayName: "CPU2 ADCCHECKEVT3" },
	{ name: "XBAR_CLB_CPU2_ADCCHECK_EVT4", displayName: "CPU2 ADCCHECKEVT4" },
	{ name: "XBAR_CLB_CPU3_ADCCHECK_EVT1", displayName: "CPU3 ADCCHECKEVT1" },
	{ name: "XBAR_CLB_CPU3_ADCCHECK_EVT2", displayName: "CPU3 ADCCHECKEVT2" },
	{ name: "XBAR_CLB_CPU3_ADCCHECK_EVT3", displayName: "CPU3 ADCCHECKEVT3" },
	{ name: "XBAR_CLB_CPU3_ADCCHECK_EVT4", displayName: "CPU3 ADCCHECKEVT4" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT1", displayName: "INPUTXBAR INPUT1" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT2", displayName: "INPUTXBAR INPUT2" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT3", displayName: "INPUTXBAR INPUT3" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT4", displayName: "INPUTXBAR INPUT4" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT5", displayName: "INPUTXBAR INPUT5" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT6", displayName: "INPUTXBAR INPUT6" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT7", displayName: "INPUTXBAR INPUT7" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT8", displayName: "INPUTXBAR INPUT8" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT9", displayName: "INPUTXBAR INPUT9" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT10", displayName: "INPUTXBAR INPUT10" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT11", displayName: "INPUTXBAR INPUT11" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT12", displayName: "INPUTXBAR INPUT12" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT13", displayName: "INPUTXBAR INPUT13" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT14", displayName: "INPUTXBAR INPUT14" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT15", displayName: "INPUTXBAR INPUT15" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT16", displayName: "INPUTXBAR INPUT16" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT17", displayName: "INPUTXBAR INPUT17" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT18", displayName: "INPUTXBAR INPUT18" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT19", displayName: "INPUTXBAR INPUT19" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT20", displayName: "INPUTXBAR INPUT20" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT21", displayName: "INPUTXBAR INPUT21" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT22", displayName: "INPUTXBAR INPUT22" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT23", displayName: "INPUTXBAR INPUT23" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT24", displayName: "INPUTXBAR INPUT24" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT25", displayName: "INPUTXBAR INPUT25" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT26", displayName: "INPUTXBAR INPUT26" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT27", displayName: "INPUTXBAR INPUT27" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT28", displayName: "INPUTXBAR INPUT28" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT29", displayName: "INPUTXBAR INPUT29" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT30", displayName: "INPUTXBAR INPUT30" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT31", displayName: "INPUTXBAR INPUT31" },
	{ name: "XBAR_CLB_INPUTXBAR_INPUT32", displayName: "INPUTXBAR INPUT32" },
	{ name: "XBAR_CLB_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_CLB_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_CLB_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_CLB_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_CLB_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_CLB_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_CLB_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_CLB_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_CLB_CLB5_OUT4", displayName: "CLB5 OUT4" },
	{ name: "XBAR_CLB_CLB5_OUT5", displayName: "CLB5 OUT5" },
	{ name: "XBAR_CLB_CLB6_OUT4", displayName: "CLB6 OUT4" },
	{ name: "XBAR_CLB_CLB6_OUT5", displayName: "CLB6 OUT5" },
	{ name: "XBAR_CLB_FSIA_RX_TRIG1", displayName: "FSIA RX TRIG1" },
	{ name: "XBAR_CLB_FSIB_RX_TRIG1", displayName: "FSIB RX TRIG1" },
	{ name: "XBAR_CLB_FSIC_RX_TRIG1", displayName: "FSIC RX TRIG1" },
	{ name: "XBAR_CLB_FSID_RX_TRIG1", displayName: "FSID RX TRIG1" },
	{ name: "XBAR_CLB_FSIA_RX_TRIG2", displayName: "FSIA RX TRIG2" },
	{ name: "XBAR_CLB_FSIB_RX_TRIG2", displayName: "FSIB RX TRIG2" },
	{ name: "XBAR_CLB_FSIC_RX_TRIG2", displayName: "FSIC RX TRIG2" },
	{ name: "XBAR_CLB_FSID_RX_TRIG2", displayName: "FSID RX TRIG2" },
	{ name: "XBAR_CLB_FSIA_RX_TRIG3", displayName: "FSIA RX TRIG3" },
	{ name: "XBAR_CLB_FSIB_RX_TRIG3", displayName: "FSIB RX TRIG3" },
	{ name: "XBAR_CLB_FSIC_RX_TRIG3", displayName: "FSIC RX TRIG3" },
	{ name: "XBAR_CLB_FSID_RX_TRIG3", displayName: "FSID RX TRIG3" },
	{ name: "XBAR_CLB_ECAT_SYNC0", displayName: "ECAT SYNC0" },
	{ name: "XBAR_CLB_ECAT_SYNC1", displayName: "ECAT SYNC1" },
	{ name: "XBAR_CLB_ECAP1_OUT", displayName: "ECAP1 OUT" },
	{ name: "XBAR_CLB_ECAP2_OUT", displayName: "ECAP2 OUT" },
	{ name: "XBAR_CLB_ECAP3_OUT", displayName: "ECAP3 OUT" },
	{ name: "XBAR_CLB_ECAP4_OUT", displayName: "ECAP4 OUT" },
	{ name: "XBAR_CLB_ECAP5_OUT", displayName: "ECAP5 OUT" },
	{ name: "XBAR_CLB_ECAP6_OUT", displayName: "ECAP6 OUT" },
	{ name: "XBAR_CLB_ECAP1_TRIPOUT", displayName: "ECAP1 TRIPOUT" },
	{ name: "XBAR_CLB_ECAP2_TRIPOUT", displayName: "ECAP2 TRIPOUT" },
	{ name: "XBAR_CLB_ECAP3_TRIPOUT", displayName: "ECAP3 TRIPOUT" },
	{ name: "XBAR_CLB_ECAP4_TRIPOUT", displayName: "ECAP4 TRIPOUT" },
	{ name: "XBAR_CLB_ECAP5_TRIPOUT", displayName: "ECAP5 TRIPOUT" },
	{ name: "XBAR_CLB_ECAP6_TRIPOUT", displayName: "ECAP6 TRIPOUT" },
	{ name: "XBAR_CLB_ADCSOCA", displayName: "ADCSOCA" },
	{ name: "XBAR_CLB_ADCSOCB", displayName: "ADCSOCB" },
	{ name: "XBAR_CLB_ESM_GEN_EVENT", displayName: "ESM GEN EVENT" },
	{ name: "XBAR_CLB_EXTSYNCOUT", displayName: "EXTSYNCOUT" },
	{ name: "XBAR_CLB_MCANA_FEVT0", displayName: "MCANA FEVT0" },
	{ name: "XBAR_CLB_MCANA_FEVT1", displayName: "MCANA FEVT1" },
	{ name: "XBAR_CLB_MCANA_FEVT2", displayName: "MCANA FEVT2" },
	{ name: "XBAR_CLB_MCANB_FEVT0", displayName: "MCANB FEVT0" },
	{ name: "XBAR_CLB_MCANB_FEVT1", displayName: "MCANB FEVT1" },
	{ name: "XBAR_CLB_MCANB_FEVT2", displayName: "MCANB FEVT2" },
	{ name: "XBAR_CLB_MCANC_FEVT0", displayName: "MCANC FEVT0" },
	{ name: "XBAR_CLB_MCANC_FEVT1", displayName: "MCANC FEVT1" },
	{ name: "XBAR_CLB_MCANC_FEVT2", displayName: "MCANC FEVT2" },
	{ name: "XBAR_CLB_MCAND_FEVT0", displayName: "MCAND FEVT0" },
	{ name: "XBAR_CLB_MCAND_FEVT1", displayName: "MCAND FEVT1" },
	{ name: "XBAR_CLB_MCAND_FEVT2", displayName: "MCAND FEVT2" },
	{ name: "XBAR_CLB_MCANE_FEVT0", displayName: "MCANE FEVT0" },
	{ name: "XBAR_CLB_MCANE_FEVT1", displayName: "MCANE FEVT1" },
	{ name: "XBAR_CLB_MCANE_FEVT2", displayName: "MCANE FEVT2" },
	{ name: "XBAR_CLB_MCANF_FEVT0", displayName: "MCANF FEVT0" },
	{ name: "XBAR_CLB_MCANF_FEVT1", displayName: "MCANF FEVT1" },
	{ name: "XBAR_CLB_MCANF_FEVT2", displayName: "MCANF FEVT2" },
	{ name: "XBAR_CLB_CPU1_ERADEVT8", displayName: "CPU1 ERADEVT8" },
	{ name: "XBAR_CLB_CPU1_ERADEVT9", displayName: "CPU1 ERADEVT9" },
	{ name: "XBAR_CLB_CPU1_ERADEVT10", displayName: "CPU1 ERADEVT10" },
	{ name: "XBAR_CLB_CPU1_ERADEVT11", displayName: "CPU1 ERADEVT11" },
	{ name: "XBAR_CLB_CPU2_ERADEVT8", displayName: "CPU2 ERADEVT8" },
	{ name: "XBAR_CLB_CPU2_ERADEVT9", displayName: "CPU2 ERADEVT9" },
	{ name: "XBAR_CLB_CPU2_ERADEVT10", displayName: "CPU2 ERADEVT10" },
	{ name: "XBAR_CLB_CPU2_ERADEVT11", displayName: "CPU2 ERADEVT11" },
	{ name: "XBAR_CLB_CPU3_ERADEVT8", displayName: "CPU3 ERADEVT8" },
	{ name: "XBAR_CLB_CPU3_ERADEVT9", displayName: "CPU3 ERADEVT9" },
	{ name: "XBAR_CLB_CPU3_ERADEVT10", displayName: "CPU3 ERADEVT10" },
	{ name: "XBAR_CLB_CPU3_ERADEVT11", displayName: "CPU3 ERADEVT11" },
	{ name: "XBAR_CLB_WADI1OUT0", displayName: "WADI1OUT0" },
	{ name: "XBAR_CLB_WADI1OUT1", displayName: "WADI1OUT1" },
	{ name: "XBAR_CLB_WADI1OUT2", displayName: "WADI1OUT2" },
	{ name: "XBAR_CLB_WADI1OUT3", displayName: "WADI1OUT3" },
	{ name: "XBAR_CLB_WADI1OUT4", displayName: "WADI1OUT4" },
	{ name: "XBAR_CLB_WADI1OUT5", displayName: "WADI1OUT5" },
	{ name: "XBAR_CLB_WADI1OUT6", displayName: "WADI1OUT6" },
	{ name: "XBAR_CLB_WADI1OUT7", displayName: "WADI1OUT7" },
	{ name: "XBAR_CLB_WADI2OUT0", displayName: "WADI2OUT0" },
	{ name: "XBAR_CLB_WADI2OUT1", displayName: "WADI2OUT1" },
	{ name: "XBAR_CLB_WADI2OUT2", displayName: "WADI2OUT2" },
	{ name: "XBAR_CLB_WADI2OUT3", displayName: "WADI2OUT3" },
	{ name: "XBAR_CLB_WADI2OUT4", displayName: "WADI2OUT4" },
	{ name: "XBAR_CLB_WADI2OUT5", displayName: "WADI2OUT5" },
	{ name: "XBAR_CLB_WADI2OUT6", displayName: "WADI2OUT6" },
	{ name: "XBAR_CLB_WADI2OUT7", displayName: "WADI2OUT7" },
]
let XBAR_MindbXbarInputSource = [
	{ name: "XBAR_MINDB_EPWM1A_DB_NO_HR", displayName: "EPWM1A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM2A_DB_NO_HR", displayName: "EPWM2A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM3A_DB_NO_HR", displayName: "EPWM3A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM4A_DB_NO_HR", displayName: "EPWM4A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM5A_DB_NO_HR", displayName: "EPWM5A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM6A_DB_NO_HR", displayName: "EPWM6A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM7A_DB_NO_HR", displayName: "EPWM7A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM8A_DB_NO_HR", displayName: "EPWM8A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM9A_DB_NO_HR", displayName: "EPWM9A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM10A_DB_NO_HR", displayName: "EPWM10A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM11A_DB_NO_HR", displayName: "EPWM11A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM12A_DB_NO_HR", displayName: "EPWM12A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM13A_DB_NO_HR", displayName: "EPWM13A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM14A_DB_NO_HR", displayName: "EPWM14A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM15A_DB_NO_HR", displayName: "EPWM15A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM16A_DB_NO_HR", displayName: "EPWM16A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM17A_DB_NO_HR", displayName: "EPWM17A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM18A_DB_NO_HR", displayName: "EPWM18A DB NO HR" },
	{ name: "XBAR_MINDB_EPWM1B_DB_NO_HR", displayName: "EPWM1B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM2B_DB_NO_HR", displayName: "EPWM2B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM3B_DB_NO_HR", displayName: "EPWM3B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM4B_DB_NO_HR", displayName: "EPWM4B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM5B_DB_NO_HR", displayName: "EPWM5B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM6B_DB_NO_HR", displayName: "EPWM6B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM7B_DB_NO_HR", displayName: "EPWM7B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM8B_DB_NO_HR", displayName: "EPWM8B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM9B_DB_NO_HR", displayName: "EPWM9B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM10B_DB_NO_HR", displayName: "EPWM10B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM11B_DB_NO_HR", displayName: "EPWM11B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM12B_DB_NO_HR", displayName: "EPWM12B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM13B_DB_NO_HR", displayName: "EPWM13B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM14B_DB_NO_HR", displayName: "EPWM14B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM15B_DB_NO_HR", displayName: "EPWM15B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM16B_DB_NO_HR", displayName: "EPWM16B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM17B_DB_NO_HR", displayName: "EPWM17B DB NO HR" },
	{ name: "XBAR_MINDB_EPWM18B_DB_NO_HR", displayName: "EPWM18B DB NO HR" },
	{ name: "XBAR_MINDB_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_MINDB_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_MINDB_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_MINDB_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_MINDB_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_MINDB_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_MINDB_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_MINDB_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_MINDB_CLB5_OUT4", displayName: "CLB5 OUT4" },
	{ name: "XBAR_MINDB_CLB5_OUT5", displayName: "CLB5 OUT5" },
	{ name: "XBAR_MINDB_CLB6_OUT4", displayName: "CLB6 OUT4" },
	{ name: "XBAR_MINDB_CLB6_OUT5", displayName: "CLB6 OUT5" },
]
let XBAR_IclXbarInputSource = [
	{ name: "XBAR_ICL_EPWM1A_MINDB", displayName: "EPWM1A MINDB" },
	{ name: "XBAR_ICL_EPWM2A_MINDB", displayName: "EPWM2A MINDB" },
	{ name: "XBAR_ICL_EPWM3A_MINDB", displayName: "EPWM3A MINDB" },
	{ name: "XBAR_ICL_EPWM4A_MINDB", displayName: "EPWM4A MINDB" },
	{ name: "XBAR_ICL_EPWM5A_MINDB", displayName: "EPWM5A MINDB" },
	{ name: "XBAR_ICL_EPWM6A_MINDB", displayName: "EPWM6A MINDB" },
	{ name: "XBAR_ICL_EPWM7A_MINDB", displayName: "EPWM7A MINDB" },
	{ name: "XBAR_ICL_EPWM8A_MINDB", displayName: "EPWM8A MINDB" },
	{ name: "XBAR_ICL_EPWM9A_MINDB", displayName: "EPWM9A MINDB" },
	{ name: "XBAR_ICL_EPWM10A_MINDB", displayName: "EPWM10A MINDB" },
	{ name: "XBAR_ICL_EPWM11A_MINDB", displayName: "EPWM11A MINDB" },
	{ name: "XBAR_ICL_EPWM12A_MINDB", displayName: "EPWM12A MINDB" },
	{ name: "XBAR_ICL_EPWM13A_MINDB", displayName: "EPWM13A MINDB" },
	{ name: "XBAR_ICL_EPWM14A_MINDB", displayName: "EPWM14A MINDB" },
	{ name: "XBAR_ICL_EPWM15A_MINDB", displayName: "EPWM15A MINDB" },
	{ name: "XBAR_ICL_EPWM16A_MINDB", displayName: "EPWM16A MINDB" },
	{ name: "XBAR_ICL_EPWM17A_MINDB", displayName: "EPWM17A MINDB" },
	{ name: "XBAR_ICL_EPWM18A_MINDB", displayName: "EPWM18A MINDB" },
	{ name: "XBAR_ICL_EPWM1B_MINDB", displayName: "EPWM1B MINDB" },
	{ name: "XBAR_ICL_EPWM2B_MINDB", displayName: "EPWM2B MINDB" },
	{ name: "XBAR_ICL_EPWM3B_MINDB", displayName: "EPWM3B MINDB" },
	{ name: "XBAR_ICL_EPWM4B_MINDB", displayName: "EPWM4B MINDB" },
	{ name: "XBAR_ICL_EPWM5B_MINDB", displayName: "EPWM5B MINDB" },
	{ name: "XBAR_ICL_EPWM6B_MINDB", displayName: "EPWM6B MINDB" },
	{ name: "XBAR_ICL_EPWM7B_MINDB", displayName: "EPWM7B MINDB" },
	{ name: "XBAR_ICL_EPWM8B_MINDB", displayName: "EPWM8B MINDB" },
	{ name: "XBAR_ICL_EPWM9B_MINDB", displayName: "EPWM9B MINDB" },
	{ name: "XBAR_ICL_EPWM10B_MINDB", displayName: "EPWM10B MINDB" },
	{ name: "XBAR_ICL_EPWM11B_MINDB", displayName: "EPWM11B MINDB" },
	{ name: "XBAR_ICL_EPWM12B_MINDB", displayName: "EPWM12B MINDB" },
	{ name: "XBAR_ICL_EPWM13B_MINDB", displayName: "EPWM13B MINDB" },
	{ name: "XBAR_ICL_EPWM14B_MINDB", displayName: "EPWM14B MINDB" },
	{ name: "XBAR_ICL_EPWM15B_MINDB", displayName: "EPWM15B MINDB" },
	{ name: "XBAR_ICL_EPWM16B_MINDB", displayName: "EPWM16B MINDB" },
	{ name: "XBAR_ICL_EPWM17B_MINDB", displayName: "EPWM17B MINDB" },
	{ name: "XBAR_ICL_EPWM18B_MINDB", displayName: "EPWM18B MINDB" },
	{ name: "XBAR_ICL_CLB1_OUT4", displayName: "CLB1 OUT4" },
	{ name: "XBAR_ICL_CLB1_OUT5", displayName: "CLB1 OUT5" },
	{ name: "XBAR_ICL_CLB2_OUT4", displayName: "CLB2 OUT4" },
	{ name: "XBAR_ICL_CLB2_OUT5", displayName: "CLB2 OUT5" },
	{ name: "XBAR_ICL_CLB3_OUT4", displayName: "CLB3 OUT4" },
	{ name: "XBAR_ICL_CLB3_OUT5", displayName: "CLB3 OUT5" },
	{ name: "XBAR_ICL_CLB4_OUT4", displayName: "CLB4 OUT4" },
	{ name: "XBAR_ICL_CLB4_OUT5", displayName: "CLB4 OUT5" },
	{ name: "XBAR_ICL_CLB5_OUT4", displayName: "CLB5 OUT4" },
	{ name: "XBAR_ICL_CLB5_OUT5", displayName: "CLB5 OUT5" },
	{ name: "XBAR_ICL_CLB6_OUT4", displayName: "CLB6 OUT4" },
	{ name: "XBAR_ICL_CLB6_OUT5", displayName: "CLB6 OUT5" },
]
let XBAR_InputFlag = [
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPL", displayName: "INPUT FLG CMPSS1 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPH", displayName: "INPUT FLG CMPSS1 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPL", displayName: "INPUT FLG CMPSS2 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPH", displayName: "INPUT FLG CMPSS2 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPL", displayName: "INPUT FLG CMPSS3 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPH", displayName: "INPUT FLG CMPSS3 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPL", displayName: "INPUT FLG CMPSS4 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPH", displayName: "INPUT FLG CMPSS4 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS5_CTRIPL", displayName: "INPUT FLG CMPSS5 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS5_CTRIPH", displayName: "INPUT FLG CMPSS5 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS6_CTRIPL", displayName: "INPUT FLG CMPSS6 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS6_CTRIPH", displayName: "INPUT FLG CMPSS6 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS7_CTRIPL", displayName: "INPUT FLG CMPSS7 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS7_CTRIPH", displayName: "INPUT FLG CMPSS7 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS8_CTRIPL", displayName: "INPUT FLG CMPSS8 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS8_CTRIPH", displayName: "INPUT FLG CMPSS8 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS9_CTRIPH", displayName: "INPUT FLG CMPSS9 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS9_CTRIPL", displayName: "INPUT FLG CMPSS9 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS10_CTRIPH", displayName: "INPUT FLG CMPSS10 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS10_CTRIPL", displayName: "INPUT FLG CMPSS10 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS11_CTRIPH", displayName: "INPUT FLG CMPSS11 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS11_CTRIPL", displayName: "INPUT FLG CMPSS11 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS12_CTRIPH", displayName: "INPUT FLG CMPSS12 CTRIPH" },
	{ name: "XBAR_INPUT_FLG_CMPSS12_CTRIPL", displayName: "INPUT FLG CMPSS12 CTRIPL" },
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPOUTL", displayName: "INPUT FLG CMPSS1 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS1_CTRIPOUTH", displayName: "INPUT FLG CMPSS1 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPOUTL", displayName: "INPUT FLG CMPSS2 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS2_CTRIPOUTH", displayName: "INPUT FLG CMPSS2 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPOUTL", displayName: "INPUT FLG CMPSS3 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS3_CTRIPOUTH", displayName: "INPUT FLG CMPSS3 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPOUTL", displayName: "INPUT FLG CMPSS4 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS4_CTRIPOUTH", displayName: "INPUT FLG CMPSS4 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS5_CTRIPOUTL", displayName: "INPUT FLG CMPSS5 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS5_CTRIPOUTH", displayName: "INPUT FLG CMPSS5 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS6_CTRIPOUTL", displayName: "INPUT FLG CMPSS6 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS6_CTRIPOUTH", displayName: "INPUT FLG CMPSS6 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS7_CTRIPOUTL", displayName: "INPUT FLG CMPSS7 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS7_CTRIPOUTH", displayName: "INPUT FLG CMPSS7 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS8_CTRIPOUTL", displayName: "INPUT FLG CMPSS8 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS8_CTRIPOUTH", displayName: "INPUT FLG CMPSS8 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS9_CTRIPOUTH", displayName: "INPUT FLG CMPSS9 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS9_CTRIPOUTL", displayName: "INPUT FLG CMPSS9 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS10_CTRIPOUTH", displayName: "INPUT FLG CMPSS10 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS10_CTRIPOUTL", displayName: "INPUT FLG CMPSS10 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS11_CTRIPOUTH", displayName: "INPUT FLG CMPSS11 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS11_CTRIPOUTL", displayName: "INPUT FLG CMPSS11 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_CMPSS12_CTRIPOUTH", displayName: "INPUT FLG CMPSS12 CTRIPOUTH" },
	{ name: "XBAR_INPUT_FLG_CMPSS12_CTRIPOUTL", displayName: "INPUT FLG CMPSS12 CTRIPOUTL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT1_COMPL", displayName: "INPUT FLG SD1FLT1 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT1_COMPH", displayName: "INPUT FLG SD1FLT1 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD1FLT2_COMPL", displayName: "INPUT FLG SD1FLT2 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT2_COMPH", displayName: "INPUT FLG SD1FLT2 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD1FLT3_COMPL", displayName: "INPUT FLG SD1FLT3 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT3_COMPH", displayName: "INPUT FLG SD1FLT3 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD1FLT4_COMPL", displayName: "INPUT FLG SD1FLT4 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD1FLT4_COMPH", displayName: "INPUT FLG SD1FLT4 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT1_COMPL", displayName: "INPUT FLG SD2FLT1 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT1_COMPH", displayName: "INPUT FLG SD2FLT1 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT2_COMPL", displayName: "INPUT FLG SD2FLT2 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT2_COMPH", displayName: "INPUT FLG SD2FLT2 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT3_COMPL", displayName: "INPUT FLG SD2FLT3 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT3_COMPH", displayName: "INPUT FLG SD2FLT3 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD2FLT4_COMPL", displayName: "INPUT FLG SD2FLT4 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD2FLT4_COMPH", displayName: "INPUT FLG SD2FLT4 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD3FLT1_COMPH", displayName: "INPUT FLG SD3FLT1 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD3FLT1_COMPL", displayName: "INPUT FLG SD3FLT1 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD3FLT2_COMPH", displayName: "INPUT FLG SD3FLT2 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD3FLT2_COMPL", displayName: "INPUT FLG SD3FLT2 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD3FLT3_COMPH", displayName: "INPUT FLG SD3FLT3 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD3FLT3_COMPL", displayName: "INPUT FLG SD3FLT3 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD3FLT4_COMPH", displayName: "INPUT FLG SD3FLT4 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD3FLT4_COMPL", displayName: "INPUT FLG SD3FLT4 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD4FLT1_COMPH", displayName: "INPUT FLG SD4FLT1 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD4FLT1_COMPL", displayName: "INPUT FLG SD4FLT1 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD4FLT2_COMPH", displayName: "INPUT FLG SD4FLT2 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD4FLT2_COMPL", displayName: "INPUT FLG SD4FLT2 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD4FLT3_COMPH", displayName: "INPUT FLG SD4FLT3 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD4FLT3_COMPL", displayName: "INPUT FLG SD4FLT3 COMPL" },
	{ name: "XBAR_INPUT_FLG_SD4FLT4_COMPH", displayName: "INPUT FLG SD4FLT4 COMPH" },
	{ name: "XBAR_INPUT_FLG_SD4FLT4_COMPL", displayName: "INPUT FLG SD4FLT4 COMPL" },
	{ name: "XBAR_INPUT_FLG_INPUT1", displayName: "INPUT FLG INPUT1" },
	{ name: "XBAR_INPUT_FLG_INPUT2", displayName: "INPUT FLG INPUT2" },
	{ name: "XBAR_INPUT_FLG_INPUT3", displayName: "INPUT FLG INPUT3" },
	{ name: "XBAR_INPUT_FLG_INPUT4", displayName: "INPUT FLG INPUT4" },
	{ name: "XBAR_INPUT_FLG_INPUT5", displayName: "INPUT FLG INPUT5" },
	{ name: "XBAR_INPUT_FLG_INPUT6", displayName: "INPUT FLG INPUT6" },
	{ name: "XBAR_INPUT_FLG_INPUT7", displayName: "INPUT FLG INPUT7" },
	{ name: "XBAR_INPUT_FLG_INPUT8", displayName: "INPUT FLG INPUT8" },
	{ name: "XBAR_INPUT_FLG_INPUT9", displayName: "INPUT FLG INPUT9" },
	{ name: "XBAR_INPUT_FLG_INPUT10", displayName: "INPUT FLG INPUT10" },
	{ name: "XBAR_INPUT_FLG_INPUT11", displayName: "INPUT FLG INPUT11" },
	{ name: "XBAR_INPUT_FLG_INPUT12", displayName: "INPUT FLG INPUT12" },
	{ name: "XBAR_INPUT_FLG_INPUT13", displayName: "INPUT FLG INPUT13" },
	{ name: "XBAR_INPUT_FLG_INPUT14", displayName: "INPUT FLG INPUT14" },
	{ name: "XBAR_INPUT_FLG_INPUT15", displayName: "INPUT FLG INPUT15" },
	{ name: "XBAR_INPUT_FLG_INPUT16", displayName: "INPUT FLG INPUT16" },
	{ name: "XBAR_INPUT_FLG_INPUT17", displayName: "INPUT FLG INPUT17" },
	{ name: "XBAR_INPUT_FLG_INPUT18", displayName: "INPUT FLG INPUT18" },
	{ name: "XBAR_INPUT_FLG_INPUT19", displayName: "INPUT FLG INPUT19" },
	{ name: "XBAR_INPUT_FLG_INPUT20", displayName: "INPUT FLG INPUT20" },
	{ name: "XBAR_INPUT_FLG_INPUT21", displayName: "INPUT FLG INPUT21" },
	{ name: "XBAR_INPUT_FLG_INPUT22", displayName: "INPUT FLG INPUT22" },
	{ name: "XBAR_INPUT_FLG_INPUT23", displayName: "INPUT FLG INPUT23" },
	{ name: "XBAR_INPUT_FLG_INPUT24", displayName: "INPUT FLG INPUT24" },
	{ name: "XBAR_INPUT_FLG_INPUT25", displayName: "INPUT FLG INPUT25" },
	{ name: "XBAR_INPUT_FLG_INPUT26", displayName: "INPUT FLG INPUT26" },
	{ name: "XBAR_INPUT_FLG_INPUT27", displayName: "INPUT FLG INPUT27" },
	{ name: "XBAR_INPUT_FLG_INPUT28", displayName: "INPUT FLG INPUT28" },
	{ name: "XBAR_INPUT_FLG_INPUT29", displayName: "INPUT FLG INPUT29" },
	{ name: "XBAR_INPUT_FLG_INPUT30", displayName: "INPUT FLG INPUT30" },
	{ name: "XBAR_INPUT_FLG_INPUT31", displayName: "INPUT FLG INPUT31" },
	{ name: "XBAR_INPUT_FLG_INPUT32", displayName: "INPUT FLG INPUT32" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT1", displayName: "INPUT FLG ADCAEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT2", displayName: "INPUT FLG ADCAEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT3", displayName: "INPUT FLG ADCAEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCAEVT4", displayName: "INPUT FLG ADCAEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT1", displayName: "INPUT FLG ADCBEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT2", displayName: "INPUT FLG ADCBEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT3", displayName: "INPUT FLG ADCBEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCBEVT4", displayName: "INPUT FLG ADCBEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT1", displayName: "INPUT FLG ADCCEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT2", displayName: "INPUT FLG ADCCEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT3", displayName: "INPUT FLG ADCCEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCCEVT4", displayName: "INPUT FLG ADCCEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT1", displayName: "INPUT FLG ADCDEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT2", displayName: "INPUT FLG ADCDEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT3", displayName: "INPUT FLG ADCDEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCDEVT4", displayName: "INPUT FLG ADCDEVT4" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT1", displayName: "INPUT FLG ADCEEVT1" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT2", displayName: "INPUT FLG ADCEEVT2" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT3", displayName: "INPUT FLG ADCEEVT3" },
	{ name: "XBAR_INPUT_FLG_ADCEEVT4", displayName: "INPUT FLG ADCEEVT4" },
	{ name: "XBAR_INPUT_FLG_CPU1_ADCCHECKEVT1", displayName: "INPUT FLG CPU1 ADCCHECKEVT1" },
	{ name: "XBAR_INPUT_FLG_CPU1_ADCCHECKEVT2", displayName: "INPUT FLG CPU1 ADCCHECKEVT2" },
	{ name: "XBAR_INPUT_FLG_CPU1_ADCCHECKEVT3", displayName: "INPUT FLG CPU1 ADCCHECKEVT3" },
	{ name: "XBAR_INPUT_FLG_CPU1_ADCCHECKEVT4", displayName: "INPUT FLG CPU1 ADCCHECKEVT4" },
	{ name: "XBAR_INPUT_FLG_CPU2_ADCCHECKEVT1", displayName: "INPUT FLG CPU2 ADCCHECKEVT1" },
	{ name: "XBAR_INPUT_FLG_CPU2_ADCCHECKEVT2", displayName: "INPUT FLG CPU2 ADCCHECKEVT2" },
	{ name: "XBAR_INPUT_FLG_CPU2_ADCCHECKEVT3", displayName: "INPUT FLG CPU2 ADCCHECKEVT3" },
	{ name: "XBAR_INPUT_FLG_CPU2_ADCCHECKEVT4", displayName: "INPUT FLG CPU2 ADCCHECKEVT4" },
	{ name: "XBAR_INPUT_FLG_CPU3_ADCCHECKEVT1", displayName: "INPUT FLG CPU3 ADCCHECKEVT1" },
	{ name: "XBAR_INPUT_FLG_CPU3_ADCCHECKEVT2", displayName: "INPUT FLG CPU3 ADCCHECKEVT2" },
	{ name: "XBAR_INPUT_FLG_CPU3_ADCCHECKEVT3", displayName: "INPUT FLG CPU3 ADCCHECKEVT3" },
	{ name: "XBAR_INPUT_FLG_CPU3_ADCCHECKEVT4", displayName: "INPUT FLG CPU3 ADCCHECKEVT4" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT4", displayName: "INPUT FLG CLB1 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT5", displayName: "INPUT FLG CLB1 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT4", displayName: "INPUT FLG CLB2 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT5", displayName: "INPUT FLG CLB2 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT4", displayName: "INPUT FLG CLB3 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT5", displayName: "INPUT FLG CLB3 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT4", displayName: "INPUT FLG CLB4 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT5", displayName: "INPUT FLG CLB4 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT4", displayName: "INPUT FLG CLB5 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT5", displayName: "INPUT FLG CLB5 OUT5" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT4", displayName: "INPUT FLG CLB6 OUT4" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT5", displayName: "INPUT FLG CLB6 OUT5" },
	{ name: "XBAR_INPUT_FLG_FSIA_RX_TRIG1", displayName: "INPUT FLG FSIA RX TRIG1" },
	{ name: "XBAR_INPUT_FLG_FSIB_RX_TRIG1", displayName: "INPUT FLG FSIB RX TRIG1" },
	{ name: "XBAR_INPUT_FLG_FSIC_RX_TRIG1", displayName: "INPUT FLG FSIC RX TRIG1" },
	{ name: "XBAR_INPUT_FLG_FSID_RX_TRIG1", displayName: "INPUT FLG FSID RX TRIG1" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT0", displayName: "INPUT FLG WADI1OUT0" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT1", displayName: "INPUT FLG WADI1OUT1" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT2", displayName: "INPUT FLG WADI1OUT2" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT3", displayName: "INPUT FLG WADI1OUT3" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT4", displayName: "INPUT FLG WADI1OUT4" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT5", displayName: "INPUT FLG WADI1OUT5" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT6", displayName: "INPUT FLG WADI1OUT6" },
	{ name: "XBAR_INPUT_FLG_WADI1OUT7", displayName: "INPUT FLG WADI1OUT7" },
	{ name: "XBAR_INPUT_FLG_ECATSYNC0", displayName: "INPUT FLG ECATSYNC0" },
	{ name: "XBAR_INPUT_FLG_ECATSYNC1", displayName: "INPUT FLG ECATSYNC1" },
	{ name: "XBAR_INPUT_FLG_ECAP1_OUT", displayName: "INPUT FLG ECAP1 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP2_OUT", displayName: "INPUT FLG ECAP2 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP3_OUT", displayName: "INPUT FLG ECAP3 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP4_OUT", displayName: "INPUT FLG ECAP4 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP5_OUT", displayName: "INPUT FLG ECAP5 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP6_OUT", displayName: "INPUT FLG ECAP6 OUT" },
	{ name: "XBAR_INPUT_FLG_ECAP1_TRIPOUT", displayName: "INPUT FLG ECAP1 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_ECAP2_TRIPOUT", displayName: "INPUT FLG ECAP2 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_ECAP3_TRIPOUT", displayName: "INPUT FLG ECAP3 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_ECAP4_TRIPOUT", displayName: "INPUT FLG ECAP4 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_ECAP5_TRIPOUT", displayName: "INPUT FLG ECAP5 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_ECAP6_TRIPOUT", displayName: "INPUT FLG ECAP6 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_ADCSOCA", displayName: "INPUT FLG ADCSOCA" },
	{ name: "XBAR_INPUT_FLG_ADCSOCB", displayName: "INPUT FLG ADCSOCB" },
	{ name: "XBAR_INPUT_FLG_ESMGENEVT", displayName: "INPUT FLG ESMGENEVT" },
	{ name: "XBAR_INPUT_FLG_EXTSYNCOUT", displayName: "INPUT FLG EXTSYNCOUT" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT0", displayName: "INPUT FLG WADI2OUT0" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT1", displayName: "INPUT FLG WADI2OUT1" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT2", displayName: "INPUT FLG WADI2OUT2" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT3", displayName: "INPUT FLG WADI2OUT3" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT4", displayName: "INPUT FLG WADI2OUT4" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT5", displayName: "INPUT FLG WADI2OUT5" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT6", displayName: "INPUT FLG WADI2OUT6" },
	{ name: "XBAR_INPUT_FLG_WADI2OUT7", displayName: "INPUT FLG WADI2OUT7" },
	{ name: "XBAR_INPUT_FLG_EPWM1_TRIPOUT", displayName: "INPUT FLG EPWM1 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM2_TRIPOUT", displayName: "INPUT FLG EPWM2 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM3_TRIPOUT", displayName: "INPUT FLG EPWM3 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM4_TRIPOUT", displayName: "INPUT FLG EPWM4 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM5_TRIPOUT", displayName: "INPUT FLG EPWM5 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM6_TRIPOUT", displayName: "INPUT FLG EPWM6 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM7_TRIPOUT", displayName: "INPUT FLG EPWM7 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM8_TRIPOUT", displayName: "INPUT FLG EPWM8 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM9_TRIPOUT", displayName: "INPUT FLG EPWM9 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM10_TRIPOUT", displayName: "INPUT FLG EPWM10 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM11_TRIPOUT", displayName: "INPUT FLG EPWM11 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM12_TRIPOUT", displayName: "INPUT FLG EPWM12 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM13_TRIPOUT", displayName: "INPUT FLG EPWM13 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM14_TRIPOUT", displayName: "INPUT FLG EPWM14 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM15_TRIPOUT", displayName: "INPUT FLG EPWM15 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM16_TRIPOUT", displayName: "INPUT FLG EPWM16 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM17_TRIPOUT", displayName: "INPUT FLG EPWM17 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM18_TRIPOUT", displayName: "INPUT FLG EPWM18 TRIPOUT" },
	{ name: "XBAR_INPUT_FLG_EPWM1_DEL_TRIP", displayName: "INPUT FLG EPWM1 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM2_DEL_TRIP", displayName: "INPUT FLG EPWM2 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM3_DEL_TRIP", displayName: "INPUT FLG EPWM3 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM4_DEL_TRIP", displayName: "INPUT FLG EPWM4 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM5_DEL_TRIP", displayName: "INPUT FLG EPWM5 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM6_DEL_TRIP", displayName: "INPUT FLG EPWM6 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM7_DEL_TRIP", displayName: "INPUT FLG EPWM7 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM8_DEL_TRIP", displayName: "INPUT FLG EPWM8 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM9_DEL_TRIP", displayName: "INPUT FLG EPWM9 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM10_DEL_TRIP", displayName: "INPUT FLG EPWM10 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM11_DEL_TRIP", displayName: "INPUT FLG EPWM11 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM12_DEL_TRIP", displayName: "INPUT FLG EPWM12 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM13_DEL_TRIP", displayName: "INPUT FLG EPWM13 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM14_DEL_TRIP", displayName: "INPUT FLG EPWM14 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM15_DEL_TRIP", displayName: "INPUT FLG EPWM15 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM16_DEL_TRIP", displayName: "INPUT FLG EPWM16 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM17_DEL_TRIP", displayName: "INPUT FLG EPWM17 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM18_DEL_TRIP", displayName: "INPUT FLG EPWM18 DEL TRIP" },
	{ name: "XBAR_INPUT_FLG_EPWM1_DEL_ACTIVE", displayName: "INPUT FLG EPWM1 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM2_DEL_ACTIVE", displayName: "INPUT FLG EPWM2 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM3_DEL_ACTIVE", displayName: "INPUT FLG EPWM3 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM4_DEL_ACTIVE", displayName: "INPUT FLG EPWM4 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM5_DEL_ACTIVE", displayName: "INPUT FLG EPWM5 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM6_DEL_ACTIVE", displayName: "INPUT FLG EPWM6 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM7_DEL_ACTIVE", displayName: "INPUT FLG EPWM7 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM8_DEL_ACTIVE", displayName: "INPUT FLG EPWM8 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM9_DEL_ACTIVE", displayName: "INPUT FLG EPWM9 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM10_DEL_ACTIVE", displayName: "INPUT FLG EPWM10 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM11_DEL_ACTIVE", displayName: "INPUT FLG EPWM11 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM12_DEL_ACTIVE", displayName: "INPUT FLG EPWM12 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM13_DEL_ACTIVE", displayName: "INPUT FLG EPWM13 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM14_DEL_ACTIVE", displayName: "INPUT FLG EPWM14 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM15_DEL_ACTIVE", displayName: "INPUT FLG EPWM15 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM16_DEL_ACTIVE", displayName: "INPUT FLG EPWM16 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM17_DEL_ACTIVE", displayName: "INPUT FLG EPWM17 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_EPWM18_DEL_ACTIVE", displayName: "INPUT FLG EPWM18 DEL ACTIVE" },
	{ name: "XBAR_INPUT_FLG_ETPWM1_A0_SCLK", displayName: "INPUT FLG ETPWM1 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM1_B0_SCLK", displayName: "INPUT FLG ETPWM1 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM2_A0_SCLK", displayName: "INPUT FLG ETPWM2 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM2_B0_SCLK", displayName: "INPUT FLG ETPWM2 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM3_A0_SCLK", displayName: "INPUT FLG ETPWM3 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM3_B0_SCLK", displayName: "INPUT FLG ETPWM3 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM4_A0_SCLK", displayName: "INPUT FLG ETPWM4 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM4_B0_SCLK", displayName: "INPUT FLG ETPWM4 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM5_A0_SCLK", displayName: "INPUT FLG ETPWM5 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM5_B0_SCLK", displayName: "INPUT FLG ETPWM5 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM6_A0_SCLK", displayName: "INPUT FLG ETPWM6 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM6_B0_SCLK", displayName: "INPUT FLG ETPWM6 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM7_A0_SCLK", displayName: "INPUT FLG ETPWM7 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM7_B0_SCLK", displayName: "INPUT FLG ETPWM7 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM8_A0_SCLK", displayName: "INPUT FLG ETPWM8 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM8_B0_SCLK", displayName: "INPUT FLG ETPWM8 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM9_A0_SCLK", displayName: "INPUT FLG ETPWM9 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM9_B0_SCLK", displayName: "INPUT FLG ETPWM9 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM10_A0_SCLK", displayName: "INPUT FLG ETPWM10 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM10_B0_SCLK", displayName: "INPUT FLG ETPWM10 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM11_A0_SCLK", displayName: "INPUT FLG ETPWM11 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM11_B0_SCLK", displayName: "INPUT FLG ETPWM11 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM12_A0_SCLK", displayName: "INPUT FLG ETPWM12 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM12_B0_SCLK", displayName: "INPUT FLG ETPWM12 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM13_A0_SCLK", displayName: "INPUT FLG ETPWM13 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM13_B0_SCLK", displayName: "INPUT FLG ETPWM13 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM14_A0_SCLK", displayName: "INPUT FLG ETPWM14 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM14_B0_SCLK", displayName: "INPUT FLG ETPWM14 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM15_A0_SCLK", displayName: "INPUT FLG ETPWM15 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM15_B0_SCLK", displayName: "INPUT FLG ETPWM15 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM16_A0_SCLK", displayName: "INPUT FLG ETPWM16 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM16_B0_SCLK", displayName: "INPUT FLG ETPWM16 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM17_A0_SCLK", displayName: "INPUT FLG ETPWM17 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM17_B0_SCLK", displayName: "INPUT FLG ETPWM17 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM18_A0_SCLK", displayName: "INPUT FLG ETPWM18 A0 SCLK" },
	{ name: "XBAR_INPUT_FLG_ETPWM18_B0_SCLK", displayName: "INPUT FLG ETPWM18 B0 SCLK" },
	{ name: "XBAR_INPUT_FLG_MDL1_OUTA", displayName: "INPUT FLG MDL1 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL1_OUTB", displayName: "INPUT FLG MDL1 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL2_OUTA", displayName: "INPUT FLG MDL2 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL2_OUTB", displayName: "INPUT FLG MDL2 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL3_OUTA", displayName: "INPUT FLG MDL3 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL3_OUTB", displayName: "INPUT FLG MDL3 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL4_OUTA", displayName: "INPUT FLG MDL4 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL4_OUTB", displayName: "INPUT FLG MDL4 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL5_OUTA", displayName: "INPUT FLG MDL5 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL5_OUTB", displayName: "INPUT FLG MDL5 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL6_OUTA", displayName: "INPUT FLG MDL6 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL6_OUTB", displayName: "INPUT FLG MDL6 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL7_OUTA", displayName: "INPUT FLG MDL7 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL7_OUTB", displayName: "INPUT FLG MDL7 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL8_OUTA", displayName: "INPUT FLG MDL8 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL8_OUTB", displayName: "INPUT FLG MDL8 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL9_OUTA", displayName: "INPUT FLG MDL9 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL9_OUTB", displayName: "INPUT FLG MDL9 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL10_OUTA", displayName: "INPUT FLG MDL10 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL10_OUTB", displayName: "INPUT FLG MDL10 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL11_OUTA", displayName: "INPUT FLG MDL11 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL11_OUTB", displayName: "INPUT FLG MDL11 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL12_OUTA", displayName: "INPUT FLG MDL12 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL12_OUTB", displayName: "INPUT FLG MDL12 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL13_OUTA", displayName: "INPUT FLG MDL13 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL13_OUTB", displayName: "INPUT FLG MDL13 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL14_OUTA", displayName: "INPUT FLG MDL14 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL14_OUTB", displayName: "INPUT FLG MDL14 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL15_OUTA", displayName: "INPUT FLG MDL15 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL15_OUTB", displayName: "INPUT FLG MDL15 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL16_OUTA", displayName: "INPUT FLG MDL16 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL16_OUTB", displayName: "INPUT FLG MDL16 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL17_OUTA", displayName: "INPUT FLG MDL17 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL17_OUTB", displayName: "INPUT FLG MDL17 OUTB" },
	{ name: "XBAR_INPUT_FLG_MDL18_OUTA", displayName: "INPUT FLG MDL18 OUTA" },
	{ name: "XBAR_INPUT_FLG_MDL18_OUTB", displayName: "INPUT FLG MDL18 OUTB" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT0", displayName: "INPUT FLG CLB1 OUT0" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT1", displayName: "INPUT FLG CLB1 OUT1" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT2", displayName: "INPUT FLG CLB1 OUT2" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT3", displayName: "INPUT FLG CLB1 OUT3" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT6", displayName: "INPUT FLG CLB1 OUT6" },
	{ name: "XBAR_INPUT_FLG_CLB1_OUT7", displayName: "INPUT FLG CLB1 OUT7" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT0", displayName: "INPUT FLG CLB2 OUT0" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT1", displayName: "INPUT FLG CLB2 OUT1" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT2", displayName: "INPUT FLG CLB2 OUT2" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT3", displayName: "INPUT FLG CLB2 OUT3" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT6", displayName: "INPUT FLG CLB2 OUT6" },
	{ name: "XBAR_INPUT_FLG_CLB2_OUT7", displayName: "INPUT FLG CLB2 OUT7" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT0", displayName: "INPUT FLG CLB3 OUT0" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT1", displayName: "INPUT FLG CLB3 OUT1" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT2", displayName: "INPUT FLG CLB3 OUT2" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT3", displayName: "INPUT FLG CLB3 OUT3" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT6", displayName: "INPUT FLG CLB3 OUT6" },
	{ name: "XBAR_INPUT_FLG_CLB3_OUT7", displayName: "INPUT FLG CLB3 OUT7" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT0", displayName: "INPUT FLG CLB4 OUT0" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT1", displayName: "INPUT FLG CLB4 OUT1" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT2", displayName: "INPUT FLG CLB4 OUT2" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT3", displayName: "INPUT FLG CLB4 OUT3" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT6", displayName: "INPUT FLG CLB4 OUT6" },
	{ name: "XBAR_INPUT_FLG_CLB4_OUT7", displayName: "INPUT FLG CLB4 OUT7" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT0", displayName: "INPUT FLG CLB5 OUT0" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT1", displayName: "INPUT FLG CLB5 OUT1" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT2", displayName: "INPUT FLG CLB5 OUT2" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT3", displayName: "INPUT FLG CLB5 OUT3" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT6", displayName: "INPUT FLG CLB5 OUT6" },
	{ name: "XBAR_INPUT_FLG_CLB5_OUT7", displayName: "INPUT FLG CLB5 OUT7" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT0", displayName: "INPUT FLG CLB6 OUT0" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT1", displayName: "INPUT FLG CLB6 OUT1" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT2", displayName: "INPUT FLG CLB6 OUT2" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT3", displayName: "INPUT FLG CLB6 OUT3" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT6", displayName: "INPUT FLG CLB6 OUT6" },
	{ name: "XBAR_INPUT_FLG_CLB6_OUT7", displayName: "INPUT FLG CLB6 OUT7" },
	{ name: "XBAR_INPUT_FLG_ADCA_EXTMUXSEL0", displayName: "INPUT FLG ADCA EXTMUXSEL0" },
	{ name: "XBAR_INPUT_FLG_ADCA_EXTMUXSEL1", displayName: "INPUT FLG ADCA EXTMUXSEL1" },
	{ name: "XBAR_INPUT_FLG_ADCA_EXTMUXSEL2", displayName: "INPUT FLG ADCA EXTMUXSEL2" },
	{ name: "XBAR_INPUT_FLG_ADCA_EXTMUXSEL3", displayName: "INPUT FLG ADCA EXTMUXSEL3" },
	{ name: "XBAR_INPUT_FLG_ADCB_EXTMUXSEL0", displayName: "INPUT FLG ADCB EXTMUXSEL0" },
	{ name: "XBAR_INPUT_FLG_ADCB_EXTMUXSEL1", displayName: "INPUT FLG ADCB EXTMUXSEL1" },
	{ name: "XBAR_INPUT_FLG_ADCB_EXTMUXSEL2", displayName: "INPUT FLG ADCB EXTMUXSEL2" },
	{ name: "XBAR_INPUT_FLG_ADCB_EXTMUXSEL3", displayName: "INPUT FLG ADCB EXTMUXSEL3" },
	{ name: "XBAR_INPUT_FLG_ADCC_EXTMUXSEL0", displayName: "INPUT FLG ADCC EXTMUXSEL0" },
	{ name: "XBAR_INPUT_FLG_ADCC_EXTMUXSEL1", displayName: "INPUT FLG ADCC EXTMUXSEL1" },
	{ name: "XBAR_INPUT_FLG_ADCC_EXTMUXSEL2", displayName: "INPUT FLG ADCC EXTMUXSEL2" },
	{ name: "XBAR_INPUT_FLG_ADCC_EXTMUXSEL3", displayName: "INPUT FLG ADCC EXTMUXSEL3" },
	{ name: "XBAR_INPUT_FLG_ADCD_EXTMUXSEL0", displayName: "INPUT FLG ADCD EXTMUXSEL0" },
	{ name: "XBAR_INPUT_FLG_ADCD_EXTMUXSEL1", displayName: "INPUT FLG ADCD EXTMUXSEL1" },
	{ name: "XBAR_INPUT_FLG_ADCD_EXTMUXSEL2", displayName: "INPUT FLG ADCD EXTMUXSEL2" },
	{ name: "XBAR_INPUT_FLG_ADCD_EXTMUXSEL3", displayName: "INPUT FLG ADCD EXTMUXSEL3" },
	{ name: "XBAR_INPUT_FLG_ADCE_EXTMUXSEL0", displayName: "INPUT FLG ADCE EXTMUXSEL0" },
	{ name: "XBAR_INPUT_FLG_ADCE_EXTMUXSEL1", displayName: "INPUT FLG ADCE EXTMUXSEL1" },
	{ name: "XBAR_INPUT_FLG_ADCE_EXTMUXSEL2", displayName: "INPUT FLG ADCE EXTMUXSEL2" },
	{ name: "XBAR_INPUT_FLG_ADCE_EXTMUXSEL3", displayName: "INPUT FLG ADCE EXTMUXSEL3" },
	{ name: "XBAR_INPUT_FLG_EPG1_EPGOUT0", displayName: "INPUT FLG EPG1 EPGOUT0" },
	{ name: "XBAR_INPUT_FLG_EPG1_EPGOUT1", displayName: "INPUT FLG EPG1 EPGOUT1" },
	{ name: "XBAR_INPUT_FLG_EPG1_EPGOUT2", displayName: "INPUT FLG EPG1 EPGOUT2" },
	{ name: "XBAR_INPUT_FLG_EPG1_EPGOUT3", displayName: "INPUT FLG EPG1 EPGOUT3" },
	{ name: "XBAR_INPUT_FLG_MCANA_FEVT0", displayName: "INPUT FLG MCANA FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCANA_FEVT1", displayName: "INPUT FLG MCANA FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCANA_FEVT2", displayName: "INPUT FLG MCANA FEVT2" },
	{ name: "XBAR_INPUT_FLG_MCANB_FEVT0", displayName: "INPUT FLG MCANB FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCANB_FEVT1", displayName: "INPUT FLG MCANB FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCANB_FEVT2", displayName: "INPUT FLG MCANB FEVT2" },
	{ name: "XBAR_INPUT_FLG_MCANC_FEVT0", displayName: "INPUT FLG MCANC FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCANC_FEVT1", displayName: "INPUT FLG MCANC FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCANC_FEVT2", displayName: "INPUT FLG MCANC FEVT2" },
	{ name: "XBAR_INPUT_FLG_MCAND_FEVT0", displayName: "INPUT FLG MCAND FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCAND_FEVT1", displayName: "INPUT FLG MCAND FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCAND_FEVT2", displayName: "INPUT FLG MCAND FEVT2" },
	{ name: "XBAR_INPUT_FLG_MCANE_FEVT0", displayName: "INPUT FLG MCANE FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCANE_FEVT1", displayName: "INPUT FLG MCANE FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCANE_FEVT2", displayName: "INPUT FLG MCANE FEVT2" },
	{ name: "XBAR_INPUT_FLG_MCANF_FEVT0", displayName: "INPUT FLG MCANF FEVT0" },
	{ name: "XBAR_INPUT_FLG_MCANF_FEVT1", displayName: "INPUT FLG MCANF FEVT1" },
	{ name: "XBAR_INPUT_FLG_MCANF_FEVT2", displayName: "INPUT FLG MCANF FEVT2" },
	{ name: "XBAR_INPUT_FLG_FSIRXA_TRIG_2", displayName: "INPUT FLG FSIRXA TRIG 2" },
	{ name: "XBAR_INPUT_FLG_FSIRXA_TRIG_3", displayName: "INPUT FLG FSIRXA TRIG 3" },
	{ name: "XBAR_INPUT_FLG_FSIRXB_TRIG_2", displayName: "INPUT FLG FSIRXB TRIG 2" },
	{ name: "XBAR_INPUT_FLG_FSIRXB_TRIG_3", displayName: "INPUT FLG FSIRXB TRIG 3" },
	{ name: "XBAR_INPUT_FLG_FSIRXC_TRIG_2", displayName: "INPUT FLG FSIRXC TRIG 2" },
	{ name: "XBAR_INPUT_FLG_FSIRXC_TRIG_3", displayName: "INPUT FLG FSIRXC TRIG 3" },
	{ name: "XBAR_INPUT_FLG_FSIRXD_TRIG_2", displayName: "INPUT FLG FSIRXD TRIG 2" },
	{ name: "XBAR_INPUT_FLG_FSIRXD_TRIG_3", displayName: "INPUT FLG FSIRXD TRIG 3" },
	{ name: "XBAR_INPUT_FLG_CPU1ERADEVT8", displayName: "INPUT FLG CPU1ERADEVT8" },
	{ name: "XBAR_INPUT_FLG_CPU1ERADEVT9", displayName: "INPUT FLG CPU1ERADEVT9" },
	{ name: "XBAR_INPUT_FLG_CPU1ERADEVT10", displayName: "INPUT FLG CPU1ERADEVT10" },
	{ name: "XBAR_INPUT_FLG_CPU1ERADEVT11", displayName: "INPUT FLG CPU1ERADEVT11" },
	{ name: "XBAR_INPUT_FLG_CPU2ERADEVT8", displayName: "INPUT FLG CPU2ERADEVT8" },
	{ name: "XBAR_INPUT_FLG_CPU2ERADEVT9", displayName: "INPUT FLG CPU2ERADEVT9" },
	{ name: "XBAR_INPUT_FLG_CPU2ERADEVT10", displayName: "INPUT FLG CPU2ERADEVT10" },
	{ name: "XBAR_INPUT_FLG_CPU2ERADEVT11", displayName: "INPUT FLG CPU2ERADEVT11" },
	{ name: "XBAR_INPUT_FLG_CPU3ERADEVT8", displayName: "INPUT FLG CPU3ERADEVT8" },
	{ name: "XBAR_INPUT_FLG_CPU3ERADEVT9", displayName: "INPUT FLG CPU3ERADEVT9" },
	{ name: "XBAR_INPUT_FLG_CPU3ERADEVT10", displayName: "INPUT FLG CPU3ERADEVT10" },
	{ name: "XBAR_INPUT_FLG_CPU3ERADEVT11", displayName: "INPUT FLG CPU3ERADEVT11" },
]
let XBAR_OutputStretchLength = [
	{ name: "XBAR_OUTPUT_STRETCH_16SYSCLK", displayName: "OUTPUT STRETCH 16SYSCLK" },
	{ name: "XBAR_OUTPUT_STRETCH_32SYSCLK", displayName: "OUTPUT STRETCH 32SYSCLK" },
]

// MUX Specific Configs
module.exports = {
	XBAR_MUXES: XBAR_MUXES,
	XBAR_OutputNum: XBAR_OutputNum,
	XBAR_TripNum: XBAR_TripNum,
	XBAR_AuxSigNum: XBAR_AuxSigNum,
	XBAR_InputNum: XBAR_InputNum,
	XBAR_OutputXbarInputSource: XBAR_OutputXbarInputSource,
	XBAR_EpwmXbarInputSource: XBAR_EpwmXbarInputSource,
	XBAR_ClbXbarInputSource: XBAR_ClbXbarInputSource,
	XBAR_MindbXbarInputSource: XBAR_MindbXbarInputSource,
	XBAR_IclXbarInputSource: XBAR_IclXbarInputSource,
	XBAR_InputFlag: XBAR_InputFlag,
	XBAR_OutputStretchLength: XBAR_OutputStretchLength,
}
