let ASysCtl_CMPHPMuxSelect = [
	{ name: "ASYSCTL_CMPHPMUX_SELECT_1", displayName: "CMPHPMUX select 1" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_2", displayName: "CMPHPMUX select 2" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_3", displayName: "CMPHPMUX select 3" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_4", displayName: "CMPHPMUX select 4" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_5", displayName: "CMPHPMUX select 5" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_6", displayName: "CMPHPMUX select 6" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_7", displayName: "CMPHPMUX select 7" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_8", displayName: "CMPHPMUX select 8" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_9", displayName: "CMPHPMUX select 9" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_10", displayName: "CMPHPMUX select 10" },
	{ name: "ASYSCTL_CMPHPMUX_SELECT_11", displayName: "CMPHPMUX select 11" },
]
let ASysCtl_CMPLPMuxSelect = [
	{ name: "ASYSCTL_CMPLPMUX_SELECT_1", displayName: "CMPLPMUX select 1" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_2", displayName: "CMPLPMUX select 2" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_3", displayName: "CMPLPMUX select 3" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_4", displayName: "CMPLPMUX select 4" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_5", displayName: "CMPLPMUX select 5" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_6", displayName: "CMPLPMUX select 6" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_7", displayName: "CMPLPMUX select 7" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_8", displayName: "CMPLPMUX select 8" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_9", displayName: "CMPLPMUX select 9" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_10", displayName: "CMPLPMUX select 10" },
	{ name: "ASYSCTL_CMPLPMUX_SELECT_11", displayName: "CMPLPMUX select 11" },
]
let ASysCtl_InternalNodeForADC = [
	{ name: "ASYSCTL_NO_CONN", displayName: "NO CONN" },
	{ name: "ASYSCTL_VDDCORE", displayName: "VDDCORE" },
	{ name: "ASYSCTL_VDDA", displayName: "VDDA" },
	{ name: "ASYSCTL_VSSA", displayName: "VSSA" },
	{ name: "ASYSCTL_VREFLOA", displayName: "VREFLOA" },
	{ name: "ASYSCTL_VREFLOB", displayName: "VREFLOB" },
	{ name: "ASYSCTL_CDAC1H", displayName: "CDAC1H" },
	{ name: "ASYSCTL_CDAC1L", displayName: "CDAC1L" },
	{ name: "ASYSCTL_CDAC2H", displayName: "CDAC2H" },
	{ name: "ASYSCTL_CDAC2L", displayName: "CDAC2L" },
	{ name: "ASYSCTL_CDAC3H", displayName: "CDAC3H" },
	{ name: "ASYSCTL_CDAC3L", displayName: "CDAC3L" },
	{ name: "ASYSCTL_CDAC4H", displayName: "CDAC4H" },
	{ name: "ASYSCTL_CDAC4L", displayName: "CDAC4L" },
	{ name: "ASYSCTL_CDAC5H", displayName: "CDAC5H" },
	{ name: "ASYSCTL_CDAC5L", displayName: "CDAC5L" },
	{ name: "ASYSCTL_CDAC6H", displayName: "CDAC6H" },
	{ name: "ASYSCTL_CDAC6L", displayName: "CDAC6L" },
	{ name: "ASYSCTL_CDAC7H", displayName: "CDAC7H" },
	{ name: "ASYSCTL_CDAC7L", displayName: "CDAC7L" },
	{ name: "ASYSCTL_CDAC8H", displayName: "CDAC8H" },
	{ name: "ASYSCTL_CDAC8L", displayName: "CDAC8L" },
	{ name: "ASYSCTL_CDAC9H", displayName: "CDAC9H" },
	{ name: "ASYSCTL_CDAC9L", displayName: "CDAC9L" },
	{ name: "ASYSCTL_CDAC10H", displayName: "CDAC10H" },
	{ name: "ASYSCTL_CDAC10L", displayName: "CDAC10L" },
	{ name: "ASYSCTL_CDAC11H", displayName: "CDAC11H" },
	{ name: "ASYSCTL_CDAC11L", displayName: "CDAC11L" },
	{ name: "ASYSCTL_ENZ_CALIB_GAIN_3P3", displayName: "ENZ CALIB GAIN 3P3" },
]
let AsysCtl_CMPselect = [
	{ name: "ASYSCTL_CMP1_HP_0", displayName: "CMP1 HP 0" },
	{ name: "ASYSCTL_CMP1_HP_1", displayName: "CMP1 HP 1" },
	{ name: "ASYSCTL_CMP1_HP_2", displayName: "CMP1 HP 2" },
	{ name: "ASYSCTL_CMP1_HP_3", displayName: "CMP1 HP 3" },
	{ name: "ASYSCTL_CMP1_HP_4", displayName: "CMP1 HP 4" },
	{ name: "ASYSCTL_CMP2_HP_0", displayName: "CMP2 HP 0" },
	{ name: "ASYSCTL_CMP2_HP_1", displayName: "CMP2 HP 1" },
	{ name: "ASYSCTL_CMP2_HP_2", displayName: "CMP2 HP 2" },
	{ name: "ASYSCTL_CMP2_HP_3", displayName: "CMP2 HP 3" },
	{ name: "ASYSCTL_CMP2_HP_4", displayName: "CMP2 HP 4" },
	{ name: "ASYSCTL_CMP3_HP_0", displayName: "CMP3 HP 0" },
	{ name: "ASYSCTL_CMP3_HP_1", displayName: "CMP3 HP 1" },
	{ name: "ASYSCTL_CMP3_HP_2", displayName: "CMP3 HP 2" },
	{ name: "ASYSCTL_CMP3_HP_3", displayName: "CMP3 HP 3" },
	{ name: "ASYSCTL_CMP3_HP_4", displayName: "CMP3 HP 4" },
	{ name: "ASYSCTL_CMP4_HP_0", displayName: "CMP4 HP 0" },
	{ name: "ASYSCTL_CMP4_HP_1", displayName: "CMP4 HP 1" },
	{ name: "ASYSCTL_CMP4_HP_2", displayName: "CMP4 HP 2" },
	{ name: "ASYSCTL_CMP4_HP_3", displayName: "CMP4 HP 3" },
	{ name: "ASYSCTL_CMP4_HP_4", displayName: "CMP4 HP 4" },
	{ name: "ASYSCTL_CMP5_HP_0", displayName: "CMP5 HP 0" },
	{ name: "ASYSCTL_CMP5_HP_1", displayName: "CMP5 HP 1" },
	{ name: "ASYSCTL_CMP5_HP_2", displayName: "CMP5 HP 2" },
	{ name: "ASYSCTL_CMP5_HP_3", displayName: "CMP5 HP 3" },
	{ name: "ASYSCTL_CMP5_HP_4", displayName: "CMP5 HP 4" },
	{ name: "ASYSCTL_CMP6_HP_0", displayName: "CMP6 HP 0" },
	{ name: "ASYSCTL_CMP6_HP_1", displayName: "CMP6 HP 1" },
	{ name: "ASYSCTL_CMP6_HP_2", displayName: "CMP6 HP 2" },
	{ name: "ASYSCTL_CMP6_HP_3", displayName: "CMP6 HP 3" },
	{ name: "ASYSCTL_CMP6_HP_4", displayName: "CMP6 HP 4" },
	{ name: "ASYSCTL_CMP7_HP_0", displayName: "CMP7 HP 0" },
	{ name: "ASYSCTL_CMP7_HP_1", displayName: "CMP7 HP 1" },
	{ name: "ASYSCTL_CMP7_HP_2", displayName: "CMP7 HP 2" },
	{ name: "ASYSCTL_CMP7_HP_3", displayName: "CMP7 HP 3" },
	{ name: "ASYSCTL_CMP7_HP_4", displayName: "CMP7 HP 4" },
	{ name: "ASYSCTL_CMP8_HP_0", displayName: "CMP8 HP 0" },
	{ name: "ASYSCTL_CMP8_HP_1", displayName: "CMP8 HP 1" },
	{ name: "ASYSCTL_CMP8_HP_2", displayName: "CMP8 HP 2" },
	{ name: "ASYSCTL_CMP8_HP_3", displayName: "CMP8 HP 3" },
	{ name: "ASYSCTL_CMP8_HP_4", displayName: "CMP8 HP 4" },
	{ name: "ASYSCTL_CMP9_HP_0", displayName: "CMP9 HP 0" },
	{ name: "ASYSCTL_CMP9_HP_1", displayName: "CMP9 HP 1" },
	{ name: "ASYSCTL_CMP9_HP_2", displayName: "CMP9 HP 2" },
	{ name: "ASYSCTL_CMP9_HP_3", displayName: "CMP9 HP 3" },
	{ name: "ASYSCTL_CMP9_HP_4", displayName: "CMP9 HP 4" },
	{ name: "ASYSCTL_CMP10_HP_0", displayName: "CMP10 HP 0" },
	{ name: "ASYSCTL_CMP10_HP_1", displayName: "CMP10 HP 1" },
	{ name: "ASYSCTL_CMP10_HP_2", displayName: "CMP10 HP 2" },
	{ name: "ASYSCTL_CMP10_HP_3", displayName: "CMP10 HP 3" },
	{ name: "ASYSCTL_CMP10_HP_4", displayName: "CMP10 HP 4" },
	{ name: "ASYSCTL_CMP11_HP_0", displayName: "CMP11 HP 0" },
	{ name: "ASYSCTL_CMP11_HP_1", displayName: "CMP11 HP 1" },
	{ name: "ASYSCTL_CMP11_HP_2", displayName: "CMP11 HP 2" },
	{ name: "ASYSCTL_CMP11_HP_3", displayName: "CMP11 HP 3" },
	{ name: "ASYSCTL_CMP11_HP_4", displayName: "CMP11 HP 4" },
	{ name: "ASYSCTL_CMP12_HP_0", displayName: "CMP12 HP 0" },
	{ name: "ASYSCTL_CMP12_HP_1", displayName: "CMP12 HP 1" },
	{ name: "ASYSCTL_CMP12_HP_2", displayName: "CMP12 HP 2" },
	{ name: "ASYSCTL_CMP12_HP_3", displayName: "CMP12 HP 3" },
	{ name: "ASYSCTL_CMP12_HP_4", displayName: "CMP12 HP 4" },
	{ name: "ASYSCTL_CMP1_LP_0", displayName: "CMP1 LP 0" },
	{ name: "ASYSCTL_CMP1_LP_1", displayName: "CMP1 LP 1" },
	{ name: "ASYSCTL_CMP1_LP_2", displayName: "CMP1 LP 2" },
	{ name: "ASYSCTL_CMP1_LP_3", displayName: "CMP1 LP 3" },
	{ name: "ASYSCTL_CMP1_LP_4", displayName: "CMP1 LP 4" },
	{ name: "ASYSCTL_CMP2_LP_0", displayName: "CMP2 LP 0" },
	{ name: "ASYSCTL_CMP2_LP_1", displayName: "CMP2 LP 1" },
	{ name: "ASYSCTL_CMP2_LP_2", displayName: "CMP2 LP 2" },
	{ name: "ASYSCTL_CMP2_LP_3", displayName: "CMP2 LP 3" },
	{ name: "ASYSCTL_CMP2_LP_4", displayName: "CMP2 LP 4" },
	{ name: "ASYSCTL_CMP3_LP_0", displayName: "CMP3 LP 0" },
	{ name: "ASYSCTL_CMP3_LP_1", displayName: "CMP3 LP 1" },
	{ name: "ASYSCTL_CMP3_LP_2", displayName: "CMP3 LP 2" },
	{ name: "ASYSCTL_CMP3_LP_3", displayName: "CMP3 LP 3" },
	{ name: "ASYSCTL_CMP3_LP_4", displayName: "CMP3 LP 4" },
	{ name: "ASYSCTL_CMP4_LP_0", displayName: "CMP4 LP 0" },
	{ name: "ASYSCTL_CMP4_LP_1", displayName: "CMP4 LP 1" },
	{ name: "ASYSCTL_CMP4_LP_2", displayName: "CMP4 LP 2" },
	{ name: "ASYSCTL_CMP4_LP_3", displayName: "CMP4 LP 3" },
	{ name: "ASYSCTL_CMP4_LP_4", displayName: "CMP4 LP 4" },
	{ name: "ASYSCTL_CMP5_LP_0", displayName: "CMP5 LP 0" },
	{ name: "ASYSCTL_CMP5_LP_1", displayName: "CMP5 LP 1" },
	{ name: "ASYSCTL_CMP5_LP_2", displayName: "CMP5 LP 2" },
	{ name: "ASYSCTL_CMP5_LP_3", displayName: "CMP5 LP 3" },
	{ name: "ASYSCTL_CMP5_LP_4", displayName: "CMP5 LP 4" },
	{ name: "ASYSCTL_CMP6_LP_0", displayName: "CMP6 LP 0" },
	{ name: "ASYSCTL_CMP6_LP_1", displayName: "CMP6 LP 1" },
	{ name: "ASYSCTL_CMP6_LP_2", displayName: "CMP6 LP 2" },
	{ name: "ASYSCTL_CMP6_LP_3", displayName: "CMP6 LP 3" },
	{ name: "ASYSCTL_CMP6_LP_4", displayName: "CMP6 LP 4" },
	{ name: "ASYSCTL_CMP7_LP_0", displayName: "CMP7 LP 0" },
	{ name: "ASYSCTL_CMP7_LP_1", displayName: "CMP7 LP 1" },
	{ name: "ASYSCTL_CMP7_LP_2", displayName: "CMP7 LP 2" },
	{ name: "ASYSCTL_CMP7_LP_3", displayName: "CMP7 LP 3" },
	{ name: "ASYSCTL_CMP7_LP_4", displayName: "CMP7 LP 4" },
	{ name: "ASYSCTL_CMP8_LP_0", displayName: "CMP8 LP 0" },
	{ name: "ASYSCTL_CMP8_LP_1", displayName: "CMP8 LP 1" },
	{ name: "ASYSCTL_CMP8_LP_2", displayName: "CMP8 LP 2" },
	{ name: "ASYSCTL_CMP8_LP_3", displayName: "CMP8 LP 3" },
	{ name: "ASYSCTL_CMP8_LP_4", displayName: "CMP8 LP 4" },
	{ name: "ASYSCTL_CMP9_LP_0", displayName: "CMP9 LP 0" },
	{ name: "ASYSCTL_CMP9_LP_1", displayName: "CMP9 LP 1" },
	{ name: "ASYSCTL_CMP9_LP_2", displayName: "CMP9 LP 2" },
	{ name: "ASYSCTL_CMP9_LP_3", displayName: "CMP9 LP 3" },
	{ name: "ASYSCTL_CMP9_LP_4", displayName: "CMP9 LP 4" },
	{ name: "ASYSCTL_CMP10_LP_0", displayName: "CMP10 LP 0" },
	{ name: "ASYSCTL_CMP10_LP_1", displayName: "CMP10 LP 1" },
	{ name: "ASYSCTL_CMP10_LP_2", displayName: "CMP10 LP 2" },
	{ name: "ASYSCTL_CMP10_LP_3", displayName: "CMP10 LP 3" },
	{ name: "ASYSCTL_CMP10_LP_4", displayName: "CMP10 LP 4" },
	{ name: "ASYSCTL_CMP11_LP_0", displayName: "CMP11 LP 0" },
	{ name: "ASYSCTL_CMP11_LP_1", displayName: "CMP11 LP 1" },
	{ name: "ASYSCTL_CMP11_LP_2", displayName: "CMP11 LP 2" },
	{ name: "ASYSCTL_CMP11_LP_3", displayName: "CMP11 LP 3" },
	{ name: "ASYSCTL_CMP11_LP_4", displayName: "CMP11 LP 4" },
	{ name: "ASYSCTL_CMP12_LP_0", displayName: "CMP12 LP 0" },
	{ name: "ASYSCTL_CMP12_LP_1", displayName: "CMP12 LP 1" },
	{ name: "ASYSCTL_CMP12_LP_2", displayName: "CMP12 LP 2" },
	{ name: "ASYSCTL_CMP12_LP_3", displayName: "CMP12 LP 3" },
	{ name: "ASYSCTL_CMP12_LP_4", displayName: "CMP12 LP 4" },
	{ name: "ASYSCTL_CMP1_HN_0", displayName: "CMP1 HN 0" },
	{ name: "ASYSCTL_CMP1_HN_1", displayName: "CMP1 HN 1" },
	{ name: "ASYSCTL_CMP2_HN_0", displayName: "CMP2 HN 0" },
	{ name: "ASYSCTL_CMP2_HN_1", displayName: "CMP2 HN 1" },
	{ name: "ASYSCTL_CMP3_HN_0", displayName: "CMP3 HN 0" },
	{ name: "ASYSCTL_CMP3_HN_1", displayName: "CMP3 HN 1" },
	{ name: "ASYSCTL_CMP4_HN_0", displayName: "CMP4 HN 0" },
	{ name: "ASYSCTL_CMP4_HN_1", displayName: "CMP4 HN 1" },
	{ name: "ASYSCTL_CMP5_HN_0", displayName: "CMP5 HN 0" },
	{ name: "ASYSCTL_CMP5_HN_1", displayName: "CMP5 HN 1" },
	{ name: "ASYSCTL_CMP6_HN_0", displayName: "CMP6 HN 0" },
	{ name: "ASYSCTL_CMP6_HN_1", displayName: "CMP6 HN 1" },
	{ name: "ASYSCTL_CMP7_HN_0", displayName: "CMP7 HN 0" },
	{ name: "ASYSCTL_CMP7_HN_1", displayName: "CMP7 HN 1" },
	{ name: "ASYSCTL_CMP8_HN_0", displayName: "CMP8 HN 0" },
	{ name: "ASYSCTL_CMP8_HN_1", displayName: "CMP8 HN 1" },
	{ name: "ASYSCTL_CMP9_HN_0", displayName: "CMP9 HN 0" },
	{ name: "ASYSCTL_CMP9_HN_1", displayName: "CMP9 HN 1" },
	{ name: "ASYSCTL_CMP10_HN_0", displayName: "CMP10 HN 0" },
	{ name: "ASYSCTL_CMP10_HN_1", displayName: "CMP10 HN 1" },
	{ name: "ASYSCTL_CMP11_HN_0", displayName: "CMP11 HN 0" },
	{ name: "ASYSCTL_CMP11_HN_1", displayName: "CMP11 HN 1" },
	{ name: "ASYSCTL_CMP12_HN_0", displayName: "CMP12 HN 0" },
	{ name: "ASYSCTL_CMP12_HN_1", displayName: "CMP12 HN 1" },
	{ name: "ASYSCTL_CMP1_LN_0", displayName: "CMP1 LN 0" },
	{ name: "ASYSCTL_CMP1_LN_1", displayName: "CMP1 LN 1" },
	{ name: "ASYSCTL_CMP2_LN_0", displayName: "CMP2 LN 0" },
	{ name: "ASYSCTL_CMP2_LN_1", displayName: "CMP2 LN 1" },
	{ name: "ASYSCTL_CMP3_LN_0", displayName: "CMP3 LN 0" },
	{ name: "ASYSCTL_CMP3_LN_1", displayName: "CMP3 LN 1" },
	{ name: "ASYSCTL_CMP4_LN_0", displayName: "CMP4 LN 0" },
	{ name: "ASYSCTL_CMP4_LN_1", displayName: "CMP4 LN 1" },
	{ name: "ASYSCTL_CMP5_LN_0", displayName: "CMP5 LN 0" },
	{ name: "ASYSCTL_CMP5_LN_1", displayName: "CMP5 LN 1" },
	{ name: "ASYSCTL_CMP6_LN_0", displayName: "CMP6 LN 0" },
	{ name: "ASYSCTL_CMP6_LN_1", displayName: "CMP6 LN 1" },
	{ name: "ASYSCTL_CMP7_LN_0", displayName: "CMP7 LN 0" },
	{ name: "ASYSCTL_CMP7_LN_1", displayName: "CMP7 LN 1" },
	{ name: "ASYSCTL_CMP8_LN_0", displayName: "CMP8 LN 0" },
	{ name: "ASYSCTL_CMP8_LN_1", displayName: "CMP8 LN 1" },
	{ name: "ASYSCTL_CMP9_LN_0", displayName: "CMP9 LN 0" },
	{ name: "ASYSCTL_CMP9_LN_1", displayName: "CMP9 LN 1" },
	{ name: "ASYSCTL_CMP10_LN_0", displayName: "CMP10 LN 0" },
	{ name: "ASYSCTL_CMP10_LN_1", displayName: "CMP10 LN 1" },
	{ name: "ASYSCTL_CMP11_LN_0", displayName: "CMP11 LN 0" },
	{ name: "ASYSCTL_CMP11_LN_1", displayName: "CMP11 LN 1" },
	{ name: "ASYSCTL_CMP12_LN_0", displayName: "CMP12 LN 0" },
	{ name: "ASYSCTL_CMP12_LN_1", displayName: "CMP12 LN 1" },
]
let ASYSCTL_AGPIOFILTER = [
	{ name: "ASYSCTL_AGPIOFILTER_BYPASS", displayName: "Filter bypass (min ACQPS = 90ns)" },
	{ name: "ASYSCTL_AGPIOFILTER_333OHM", displayName: "333Ohm filter (min ACQPS = 125ns)" },
	{ name: "ASYSCTL_AGPIOFILTER_500OHM", displayName: "500 Ohm filter (min ACQPS = 160ns)" },
	{ name: "ASYSCTL_AGPIOFILTER_1000OHM", displayName: "1KOhm filter  (min ACQPS = 230ns)" },
]
let ASYSCTL_VREFHI = [
	{ name: "ASYSCTL_VREFHIA", displayName: "VREFHIA" },
	{ name: "ASYSCTL_VREFHIB", displayName: "VREFHIB" },
	{ name: "ASYSCTL_VREFHIC", displayName: "VREFHIC" },
]
let ASYSCTL_CMPHNMUX_SELECT = [
	{ name: "ASYSCTL_CMPHNMUX_SELECT_1", displayName: "CMPHNMUX select 1" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_2", displayName: "CMPHNMUX select 2" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_3", displayName: "CMPHNMUX select 3" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_4", displayName: "CMPHNMUX select 4" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_5", displayName: "CMPHNMUX select 5" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_6", displayName: "CMPHNMUX select 6" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_7", displayName: "CMPHNMUX select 7" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_8", displayName: "CMPHNMUX select 8" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_9", displayName: "CMPHNMUX select 9" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_10", displayName: "CMPHNMUX select 10" },
	{ name: "ASYSCTL_CMPHNMUX_SELECT_11", displayName: "CMPHNMUX select 11" },
]
let ASYSCTL_CMPLNMUX_SELECT = [
	{ name: "ASYSCTL_CMPLNMUX_SELECT_1", displayName: "CMPLNMUX select 1" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_2", displayName: "CMPLNMUX select 2" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_3", displayName: "CMPLNMUX select 3" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_4", displayName: "CMPLNMUX select 4" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_5", displayName: "CMPLNMUX select 5" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_6", displayName: "CMPLNMUX select 6" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_7", displayName: "CMPLNMUX select 7" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_8", displayName: "CMPLNMUX select 8" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_9", displayName: "CMPLNMUX select 9" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_10", displayName: "CMPLNMUX select 10" },
	{ name: "ASYSCTL_CMPLNMUX_SELECT_11", displayName: "CMPLNMUX select 11" },
]
module.exports = {
	ASysCtl_CMPHPMuxSelect: ASysCtl_CMPHPMuxSelect,
	ASysCtl_CMPLPMuxSelect: ASysCtl_CMPLPMuxSelect,
	ASysCtl_InternalNodeForADC: ASysCtl_InternalNodeForADC,
	AsysCtl_CMPselect: AsysCtl_CMPselect,
	ASYSCTL_AGPIOFILTER: ASYSCTL_AGPIOFILTER,
	ASYSCTL_VREFHI: ASYSCTL_VREFHI,
	ASYSCTL_CMPHNMUX_SELECT: ASYSCTL_CMPHNMUX_SELECT,
	ASYSCTL_CMPLNMUX_SELECT: ASYSCTL_CMPLNMUX_SELECT,
}
