let interrupts = [
	{ int_define_name: "INT_CPU_OVF", int_channel_number: "0", int_description: "C29 CPU Overflow Interrupt" },
	{ int_define_name: "INT_CPU_UVF", int_channel_number: "1", int_description: "C29 CPU Underflow Interrupt" },
	{ int_define_name: "INT_CPU_DOV", int_channel_number: "2", int_description: "C29 CPU ? Interrupt" },
	{ int_define_name: "INT_WD", int_channel_number: "3", int_description: "Watchdog interrupt" },
	{ int_define_name: "INT_ERAD", int_channel_number: "4", int_description: "ERAD Interrupt" },
	{ int_define_name: "INT_DLT", int_channel_number: "5", int_description: "DLT Interrupt" },
	{ int_define_name: "INT_TIMER0", int_channel_number: "6", int_description: "Timer 0 Interrupt" },
	{ int_define_name: "INT_TIMER1", int_channel_number: "7", int_description: "Timer 1 Interrupt" },
	{ int_define_name: "INT_TIMER2", int_channel_number: "8", int_description: "Timer 2 Interrupt" },
	{ int_define_name: "INT_DEBUGSS", int_channel_number: "9", int_description: "Debug Interrupt" },
	{ int_define_name: "INT_ESM_LOWPRI", int_channel_number: "10", int_description: "ESM CPUx Low Priority Interrupt" },
	{ int_define_name: "INT_ESM_PARITYERR", int_channel_number: "11", int_description: "ESM Parity Error Interrupt" },
	{ int_define_name: "INT_IPC_1_1", int_channel_number: "12", int_description: "" },
	{ int_define_name: "INT_IPC_1_2", int_channel_number: "13", int_description: "" },
	{ int_define_name: "INT_IPC_1_3", int_channel_number: "14", int_description: "" },
	{ int_define_name: "INT_IPC_1_4", int_channel_number: "15", int_description: "" },
	{ int_define_name: "INT_IPC_2_1", int_channel_number: "16", int_description: "" },
	{ int_define_name: "INT_IPC_2_2", int_channel_number: "17", int_description: "" },
	{ int_define_name: "INT_IPC_2_3", int_channel_number: "18", int_description: "" },
	{ int_define_name: "INT_IPC_2_4", int_channel_number: "19", int_description: "" },
	{ int_define_name: "INT_IPC_HSM_RACK", int_channel_number: "20", int_description: "" },
	{ int_define_name: "INT_IPC_HSM_WDONE", int_channel_number: "21", int_description: "" },
	{ int_define_name: "INT_DTHE_TRNG", int_channel_number: "26", int_description: "TRNG Interrupt" },
	{ int_define_name: "INT_DTHE_PKAE", int_channel_number: "27", int_description: "PKAE Interrupt" },
	{ int_define_name: "INT_DTHE_SHA_S", int_channel_number: "28", int_description: "SHA_S Interrupt" },
	{ int_define_name: "INT_DTHE_SHA_P", int_channel_number: "29", int_description: "SHA_P Interrupt" },
	{ int_define_name: "INT_DTHE_AES_S", int_channel_number: "30", int_description: "AES_S Interrupt" },
	{ int_define_name: "INT_DTHE_AES_P", int_channel_number: "31", int_description: "AES_P Interrupt" },
	{ int_define_name: "INT_DTHE_SM3", int_channel_number: "32", int_description: "SM3 Interrupt" },
	{ int_define_name: "INT_DTHE_SM4", int_channel_number: "33", int_description: "SM4 Interrupt" },
	{ int_define_name: "INT_FLC1", int_channel_number: "34", int_description: "Flash Controller Interrupt 1" },
	{ int_define_name: "INT_FLC2", int_channel_number: "35", int_description: "Flash Controller Interrupt 2" },
	{ int_define_name: "INT_EPWM1", int_channel_number: "36", int_description: "EPWM1 Interrupt" },
	{ int_define_name: "INT_EPWM1_TZ", int_channel_number: "37", int_description: "EPWM1 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM2", int_channel_number: "38", int_description: "EPWM2 Interrupt" },
	{ int_define_name: "INT_EPWM2_TZ", int_channel_number: "39", int_description: "EPWM2 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM3", int_channel_number: "40", int_description: "EPWM3 Interrupt" },
	{ int_define_name: "INT_EPWM3_TZ", int_channel_number: "41", int_description: "EPWM3 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM4", int_channel_number: "42", int_description: "EPWM4 Interrupt" },
	{ int_define_name: "INT_EPWM4_TZ", int_channel_number: "43", int_description: "EPWM4 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM5", int_channel_number: "44", int_description: "EPWM5 Interrupt" },
	{ int_define_name: "INT_EPWM5_TZ", int_channel_number: "45", int_description: "EPWM5 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM6", int_channel_number: "46", int_description: "EPWM6 Interrupt" },
	{ int_define_name: "INT_EPWM6_TZ", int_channel_number: "47", int_description: "EPWM6 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM7", int_channel_number: "48", int_description: "EPWM7 Interrupt" },
	{ int_define_name: "INT_EPWM7_TZ", int_channel_number: "49", int_description: "EPWM7 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM8", int_channel_number: "50", int_description: "EPWM8 Interrupt" },
	{ int_define_name: "INT_EPWM8_TZ", int_channel_number: "51", int_description: "EPWM8 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM9", int_channel_number: "52", int_description: "EPWM9 Interrupt" },
	{ int_define_name: "INT_EPWM9_TZ", int_channel_number: "53", int_description: "EPWM9 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM10", int_channel_number: "54", int_description: "EPWM10 Interrupt" },
	{ int_define_name: "INT_EPWM10_TZ", int_channel_number: "55", int_description: "EPWM10 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM11", int_channel_number: "56", int_description: "EPWM11 Interrupt" },
	{ int_define_name: "INT_EPWM11_TZ", int_channel_number: "57", int_description: "EPWM11 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM12", int_channel_number: "58", int_description: "EPWM12 Interrupt" },
	{ int_define_name: "INT_EPWM12_TZ", int_channel_number: "59", int_description: "EPWM12 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM13", int_channel_number: "60", int_description: "EPWM13 Interrupt" },
	{ int_define_name: "INT_EPWM13_TZ", int_channel_number: "61", int_description: "EPWM13 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM14", int_channel_number: "62", int_description: "EPWM14 Interrupt" },
	{ int_define_name: "INT_EPWM14_TZ", int_channel_number: "63", int_description: "EPWM14 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM15", int_channel_number: "64", int_description: "EPWM15 Interrupt" },
	{ int_define_name: "INT_EPWM15_TZ", int_channel_number: "65", int_description: "EPWM15 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM16", int_channel_number: "66", int_description: "EPWM16 Interrupt" },
	{ int_define_name: "INT_EPWM16_TZ", int_channel_number: "67", int_description: "EPWM16 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM17", int_channel_number: "68", int_description: "EPWM17 Interrupt" },
	{ int_define_name: "INT_EPWM17_TZ", int_channel_number: "69", int_description: "EPWM17 Trip Zone Interrupt" },
	{ int_define_name: "INT_EPWM18", int_channel_number: "70", int_description: "EPWM18 Interrupt" },
	{ int_define_name: "INT_EPWM18_TZ", int_channel_number: "71", int_description: "EPWM18 Trip Zone Interrupt" },
	{ int_define_name: "INT_EQEP1", int_channel_number: "72", int_description: "EQEP1 Interrupt" },
	{ int_define_name: "INT_EQEP2", int_channel_number: "73", int_description: "EQEP2 Interrupt" },
	{ int_define_name: "INT_EQEP3", int_channel_number: "74", int_description: "EQEP3 Interrupt" },
	{ int_define_name: "INT_EQEP4", int_channel_number: "75", int_description: "EQEP4 Interrupt" },
	{ int_define_name: "INT_EQEP5", int_channel_number: "76", int_description: "EQEP5 Interrupt" },
	{ int_define_name: "INT_EQEP6", int_channel_number: "77", int_description: "EQEP6 Interrupt" },
	{ int_define_name: "INT_ECAP1", int_channel_number: "78", int_description: "ECAP1 Interrupt" },
	{ int_define_name: "INT_ECAP2", int_channel_number: "79", int_description: "ECAP2 Interrupt" },
	{ int_define_name: "INT_ECAP3", int_channel_number: "80", int_description: "ECAP3 Interrupt" },
	{ int_define_name: "INT_ECAP4", int_channel_number: "81", int_description: "ECAP4 Interrupt" },
	{ int_define_name: "INT_ECAP5", int_channel_number: "82", int_description: "ECAP5 Interrupt" },
	{ int_define_name: "INT_HRCAP5", int_channel_number: "83", int_description: "HRCAP5 Interrupt" },
	{ int_define_name: "INT_ECAP6", int_channel_number: "84", int_description: "ECAP6 Interrupt" },
	{ int_define_name: "INT_HRCAP6", int_channel_number: "85", int_description: "HRCAP6 Interrupt" },
	{ int_define_name: "INT_ADCA_EVT", int_channel_number: "86", int_description: "ADCA Event Interrupt" },
	{ int_define_name: "INT_ADCA1", int_channel_number: "87", int_description: "ADCA Interrupt 1" },
	{ int_define_name: "INT_ADCA2", int_channel_number: "88", int_description: "ADCA Interrupt 2" },
	{ int_define_name: "INT_ADCA3", int_channel_number: "89", int_description: "ADCA Interrupt 3" },
	{ int_define_name: "INT_ADCA4", int_channel_number: "90", int_description: "ADCA Interrupt 4" },
	{ int_define_name: "INT_ADCB_EVT", int_channel_number: "91", int_description: "ADCB Event Interrupt" },
	{ int_define_name: "INT_ADCB1", int_channel_number: "92", int_description: "ADCB Interrupt 1" },
	{ int_define_name: "INT_ADCB2", int_channel_number: "93", int_description: "ADCB Interrupt 2" },
	{ int_define_name: "INT_ADCB3", int_channel_number: "94", int_description: "ADCB Interrupt 3" },
	{ int_define_name: "INT_ADCB4", int_channel_number: "95", int_description: "ADCB Interrupt 4" },
	{ int_define_name: "INT_ADCC_EVT", int_channel_number: "96", int_description: "ADCC Event Interrupt" },
	{ int_define_name: "INT_ADCC1", int_channel_number: "97", int_description: "ADCC Interrupt 1" },
	{ int_define_name: "INT_ADCC2", int_channel_number: "98", int_description: "ADCC Interrupt 2" },
	{ int_define_name: "INT_ADCC3", int_channel_number: "99", int_description: "ADCC Interrupt 3" },
	{ int_define_name: "INT_ADCC4", int_channel_number: "100", int_description: "ADCC Interrupt 4" },
	{ int_define_name: "INT_ADCD_EVT", int_channel_number: "101", int_description: "ADCD Event Interrupt" },
	{ int_define_name: "INT_ADCD1", int_channel_number: "102", int_description: "ADCD Interrupt 1" },
	{ int_define_name: "INT_ADCD2", int_channel_number: "103", int_description: "ADCD Interrupt 2" },
	{ int_define_name: "INT_ADCD3", int_channel_number: "104", int_description: "ADCD Interrupt 3" },
	{ int_define_name: "INT_ADCD4", int_channel_number: "105", int_description: "ADCD Interrupt 4" },
	{ int_define_name: "INT_ADCE_EVT", int_channel_number: "106", int_description: "ADCE Event Interrupt" },
	{ int_define_name: "INT_ADCE1", int_channel_number: "107", int_description: "ADCE Interrupt 1" },
	{ int_define_name: "INT_ADCE2", int_channel_number: "108", int_description: "ADCE Interrupt 2" },
	{ int_define_name: "INT_ADCE3", int_channel_number: "109", int_description: "ADCE Interrupt 3" },
	{ int_define_name: "INT_ADCE4", int_channel_number: "110", int_description: "ADCE Interrupt 4" },
	{ int_define_name: "INT_SD1_ERR", int_channel_number: "112", int_description: "SDFM 1 Error Interrupt" },
	{ int_define_name: "INT_SD1_FLT1_DR", int_channel_number: "113", int_description: "SDFM 1 Filter 1 Interrupt" },
	{ int_define_name: "INT_SD1_FLT2_DR", int_channel_number: "114", int_description: "SDFM 1 Filter 2 Interrupt" },
	{ int_define_name: "INT_SD1_FLT3_DR", int_channel_number: "115", int_description: "SDFM 1 Filter 3 Interrupt" },
	{ int_define_name: "INT_SD1_FLT4_DR", int_channel_number: "116", int_description: "SDFM 1 Filter 4 Interrupt" },
	{ int_define_name: "INT_SD2_ERR", int_channel_number: "117", int_description: "SDFM 1 Error Interrupt" },
	{ int_define_name: "INT_SD2_FLT1_DR", int_channel_number: "118", int_description: "SDFM 1 Filter 1 Interrupt" },
	{ int_define_name: "INT_SD2_FLT2_DR", int_channel_number: "119", int_description: "SDFM 1 Filter 2 Interrupt" },
	{ int_define_name: "INT_SD2_FLT3_DR", int_channel_number: "120", int_description: "SDFM 1 Filter 3 Interrupt" },
	{ int_define_name: "INT_SD2_FLT4_DR", int_channel_number: "121", int_description: "SDFM 1 Filter 4 Interrupt" },
	{ int_define_name: "INT_SD3_ERR", int_channel_number: "122", int_description: "SDFM 1 Error Interrupt" },
	{ int_define_name: "INT_SD3_FLT1_DR", int_channel_number: "123", int_description: "SDFM 1 Filter 1 Interrupt" },
	{ int_define_name: "INT_SD3_FLT2_DR", int_channel_number: "124", int_description: "SDFM 1 Filter 2 Interrupt" },
	{ int_define_name: "INT_SD3_FLT3_DR", int_channel_number: "125", int_description: "SDFM 1 Filter 3 Interrupt" },
	{ int_define_name: "INT_SD3_FLT4_DR", int_channel_number: "126", int_description: "SDFM 1 Filter 4 Interrupt" },
	{ int_define_name: "INT_SD4_ERR", int_channel_number: "127", int_description: "SDFM 1 Error Interrupt" },
	{ int_define_name: "INT_SD4_FLT1_DR", int_channel_number: "128", int_description: "SDFM 1 Filter 1 Interrupt" },
	{ int_define_name: "INT_SD4_FLT2_DR", int_channel_number: "129", int_description: "SDFM 1 Filter 2 Interrupt" },
	{ int_define_name: "INT_SD4_FLT3_DR", int_channel_number: "130", int_description: "SDFM 1 Filter 3 Interrupt" },
	{ int_define_name: "INT_SD4_FLT4_DR", int_channel_number: "131", int_description: "SDFM 1 Filter 4 Interrupt" },
	{ int_define_name: "INT_CLB1", int_channel_number: "132", int_description: "CLB1 Interrupt" },
	{ int_define_name: "INT_CLB2", int_channel_number: "133", int_description: "CLB2 Interrupt" },
	{ int_define_name: "INT_CLB3", int_channel_number: "134", int_description: "CLB3 Interrupt" },
	{ int_define_name: "INT_CLB4", int_channel_number: "135", int_description: "CLB4 Interrupt" },
	{ int_define_name: "INT_CLB5", int_channel_number: "136", int_description: "CLB5 Interrupt" },
	{ int_define_name: "INT_CLB6", int_channel_number: "137", int_description: "CLB6 Interrupt" },
	{ int_define_name: "INT_UARTA", int_channel_number: "138", int_description: "UARTA Interrupt" },
	{ int_define_name: "INT_UARTB", int_channel_number: "139", int_description: "UARTB Interrupt" },
	{ int_define_name: "INT_UARTC", int_channel_number: "140", int_description: "UARTC Interrupt" },
	{ int_define_name: "INT_UARTD", int_channel_number: "141", int_description: "UARTD Interrupt" },
	{ int_define_name: "INT_UARTE", int_channel_number: "142", int_description: "UARTE Interrupt" },
	{ int_define_name: "INT_UARTF", int_channel_number: "143", int_description: "UARTF Interrupt" },
	{ int_define_name: "INT_LINA_0", int_channel_number: "144", int_description: "LINA Interrupt 0" },
	{ int_define_name: "INT_LINA_1", int_channel_number: "145", int_description: "LINA Interrupt 1" },
	{ int_define_name: "INT_LINB_0", int_channel_number: "146", int_description: "LINB Interrupt 0" },
	{ int_define_name: "INT_LINB_1", int_channel_number: "147", int_description: "LINB Interrupt 1" },
	{ int_define_name: "INT_PMBUSA", int_channel_number: "148", int_description: "PMBUSA Interrupt" },
	{ int_define_name: "INT_I2CA", int_channel_number: "149", int_description: "I2CA Interrupt 1" },
	{ int_define_name: "INT_I2CA_FIFO", int_channel_number: "150", int_description: "I2CA Interrupt 2" },
	{ int_define_name: "INT_I2CB", int_channel_number: "151", int_description: "I2CB Interrupt 1" },
	{ int_define_name: "INT_I2CB_FIFO", int_channel_number: "152", int_description: "I2CB Interrupt 2" },
	{ int_define_name: "INT_SPIA_TX", int_channel_number: "153", int_description: "SPIA TX Interrupt" },
	{ int_define_name: "INT_SPIA_RX", int_channel_number: "154", int_description: "SPIA RX Interrupt" },
	{ int_define_name: "INT_SPIB_TX", int_channel_number: "155", int_description: "SPIB TX Interrupt" },
	{ int_define_name: "INT_SPIB_RX", int_channel_number: "156", int_description: "SPIB RX Interrupt" },
	{ int_define_name: "INT_SPIC_TX", int_channel_number: "157", int_description: "SPIC TX Interrupt" },
	{ int_define_name: "INT_SPIC_RX", int_channel_number: "158", int_description: "SPIC RX Interrupt" },
	{ int_define_name: "INT_SPID_TX", int_channel_number: "159", int_description: "SPID TX Interrupt" },
	{ int_define_name: "INT_SPID_RX", int_channel_number: "160", int_description: "SPID RX Interrupt" },
	{ int_define_name: "INT_SPIE_TX", int_channel_number: "161", int_description: "SPIE TX Interrupt" },
	{ int_define_name: "INT_SPIE_RX", int_channel_number: "162", int_description: "SPIE RX Interrupt" },
	{ int_define_name: "INT_FSITXA1", int_channel_number: "163", int_description: "FSITXA Interrupt 1" },
	{ int_define_name: "INT_FSITXA2", int_channel_number: "164", int_description: "FSITXA Interrupt 2" },
	{ int_define_name: "INT_FSITXB1", int_channel_number: "165", int_description: "FSITXB Interrupt 1" },
	{ int_define_name: "INT_FSITXB2", int_channel_number: "166", int_description: "FSITXB Interrupt 2" },
	{ int_define_name: "INT_FSITXC1", int_channel_number: "167", int_description: "FSITXC Interrupt 1" },
	{ int_define_name: "INT_FSITXC2", int_channel_number: "168", int_description: "FSITXC Interrupt 2" },
	{ int_define_name: "INT_FSITXD1", int_channel_number: "169", int_description: "FSITXD Interrupt 1" },
	{ int_define_name: "INT_FSITXD2", int_channel_number: "170", int_description: "FSITXD Interrupt 2" },
	{ int_define_name: "INT_FSIRXA1", int_channel_number: "171", int_description: "FSIRXA Interrupt 1" },
	{ int_define_name: "INT_FSIRXA2", int_channel_number: "172", int_description: "FSIRXA Interrupt 2" },
	{ int_define_name: "INT_FSIRXB1", int_channel_number: "173", int_description: "FSIRXB Interrupt 1" },
	{ int_define_name: "INT_FSIRXB2", int_channel_number: "174", int_description: "FSIRXB Interrupt 2" },
	{ int_define_name: "INT_FSIRXC1", int_channel_number: "175", int_description: "FSIRXC Interrupt 1" },
	{ int_define_name: "INT_FSIRXC2", int_channel_number: "176", int_description: "FSIRXC Interrupt 2" },
	{ int_define_name: "INT_FSIRXD1", int_channel_number: "177", int_description: "FSIRXD Interrupt 1" },
	{ int_define_name: "INT_FSIRXD2", int_channel_number: "178", int_description: "FSIRXD Interrupt 2" },
	{ int_define_name: "INT_SENT1", int_channel_number: "179", int_description: "SENT1 Interrupt" },
	{ int_define_name: "INT_SENT2", int_channel_number: "180", int_description: "SENT2 Interrupt" },
	{ int_define_name: "INT_SENT3", int_channel_number: "181", int_description: "SENT3 Interrupt" },
	{ int_define_name: "INT_SENT4", int_channel_number: "182", int_description: "SENT4 Interrupt" },
	{ int_define_name: "INT_SENT5", int_channel_number: "183", int_description: "SENT5 Interrupt" },
	{ int_define_name: "INT_SENT6", int_channel_number: "184", int_description: "SENT6 Interrupt" },
	{ int_define_name: "INT_MCANA_WAKE", int_channel_number: "186", int_description: "MCANA Wakeup Interrupt" },
	{ int_define_name: "INT_MCANA_1", int_channel_number: "187", int_description: "MCANA Interrupt 1" },
	{ int_define_name: "INT_MCANA_0", int_channel_number: "188", int_description: "MCANA Interrupt 0" },
	{ int_define_name: "INT_MCANB_WAKE", int_channel_number: "190", int_description: "MCANB Wakeup Interrupt" },
	{ int_define_name: "INT_MCANB_1", int_channel_number: "191", int_description: "MCANB Interrupt 1" },
	{ int_define_name: "INT_MCANB_0", int_channel_number: "192", int_description: "MCANB Interrupt 0" },
	{ int_define_name: "INT_MCANC_WAKE", int_channel_number: "194", int_description: "MCANC Wakeup Interrupt" },
	{ int_define_name: "INT_MCANC_1", int_channel_number: "195", int_description: "MCANC Interrupt 1" },
	{ int_define_name: "INT_MCANC_0", int_channel_number: "196", int_description: "MCANC Interrupt 0" },
	{ int_define_name: "INT_MCAND_WAKE", int_channel_number: "198", int_description: "MCAND Wakeup Interrupt" },
	{ int_define_name: "INT_MCAND_1", int_channel_number: "199", int_description: "MCAND Interrupt 1" },
	{ int_define_name: "INT_MCAND_0", int_channel_number: "200", int_description: "MCAND Interrupt 0" },
	{ int_define_name: "INT_MCANE_WAKE", int_channel_number: "202", int_description: "MCANE Wakeup Interrupt" },
	{ int_define_name: "INT_MCANE_1", int_channel_number: "203", int_description: "MCANE Interrupt 1" },
	{ int_define_name: "INT_MCANE_0", int_channel_number: "204", int_description: "MCANE Interrupt 0" },
	{ int_define_name: "INT_MCANF_WAKE", int_channel_number: "206", int_description: "MCANF Wakeup Interrupt" },
	{ int_define_name: "INT_MCANF_1", int_channel_number: "207", int_description: "MCANF Interrupt 1" },
	{ int_define_name: "INT_MCANF_0", int_channel_number: "208", int_description: "MCANF Interrupt 0" },
	{ int_define_name: "INT_ECAT", int_channel_number: "209", int_description: "Ethercat Main Interrupt" },
	{ int_define_name: "INT_ECATSYNC0", int_channel_number: "210", int_description: "Ethercat SYNC0 Interrupt" },
	{ int_define_name: "INT_ECATSYNC1", int_channel_number: "211", int_description: "Ethercat SYNC1 Interrupt" },
	{ int_define_name: "INT_ECATRST", int_channel_number: "212", int_description: "Ethercat Reset Interrupt" },
	{ int_define_name: "INT_RTDMA1CH1", int_channel_number: "213", int_description: "RTDMA1 Channel 1 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH2", int_channel_number: "214", int_description: "RTDMA1 Channel 2 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH3", int_channel_number: "215", int_description: "RTDMA1 Channel 3 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH4", int_channel_number: "216", int_description: "RTDMA1 Channel 4 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH5", int_channel_number: "217", int_description: "RTDMA1 Channel 5 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH6", int_channel_number: "218", int_description: "RTDMA1 Channel 6 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH7", int_channel_number: "219", int_description: "RTDMA1 Channel 7 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH8", int_channel_number: "220", int_description: "RTDMA1 Channel 8 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH9", int_channel_number: "221", int_description: "RTDMA1 Channel 9 Interrupt" },
	{ int_define_name: "INT_RTDMA1CH10", int_channel_number: "222", int_description: "RTDMA1 Channel 10 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH1", int_channel_number: "223", int_description: "RTDMA2 Channel 1 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH2", int_channel_number: "224", int_description: "RTDMA2 Channel 2 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH3", int_channel_number: "225", int_description: "RTDMA2 Channel 3 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH4", int_channel_number: "226", int_description: "RTDMA2 Channel 4 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH5", int_channel_number: "227", int_description: "RTDMA2 Channel 5 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH6", int_channel_number: "228", int_description: "RTDMA2 Channel 6 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH7", int_channel_number: "229", int_description: "RTDMA2 Channel 7 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH8", int_channel_number: "230", int_description: "RTDMA2 Channel 8 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH9", int_channel_number: "231", int_description: "RTDMA2 Channel 9 Interrupt" },
	{ int_define_name: "INT_RTDMA2CH10", int_channel_number: "232", int_description: "RTDMA2 Channel 10 Interrupt" },
	{ int_define_name: "INT_WADI1", int_channel_number: "233", int_description: "WADI1 Interrupt" },
	{ int_define_name: "INT_WADI2", int_channel_number: "234", int_description: "WADI2 Interrupt" },
	{ int_define_name: "INT_XINT1", int_channel_number: "235", int_description: "XINT1 Interrupt" },
	{ int_define_name: "INT_XINT2", int_channel_number: "236", int_description: "XINT2 Interrupt" },
	{ int_define_name: "INT_XINT3", int_channel_number: "237", int_description: "XINT3 Interrupt" },
	{ int_define_name: "INT_XINT4", int_channel_number: "238", int_description: "XINT4 Interrupt" },
	{ int_define_name: "INT_XINT5", int_channel_number: "239", int_description: "XINT5 Interrupt" },
	{ int_define_name: "INT_DCC1", int_channel_number: "240", int_description: "DCC1 Interrupt" },
	{ int_define_name: "INT_DCC2", int_channel_number: "241", int_description: "DCC2 Interrupt" },
	{ int_define_name: "INT_DCC3", int_channel_number: "242", int_description: "DCC3 Interrupt" },
	{ int_define_name: "INT_LPM_WAKE", int_channel_number: "243", int_description: "LPM Wakeup Interrupt" },
	{ int_define_name: "INT_SW12", int_channel_number: "244", int_description: "Software Interrupt 12" },
	{ int_define_name: "INT_SW11", int_channel_number: "245", int_description: "Software Interrupt 11" },
	{ int_define_name: "INT_SW10", int_channel_number: "246", int_description: "Software Interrupt 10" },
	{ int_define_name: "INT_SW9", int_channel_number: "247", int_description: "Software Interrupt 9" },
	{ int_define_name: "INT_SW8", int_channel_number: "248", int_description: "Software Interrupt 8" },
	{ int_define_name: "INT_SW7", int_channel_number: "249", int_description: "Software Interrupt 7" },
	{ int_define_name: "INT_SW6", int_channel_number: "250", int_description: "Software Interrupt 6" },
	{ int_define_name: "INT_SW5", int_channel_number: "251", int_description: "Software Interrupt 5" },
	{ int_define_name: "INT_SW4", int_channel_number: "252", int_description: "Software Interrupt 4" },
	{ int_define_name: "INT_SW3", int_channel_number: "253", int_description: "Software Interrupt 3" },
	{ int_define_name: "INT_SW2", int_channel_number: "254", int_description: "Software Interrupt 2" },
	{ int_define_name: "INT_SW1", int_channel_number: "255", int_description: "Software Interrupt 1" },
	{ int_define_name: "INT_NMI", int_channel_number: "1024", int_description: "" },
];
module.exports = {
	interrupts: interrupts,
}
