let DCC_Count1ClockSource = [
	{ name: "DCC_COUNT1SRC_PLL", displayName: "Direct output of SYSPLL CLKOUT" },
	{ name: "DCC_COUNT1SRC_FLC1_FCLK", displayName: "FCLK (divided clock) output from Flash Controller 1" },
	{ name: "DCC_COUNT1SRC_INTOSC1", displayName: "Internal Oscillator1 Output Clock" },
	{ name: "DCC_COUNT1SRC_INTOSC2", displayName: "Internal Oscillator2 Output Clock" },
	{ name: "DCC_COUNT1SRC_ECATPHYCLK", displayName: "Ethercat PHY Clock" },
	{ name: "DCC_COUNT1SRC_CPU1_CLOCK", displayName: "CPU1 Clock" },
	{ name: "DCC_COUNT1SRC_CPU2_CLOCK", displayName: "CPU2 Clock" },
	{ name: "DCC_COUNT1SRC_RTDMA_CLOCK", displayName: "RTDMA Clock" },
	{ name: "DCC_COUNT1SRC_INPUTXBAR1_INPUT15", displayName: "Input 15 of INPUTXBAR1" },
	{ name: "DCC_COUNT1SRC_AUXCLKIN", displayName: "Auxiliary Clock input" },
	{ name: "DCC_COUNT1SRC_EPWMCLK", displayName: "Clock input to EPWM module" },
	{ name: "DCC_COUNT1SRC_ADCCLK", displayName: "ADC conversion clock" },
	{ name: "DCC_COUNT1SRC_WDCLK", displayName: "Watchdog clock after dividers" },
	{ name: "DCC_COUNT1SRC_FLC2_FCLK", displayName: "FCLK (divided clock) output from Flash Controller 2" },
	{ name: "DCC_COUNT1SRC_CPU3_CLOCK", displayName: "CPU3 Clock" },
	{ name: "DCC_COUNT1SRC_INPUTXBAR1_INPUT11", displayName: "Input 11 of INPUTXBAR" },
	{ name: "DCC_COUNT1SRC_INPUTXBAR1_INPUT12", displayName: "Input 12 of INPUTXBAR" },
	{ name: "DCC_COUNT1SRC_MCANA", displayName: "MCANA Bit Clock" },
	{ name: "DCC_COUNT1SRC_MCANB", displayName: "MCANB Bit Clock" },
	{ name: "DCC_COUNT1SRC_MCANC", displayName: "MCANC Bit Clock" },
	{ name: "DCC_COUNT1SRC_MCAND", displayName: "MCAND Bit Clock" },
	{ name: "DCC_COUNT1SRC_MCANE", displayName: "MCANE Bit Clock" },
	{ name: "DCC_COUNT1SRC_MCANF", displayName: "MCANF Bit Clock" },
	{ name: "DCC_COUNT1SRC_ESMCLK", displayName: "ESM Clock" },
]
let DCC_Count0ClockSource = [
	{ name: "DCC_COUNT0SRC_XTAL", displayName: "Crystal Oscillator output" },
	{ name: "DCC_COUNT0SRC_INTOSC1", displayName: "Internal Oscillator1 output" },
	{ name: "DCC_COUNT0SRC_INTOSC2", displayName: "Internal Oscillator2 output" },
	{ name: "DCC_COUNT0SRC_TCK", displayName: "TCK pin input" },
	{ name: "DCC_COUNT0SRC_CPU1_CLOCK", displayName: "CPU1 Clock" },
	{ name: "DCC_COUNT0SRC_AUXCLKIN", displayName: "Auxiliary Clock input" },
	{ name: "DCC_COUNT0SRC_INPUTXBAR1_INPUT16", displayName: "Input 16 of INPUTXBAR" },
]
module.exports = {
	DCC_Count1ClockSource: DCC_Count1ClockSource,
	DCC_Count0ClockSource: DCC_Count0ClockSource,
}
