let SSU_CPUID = [
	{ name: "SSU_CPU1", displayName: "CPU1" },
	{ name: "SSU_CPU2", displayName: "CPU2" },
	{ name: "SSU_CPU3", displayName: "CPU3" },
]
let SSU_Link = [
	{ name: "SSU_LINK0", displayName: "LINK0" },
	{ name: "SSU_LINK1", displayName: "LINK1" },
	{ name: "SSU_LINK2", displayName: "LINK2" },
	{ name: "SSU_LINK3", displayName: "LINK3" },
	{ name: "SSU_LINK4", displayName: "LINK4" },
	{ name: "SSU_LINK5", displayName: "LINK5" },
	{ name: "SSU_LINK6", displayName: "LINK6" },
	{ name: "SSU_LINK7", displayName: "LINK7" },
	{ name: "SSU_LINK8", displayName: "LINK8" },
	{ name: "SSU_LINK9", displayName: "LINK9" },
	{ name: "SSU_LINK10", displayName: "LINK10" },
	{ name: "SSU_LINK11", displayName: "LINK11" },
	{ name: "SSU_LINK12", displayName: "LINK12" },
	{ name: "SSU_LINK13", displayName: "LINK13" },
	{ name: "SSU_LINK14", displayName: "LINK14" },
	{ name: "SSU_LINK15", displayName: "LINK15" },
]
let SSU_APExeLink = [
	{ name: "SSU_EXE_LINK1", displayName: "EXE LINK1" },
	{ name: "SSU_EXE_LINK2", displayName: "EXE LINK2" },
	{ name: "SSU_EXE_LINK3", displayName: "EXE LINK3" },
	{ name: "SSU_EXE_LINK4", displayName: "EXE LINK4" },
	{ name: "SSU_EXE_LINK5", displayName: "EXE LINK5" },
	{ name: "SSU_EXE_LINK6", displayName: "EXE LINK6" },
	{ name: "SSU_EXE_LINK7", displayName: "EXE LINK7" },
	{ name: "SSU_EXE_LINK8", displayName: "EXE LINK8" },
	{ name: "SSU_EXE_LINK9", displayName: "EXE LINK9" },
	{ name: "SSU_EXE_LINK10", displayName: "EXE LINK10" },
	{ name: "SSU_EXE_LINK11", displayName: "EXE LINK11" },
	{ name: "SSU_EXE_LINK12", displayName: "EXE LINK12" },
	{ name: "SSU_EXE_LINK13", displayName: "EXE LINK13" },
	{ name: "SSU_EXE_LINK14", displayName: "EXE LINK14" },
	{ name: "SSU_EXE_LINK15", displayName: "EXE LINK15" },
	{ name: "SSU_EXE_DISABLE", displayName: "EXE DISABLE" },
]
let SSU_APILink = [
	{ name: "SSU_API_LINK0", displayName: "API LINK0" },
	{ name: "SSU_API_LINK1", displayName: "API LINK1" },
	{ name: "SSU_API_LINK2", displayName: "API LINK2" },
	{ name: "SSU_API_LINK3", displayName: "API LINK3" },
	{ name: "SSU_API_LINK4", displayName: "API LINK4" },
	{ name: "SSU_API_LINK5", displayName: "API LINK5" },
	{ name: "SSU_API_LINK6", displayName: "API LINK6" },
	{ name: "SSU_API_LINK7", displayName: "API LINK7" },
	{ name: "SSU_API_LINK8", displayName: "API LINK8" },
	{ name: "SSU_API_LINK9", displayName: "API LINK9" },
	{ name: "SSU_API_LINK10", displayName: "API LINK10" },
	{ name: "SSU_API_LINK11", displayName: "API LINK11" },
	{ name: "SSU_API_LINK12", displayName: "API LINK12" },
	{ name: "SSU_API_LINK13", displayName: "API LINK13" },
	{ name: "SSU_API_LINK14", displayName: "API LINK14" },
	{ name: "SSU_API_LINK15", displayName: "API LINK15" },
	{ name: "SSU_API_DISABLE", displayName: "API DISABLE" },
]
let SSU_MemType = [
	{ name: "SSU_MEMTYPE_ROM", displayName: "MEMTYPE ROM" },
	{ name: "SSU_MEMTYPE_FLASH", displayName: "MEMTYPE FLASH" },
	{ name: "SSU_MEMTYPE_RAM", displayName: "MEMTYPE RAM" },
	{ name: "SSU_MEMTYPE_PERIPH", displayName: "MEMTYPE PERIPH" },
	{ name: "SSU_MEMTYPE_EXT", displayName: "MEMTYPE EXT" },
]
let SSU_Stack = [
	{ name: "SSU_STACK1", displayName: "STACK1" },
	{ name: "SSU_STACK2", displayName: "STACK2" },
	{ name: "SSU_STACK3", displayName: "STACK3" },
	{ name: "SSU_STACK4", displayName: "STACK4" },
	{ name: "SSU_STACK5", displayName: "STACK5" },
	{ name: "SSU_STACK6", displayName: "STACK6" },
	{ name: "SSU_STACK7", displayName: "STACK7" },
]
let SSU_Zone = [
	{ name: "SSU_ZONE1", displayName: "ZONE1" },
	{ name: "SSU_ZONE2", displayName: "ZONE2" },
	{ name: "SSU_ZONE3", displayName: "ZONE3" },
]
module.exports = {
	SSU_CPUID: SSU_CPUID,
	SSU_Link: SSU_Link,
	SSU_APExeLink: SSU_APExeLink,
	SSU_APILink: SSU_APILink,
	SSU_MemType: SSU_MemType,
	SSU_Stack: SSU_Stack,
	SSU_Zone: SSU_Zone,
}
