let CLBInputSignals = {
    "F29H85x": {
        "GLOBAL_MUX": {
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG0": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG1": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG2": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG3": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG4": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG5": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG6": true,
            "CLB_GLOBAL_IN_MUX_CLB_AUXSIG7": true,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT16": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT17": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT18": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT19": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT20": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT21": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT22": false,
            "CLB_GLOBAL_IN_MUX_CLB1_OUT23": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT16": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT17": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT18": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT19": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT20": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT21": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT22": false,
            "CLB_GLOBAL_IN_MUX_CLB2_OUT23": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT16": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT17": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT18": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT19": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT20": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT21": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT22": false,
            "CLB_GLOBAL_IN_MUX_CLB3_OUT23": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT16": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT17": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT18": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT19": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT20": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT21": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT22": false,
            "CLB_GLOBAL_IN_MUX_CLB4_OUT23": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT16": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT17": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT18": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT19": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT20": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT21": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT22": false,
            "CLB_GLOBAL_IN_MUX_CLB5_OUT23": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT16": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT17": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT18": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT19": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT20": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT21": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT22": false,
            "CLB_GLOBAL_IN_MUX_CLB6_OUT23": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT0": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT1": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT2": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT3": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT4": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT5": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT6": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_EVENT7": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_SEC_EVENT0": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_SEC_EVENT1": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_SEC_EVENT2": false,
            "CLB_GLOBAL_IN_MUX_CPU1_ERAD_SEC_EVENT3": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT0": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT1": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT2": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT3": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT4": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT5": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT6": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_EVENT7": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_SEC_EVENT0": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_SEC_EVENT1": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_SEC_EVENT2": false,
            "CLB_GLOBAL_IN_MUX_CPU2_ERAD_SEC_EVENT3": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT0": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT1": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT2": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT3": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT4": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT5": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT6": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_EVENT7": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_SEC_EVENT0": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_SEC_EVENT1": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_SEC_EVENT2": false,
            "CLB_GLOBAL_IN_MUX_CPU3_ERAD_SEC_EVENT3": false,
            "CLB_GLOBAL_IN_MUX_CPU3_HALT": false,
            "CLB_GLOBAL_IN_MUX_ECAT_EOF": true,
            "CLB_GLOBAL_IN_MUX_ECAT_SOF": true,
            "CLB_GLOBAL_IN_MUX_ECAT_SYNC0": true,
            "CLB_GLOBAL_IN_MUX_ECAT_SYNC1": true,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM1_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM1A": true,
            "CLB_GLOBAL_IN_MUX_EPWM1A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM1A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM1A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM1B": true,
            "CLB_GLOBAL_IN_MUX_EPWM1B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM1B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM1B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM2_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM2A": true,
            "CLB_GLOBAL_IN_MUX_EPWM2A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM2A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM2A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM2B": true,
            "CLB_GLOBAL_IN_MUX_EPWM2B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM2B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM2B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM3_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM3A": true,
            "CLB_GLOBAL_IN_MUX_EPWM3A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM3A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM3A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM3B": true,
            "CLB_GLOBAL_IN_MUX_EPWM3B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM3B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM3B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM4_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM4A": true,
            "CLB_GLOBAL_IN_MUX_EPWM4A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM4A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM4A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM4B": true,
            "CLB_GLOBAL_IN_MUX_EPWM4B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM4B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM4B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM5_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM5A": true,
            "CLB_GLOBAL_IN_MUX_EPWM5A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM5A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM5A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM5B": true,
            "CLB_GLOBAL_IN_MUX_EPWM5B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM5B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM5B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM6_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM6A": true,
            "CLB_GLOBAL_IN_MUX_EPWM6A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM6A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM6A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM6B": true,
            "CLB_GLOBAL_IN_MUX_EPWM6B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM6B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM6B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM7_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM7A": true,
            "CLB_GLOBAL_IN_MUX_EPWM7A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM7A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM7A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM7B": true,
            "CLB_GLOBAL_IN_MUX_EPWM7B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM7B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM7B_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTR_CMPA": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTR_CMPB": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTR_CMPC": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTR_CMPD": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTR_PRD": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTR_ZERO": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_CTRDIR": false,
            "CLB_GLOBAL_IN_MUX_EPWM8_TBCLK": false,
            "CLB_GLOBAL_IN_MUX_EPWM8A": true,
            "CLB_GLOBAL_IN_MUX_EPWM8A_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM8A_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM8A_OE": true,
            "CLB_GLOBAL_IN_MUX_EPWM8B": true,
            "CLB_GLOBAL_IN_MUX_EPWM8B_AQ": false,
            "CLB_GLOBAL_IN_MUX_EPWM8B_DB": false,
            "CLB_GLOBAL_IN_MUX_EPWM8B_OE": true,
            "CLB_GLOBAL_IN_MUX_FSIRXA_DATA_PACKET_RCVD": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_DATA_TAG_MATCH2": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_ERROR_PACKET_RCVD": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_ERROR_TAG_MATCH2": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_OUTPUT_FRAME_DONE": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_PING_PACKET_RCVD": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_PING_TAG_MATCH2": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_RX_TRIG2": false,
            "CLB_GLOBAL_IN_MUX_FSIRXA_RX_TRIG3": false,
            "CLB_GLOBAL_IN_MUX_FSIRXB_DATA_TAG_MATCH": false,
            "CLB_GLOBAL_IN_MUX_FSIRXB_ERROR_TAG_MATCH": false,
            "CLB_GLOBAL_IN_MUX_FSIRXB_PING_TAG_MATCH": false,
            "CLB_GLOBAL_IN_MUX_SPI1_SPICLK": true,
            "CLB_GLOBAL_IN_MUX_SPI1_SPIPOCI_CONTROLLER": true,
            "CLB_GLOBAL_IN_MUX_SPI1_SPIPTE": true,
            "CLB_GLOBAL_IN_MUX_SPI2_SPICLK": true,
            "CLB_GLOBAL_IN_MUX_SPI2_SPIPOCI_CONTROLLER": true,
            "CLB_GLOBAL_IN_MUX_SPI2_SPIPTE": true
        },
        "LOCAL_MUX": {
            "CLB_LOCAL_IN_MUX_GLOBAL_IN": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCAEVT1": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCAEVT2": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCBEVT1": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCBEVT2": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCAH": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCAL": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCBH": true,
            "CLB_LOCAL_IN_MUX_EPWM_DCBL": true,
            "CLB_LOCAL_IN_MUX_EPWM_OST": true,
            "CLB_LOCAL_IN_MUX_EPWM_CBC": true,
            "CLB_LOCAL_IN_MUX_ECAP_ECAPIN": true,
            "CLB_LOCAL_IN_MUX_ECAP_ECAP_OUT": false,
            "CLB_LOCAL_IN_MUX_ECAP_ECAP_OUT_EN": false,
            "CLB_LOCAL_IN_MUX_ECAP_CEVT1": false,
            "CLB_LOCAL_IN_MUX_ECAP_CEVT2": false,
            "CLB_LOCAL_IN_MUX_ECAP_CEVT3": false,
            "CLB_LOCAL_IN_MUX_ECAP_CEVT4": false,
            "CLB_LOCAL_IN_MUX_EQEP_EQEPA": true,
            "CLB_LOCAL_IN_MUX_FSI_DATA_PKT_RCVD": false,
            "CLB_LOCAL_IN_MUX_EQEP_EQEPB": true,
            "CLB_LOCAL_IN_MUX_FSI_ERROR_PKT_RCVD": false,
            "CLB_LOCAL_IN_MUX_EQEP_EQEPI": true,
            "CLB_LOCAL_IN_MUX_FSI_PING_PKT_RCVD": false,
            "CLB_LOCAL_IN_MUX_EQEP_EQEPS": true,
            "CLB_LOCAL_IN_MUX_CPU3_HALT": true,
            "CLB_LOCAL_IN_MUX_CPU1_TBCLKSYNC": false,
            "CLB_LOCAL_IN_MUX_CPU3_TBCLKSYNC": true,
            "CLB_LOCAL_IN_MUX_CPU2_TBCLKSYNC": false,
            "CLB_LOCAL_IN_MUX_CPU1_HALT": false,
            "CLB_LOCAL_IN_MUX_SPIPICO_CONTROLLER": true,
            "CLB_LOCAL_IN_MUX_SPICLK": true,
            "CLB_LOCAL_IN_MUX_SPIPICO_PERIPHERAL": true,
            "CLB_LOCAL_IN_MUX_SPIPTE": true,
            "CLB_LOCAL_IN_MUX_SPIPOCI_OUT": true,
            "CLB_LOCAL_IN_MUX_CLB_PSCLK": false,
            "CLB_LOCAL_IN_MUX_EPWM9A": true,
            "CLB_LOCAL_IN_MUX_ECAP5_ECAPIN": true,
            "CLB_LOCAL_IN_MUX_EPWM9A_OE": true,
            "CLB_LOCAL_IN_MUX_ECAP5_ECAP_OUT": false,
            "CLB_LOCAL_IN_MUX_EPWM9B": true,
            "CLB_LOCAL_IN_MUX_ECAP5_ECAP_OUT_EN": false,
            "CLB_LOCAL_IN_MUX_EPWM9B_OE": true,
            "CLB_LOCAL_IN_MUX_ECAP5_CEVT1": false,
            "CLB_LOCAL_IN_MUX_EPWM10A": true,
            "CLB_LOCAL_IN_MUX_ECAP5_CEVT2": false,
            "CLB_LOCAL_IN_MUX_EPWM10A_OE": true,
            "CLB_LOCAL_IN_MUX_ECAP5_CEVT3": false,
            "CLB_LOCAL_IN_MUX_EPWM10B": true,
            "CLB_LOCAL_IN_MUX_ECAP5_CEVT4": false,
            "CLB_LOCAL_IN_MUX_EPWM10B_OE": true,
            "CLB_LOCAL_IN_MUX_EPWM11A": true,
            "CLB_LOCAL_IN_MUX_EQEP5_EQEPA": true,
            "CLB_LOCAL_IN_MUX_EQEP6_EQEPA": true,
            "CLB_LOCAL_IN_MUX_EPWM11A_OE": true,
            "CLB_LOCAL_IN_MUX_EQEP5_EQEPB": true,
            "CLB_LOCAL_IN_MUX_EQEP6_EQEPB": true,
            "CLB_LOCAL_IN_MUX_EPWM11B": true,
            "CLB_LOCAL_IN_MUX_EQEP5_EQEPI": true,
            "CLB_LOCAL_IN_MUX_EQEP6_EQEPI": true,
            "CLB_LOCAL_IN_MUX_EPWM11B_OE": true,
            "CLB_LOCAL_IN_MUX_EQEP5_EQEPS": true,
            "CLB_LOCAL_IN_MUX_EQEP6_EQEPS": true,
            "CLB_LOCAL_IN_MUX_EPWM12A": true,
            "CLB_LOCAL_IN_MUX_EPWM16A": true,
            "CLB_LOCAL_IN_MUX_EPWM12A_OE": true,
            "CLB_LOCAL_IN_MUX_EPWM16A_OE": true,
            "CLB_LOCAL_IN_MUX_EPWM12B": true,
            "CLB_LOCAL_IN_MUX_EPWM16B": true,
            "CLB_LOCAL_IN_MUX_EPWM12B_OE": true,
            "CLB_LOCAL_IN_MUX_EPWM16B_OE": true,
            "CLB_LOCAL_IN_MUX_INPUT17": true,
            "CLB_LOCAL_IN_MUX_INPUT18": true,
            "CLB_LOCAL_IN_MUX_INPUT19": true,
            "CLB_LOCAL_IN_MUX_INPUT20": true,
            "CLB_LOCAL_IN_MUX_INPUT21": true,
            "CLB_LOCAL_IN_MUX_INPUT22": true,
            "CLB_LOCAL_IN_MUX_INPUT23": true,
            "CLB_LOCAL_IN_MUX_INPUT24": true,
            "CLB_LOCAL_IN_MUX_INPUT25": true,
            "CLB_LOCAL_IN_MUX_INPUT26": true,
            "CLB_LOCAL_IN_MUX_INPUT27": true,
            "CLB_LOCAL_IN_MUX_INPUT28": true,
            "CLB_LOCAL_IN_MUX_INPUT29": true,
            "CLB_LOCAL_IN_MUX_INPUT30": true,
            "CLB_LOCAL_IN_MUX_INPUT31": true,
            "CLB_LOCAL_IN_MUX_INPUT32": true
        },
        "OUT_OVERRIDE": {
            "CLB1": {
                "CLB_OUT0": "HRPWM1A",
                "CLB_OUT1": "HRPWM1A_OE",
                "CLB_OUT2": "HRPWM1B",
                "CLB_OUT3": "HRPWM1B_OE",
                "CLB_OUT4": "EPWM1A_AQ",
                "CLB_OUT5": "EPWM1B_AQ",
                "CLB_OUT6": "EPWM1A_DB",
                "CLB_OUT7": "EPWM1B_DB",
                "CLB_OUT8": "EQEP1_QCLK",
                "CLB_OUT9": "EQEP1_QDIR",
                "CLB_OUT10": "EQEP1_QB",
                "CLB_OUT11": "EQEP1_QA",
                "CLB_OUT12": "All XBARs",
                "CLB_OUT13": "All XBARs",
                "CLB_OUT14": "ECAP Mux",
                "CLB_OUT15": "ECAP Mux",
                "CLB_OUT16": "Global Mux",
                "CLB_OUT17": "Global Mux",
                "CLB_OUT18": "Global Mux",
                "CLB_OUT19": "Global Mux",
                "CLB_OUT20": "Global Mux",
                "CLB_OUT21": "Global Mux, SPIA_PTE_OUT",
                "CLB_OUT22": "Global Mux, SPIA_PICO_OUT",
                "CLB_OUT23": "Global Mux, SPIA_POCI_OUT",
                "CLB_OUT24": "SPIA_CLK_IN",
                "CLB_OUT25": "SPIA_PICO_IN",
                "CLB_OUT26": "SPIA_PTE_IN",
                "CLB_OUT27": "ADC_SOC_TRIGGERS",
                "CLB_OUT28": "ECAP1_OUT_EN",
                "CLB_OUT29": "ECAP1_OUT",
                "CLB_OUT30": "FSITX Triggers",
                "CLB_OUT31": "FSITX Triggers"
            },
            "CLB2": {
                "CLB_OUT0": "HRPWM2A",
                "CLB_OUT1": "HRPWM2A_OE",
                "CLB_OUT2": "HRPWM2B",
                "CLB_OUT3": "HRPWM2B_OE",
                "CLB_OUT4": "EPWM2A_AQ",
                "CLB_OUT5": "EPWM2B_AQ",
                "CLB_OUT6": "EPWM2A_DB",
                "CLB_OUT7": "EPWM2B_DB",
                "CLB_OUT8": "EQEP2_QCLK",
                "CLB_OUT9": "EQEP2_QDIR",
                "CLB_OUT10": "EQEP2_QB",
                "CLB_OUT11": "EQEP2_QA",
                "CLB_OUT12": "All XBARs",
                "CLB_OUT13": "All XBARs",
                "CLB_OUT14": "ECAP Mux",
                "CLB_OUT15": "ECAP Mux",
                "CLB_OUT16": "Global Mux",
                "CLB_OUT17": "Global Mux",
                "CLB_OUT18": "Global Mux",
                "CLB_OUT19": "Global Mux",
                "CLB_OUT20": "Global Mux",
                "CLB_OUT21": "Global Mux, SPIB_PTE_OUT",
                "CLB_OUT22": "Global Mux, SPIB_PICO_OUT",
                "CLB_OUT23": "Global Mux, SPIB_POCI_OUT",
                "CLB_OUT24": "SPIB_CLK_IN",
                "CLB_OUT25": "SPIB_PICO_IN",
                "CLB_OUT26": "SPIB_PTE_IN",
                "CLB_OUT27": "ADC_SOC_TRIGGERS",
                "CLB_OUT28": "ECAP2_OUT_EN",
                "CLB_OUT29": "ECAP2_OUT",
                "CLB_OUT30": "FSITX Triggers",
                "CLB_OUT31": "FSITX Triggers"
            },
            "CLB3": {
                "CLB_OUT0": "HRPWM3A",
                "CLB_OUT1": "HRPWM3A_OE",
                "CLB_OUT2": "HRPWM3B",
                "CLB_OUT3": "HRPWM3B_OE",
                "CLB_OUT4": "EPWM3A_AQ",
                "CLB_OUT5": "EPWM3B_AQ",
                "CLB_OUT6": "EPWM3A_DB",
                "CLB_OUT7": "EPWM3B_DB",
                "CLB_OUT8": "EQEP3_QA",
                "CLB_OUT9": "EQEP3_QB",
                "CLB_OUT10": "EQEP3_QDIR",
                "CLB_OUT11": "EQEP3_QCLK",
                "CLB_OUT12": "All XBARs",
                "CLB_OUT13": "All XBARs",
                "CLB_OUT14": "ECAP Mux",
                "CLB_OUT15": "ECAP Mux",
                "CLB_OUT16": "Global Mux",
                "CLB_OUT17": "Global Mux",
                "CLB_OUT18": "Global Mux",
                "CLB_OUT19": "Global Mux",
                "CLB_OUT20": "Global Mux",
                "CLB_OUT21": "Global Mux, SPIC_PTE_OUT",
                "CLB_OUT22": "Global Mux, SPIC_PICO_OUT",
                "CLB_OUT23": "Global Mux, SPIC_POCI_OUT",
                "CLB_OUT24": "SPIC_CLK_IN",
                "CLB_OUT25": "SPIC_PICO_IN",
                "CLB_OUT26": "SPIC_PTE_IN",
                "CLB_OUT27": "ADC_SOC_TRIGGERS",
                "CLB_OUT28": "ECAP3_OUT_EN",
                "CLB_OUT29": "ECAP3_OUT",
                "CLB_OUT30": "FSITX Triggers",
                "CLB_OUT31": "FSITX Triggers"
            },
            "CLB4": {
                "CLB_OUT0": "HRPWM4A",
                "CLB_OUT1": "HRPWM4A_OE",
                "CLB_OUT2": "HRPWM4B",
                "CLB_OUT3": "HRPWM4B_OE",
                "CLB_OUT4": "EPWM4A_AQ",
                "CLB_OUT5": "EPWM4B_AQ",
                "CLB_OUT6": "EPWM4A_DB",
                "CLB_OUT7": "EPWM4B_DB",
                "CLB_OUT8": "EQEP4_QA",
                "CLB_OUT9": "EQEP4_QB",
                "CLB_OUT10": "EQEP4_QDIR",
                "CLB_OUT11": "EQEP4_QCLK",
                "CLB_OUT12": "All XBARs",
                "CLB_OUT13": "All XBARs",
                "CLB_OUT14": "ECAP Mux",
                "CLB_OUT15": "ECAP Mux",
                "CLB_OUT16": "Global Mux",
                "CLB_OUT17": "Global Mux",
                "CLB_OUT18": "Global Mux",
                "CLB_OUT19": "Global Mux",
                "CLB_OUT20": "Global Mux",
                "CLB_OUT21": "Global Mux, SPIPTE_OUT",
                "CLB_OUT22": "Global Mux, SPID_PICO_OUT",
                "CLB_OUT23": "Global Mux, SPID_POCI_OUT",
                "CLB_OUT24": "SPID_CLK_IN",
                "CLB_OUT25": "SPID_PICO_IN",
                "CLB_OUT26": "SPID_PTE_IN",
                "CLB_OUT27": "ADC_SOC_TRIGGERS",
                "CLB_OUT28": "ECAP4_OUT_EN",
                "CLB_OUT29": "ECAP4_OUT",
                "CLB_OUT30": "FSITX Triggers",
                "CLB_OUT31": "FSITX Triggers"
            },
            "CLB5": {
                "CLB_OUT0": "HRPWM5A",
                "CLB_OUT1": "HRPWM5A_OE",
                "CLB_OUT2": "HRPWM5B",
                "CLB_OUT3": "HRPWM5B_OE",
                "CLB_OUT4": "EPWM5A_AQ",
                "CLB_OUT5": "EPWM5B_AQ",
                "CLB_OUT6": "EPWM5A_DB",
                "CLB_OUT7": "EPWM5B_DB",
                "CLB_OUT8": "EQEP5_QA",
                "CLB_OUT9": "EQEP5_QB",
                "CLB_OUT10": "EQEP5_QDIR",
                "CLB_OUT11": "EQEP5_QCLK",
                "CLB_OUT12": "All XBARs",
                "CLB_OUT13": "All XBARs",
                "CLB_OUT14": "ECAP Mux",
                "CLB_OUT15": "ECAP Mux",
                "CLB_OUT16": "Global Mux",
                "CLB_OUT17": "Global Mux",
                "CLB_OUT18": "Global Mux",
                "CLB_OUT19": "Global Mux",
                "CLB_OUT20": "Global Mux",
                "CLB_OUT21": "Global Mux, SPIE_PTE_OUT",
                "CLB_OUT22": "Global Mux, SPIE_PICO_OUT",
                "CLB_OUT23": "Global Mux, SPIE_POCI_OUT",
                "CLB_OUT24": "SPIE_CLK_IN",
                "CLB_OUT25": "SPIE_PICO_IN",
                "CLB_OUT26": "SPIE_PTE_IN",
                "CLB_OUT27": "ADC_SOC_TRIGGERS",
                "CLB_OUT28": "ECAP5_OUT_EN",
                "CLB_OUT29": "ECAP5_OUT",
                "CLB_OUT30": "FSITX Triggers",
                "CLB_OUT31": "FSITX Triggers"
            },
            "CLB6": {
                "CLB_OUT0": "HRPWM6A",
                "CLB_OUT1": "HRPWM6A_OE",
                "CLB_OUT2": "HRPWM6B",
                "CLB_OUT3": "HRPWM6B_OE",
                "CLB_OUT4": "EPWM6A_AQ",
                "CLB_OUT5": "EPWM6B_AQ",
                "CLB_OUT6": "EPWM6A_DB",
                "CLB_OUT7": "EPWM6B_DB",
                "CLB_OUT8": "EQEP6_QA",
                "CLB_OUT9": "EQEP6_QB",
                "CLB_OUT10": "EQEP6_QDIR",
                "CLB_OUT11": "EQEP6_QCLK",
                "CLB_OUT12": "All XBARs",
                "CLB_OUT13": "All XBARs",
                "CLB_OUT14": "ECAP Mux",
                "CLB_OUT15": "ECAP Mux",
                "CLB_OUT16": "Global Mux",
                "CLB_OUT17": "Global Mux",
                "CLB_OUT18": "Global Mux",
                "CLB_OUT19": "Global Mux",
                "CLB_OUT20": "Global Mux",
                "CLB_OUT21": "Global Mux",
                "CLB_OUT22": "Global Mux",
                "CLB_OUT23": "Global Mux",
                "CLB_OUT24": "Global Mux",
                "CLB_OUT25": "Global Mux",
                "CLB_OUT26": "Global Mux",
                "CLB_OUT27": "ADC_SOC_TRIGGERS",
                "CLB_OUT28": "ECAP6_OUT_EN",
                "CLB_OUT29": "ECAP6_OUT",
                "CLB_OUT30": "FSITX Triggers",
                "CLB_OUT31": "FSITX Triggers"
            }
        }
    }
}

exports = {
    CLBInputSignals: CLBInputSignals,
}